/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditContributionDialog.java
 *
 * Created on 18.04.2013, 12:08:44
 */
package org.exmaralda.orthonormal.gui;

import java.awt.event.MouseEvent;
import java.util.Vector;
import org.exmaralda.folker.data.Contribution;
import org.exmaralda.folker.data.Timepoint;
import org.exmaralda.folker.listview.ContributionTextPane;
import org.exmaralda.folker.listview.ContributionTextPaneListener;
import org.exmaralda.orthonormal.application.ApplicationControl;

/**
 *
 * @author Schmidt
 */
public class EditContributionDialog extends javax.swing.JDialog implements ContributionTextPaneListener  {

    ContributionTextPane contributionTextPane;
    ApplicationControl applicationControl;
    public boolean ok;
    //Vector<ContributionTextPaneListener> listeners = new Vector<ContributionTextPaneListener>();
    
    
    /** Creates new form EditContributionDialog */
    public EditContributionDialog(java.awt.Frame parent, ApplicationControl ac, boolean modal) {
        super(parent, modal);
        applicationControl = ac;
        initComponents();
        contributionTextPane = new ContributionTextPane();
        //contributionTextPane.addContributionTextPaneListener(this);
        editScrollPane.setViewportView(contributionTextPane);        
        pack();
    }
    
    public void setContribution(Contribution contribution){
        contributionTextPane.setContribution(contribution);
    }
    
    public Contribution getContribution(){
        return contributionTextPane.getContribution();
    }
    
    public void addContributionTextPaneListener(ContributionTextPaneListener l){
        contributionTextPane.addContributionTextPaneListener(l);
        //listeners.addElement(l);
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        upperPanel = new javax.swing.JPanel();
        playButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        editScrollPane = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Beitrag bearbeiten");

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        jPanel1.add(okButton);

        cancelButton.setText("Abbrechen");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelButton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        playButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/exmaralda/folker/tangoicons/tango-icon-theme-0.8.1/22x22/actions/media-playback-start.png"))); // NOI18N
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });
        upperPanel.add(playButton);

        stopButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/exmaralda/folker/tangoicons/tango-icon-theme-0.8.1/22x22/actions/media-playback-stop.png"))); // NOI18N
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });
        upperPanel.add(stopButton);

        getContentPane().add(upperPanel, java.awt.BorderLayout.NORTH);

        editScrollPane.setMinimumSize(new java.awt.Dimension(400, 300));
        editScrollPane.setPreferredSize(new java.awt.Dimension(600, 300));
        getContentPane().add(editScrollPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        applicationControl.playSelection();        
    }//GEN-LAST:event_playButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        contributionTextPane.validateContribution();
        ok = true;
        setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        ok = false;
        setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        applicationControl.stop();
    }//GEN-LAST:event_stopButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditContributionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditContributionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditContributionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditContributionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                EditContributionDialog dialog = new EditContributionDialog(new javax.swing.JFrame(), null, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JScrollPane editScrollPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton okButton;
    private javax.swing.JButton playButton;
    private javax.swing.JButton stopButton;
    private javax.swing.JPanel upperPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void validateContribution() {
        ok = true;
        setVisible(false);
    }

    @Override
    public void processTimepoint(Timepoint tp) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void processTimepoint(Timepoint tp, MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }
}
