/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.exmaralda.partitureditor.multimodalPanel;

import java.util.ArrayList;
import javax.swing.JButton;
import org.exmaralda.partitureditor.unicodeKeyboard.UnicodeKeyboardEvent;
import org.exmaralda.partitureditor.unicodeKeyboard.UnicodeKeyboardListener;

/**
 *
 * @author Schmidt
 */
public class MultimodalPanel extends javax.swing.JPanel {

    private final ArrayList<UnicodeKeyboardListener> listeners = new ArrayList<UnicodeKeyboardListener>();
    
    /**
     * Creates new form MultimodalPanel
     */
    public MultimodalPanel() {
        initComponents();
    }

    protected void fireUnicodeKeyPressed(String t) {
        UnicodeKeyboardEvent event = new UnicodeKeyboardEvent(t);
        for (UnicodeKeyboardListener listener : listeners) {
            listener.performUnicodeKeyboardAction(event);             
         }
    }
    
    public void addUnicodeKeyboardListener(UnicodeKeyboardListener listener){
        listeners.add(listener);
    }

    private void updatePeriodButton(){
        int length = ((Integer) milisecondsSpinner.getValue()).intValue();
        String type = (String) typeComboBox.getSelectedItem();
        String period = "";
        for (int i=0; i<length; i++){
            if ("Preparation".equals(type)) period+=".";
            if ("Holding".equals(type)) period+="-";
            if ("Retraction".equals(type)) period+=",";
        }
        period+=">";
        periodButton.setText(period);        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainTabbedPane = new javax.swing.JTabbedPane();
        headPanel = new javax.swing.JPanel();
        headIconPanel = new javax.swing.JPanel();
        headIconLabel = new javax.swing.JLabel();
        headInputPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        eyesPanel = new javax.swing.JPanel();
        eyesIconPanel = new javax.swing.JPanel();
        eyesIconLabel = new javax.swing.JLabel();
        eyesInputPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton27 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jButton28 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jButton42 = new javax.swing.JButton();
        browsPanel = new javax.swing.JPanel();
        mouthPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        periodsPanel = new javax.swing.JPanel();
        typeComboBox = new javax.swing.JComboBox();
        milisecondsSpinner = new javax.swing.JSpinner();
        milisecondsLabel = new javax.swing.JLabel();
        periodButton = new javax.swing.JButton();
        buttonPanel = new javax.swing.JPanel();
        kineButton = new javax.swing.JButton();
        kineBeginButton = new javax.swing.JButton();
        kineContinueButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        headPanel.setLayout(new java.awt.BorderLayout());

        headIconPanel.setBackground(new java.awt.Color(255, 255, 255));

        headIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/exmaralda/partitureditor/multimodalPanel/head.png"))); // NOI18N
        headIconPanel.add(headIconLabel);

        headPanel.add(headIconPanel, java.awt.BorderLayout.CENTER);

        headInputPanel.setBackground(new java.awt.Color(255, 255, 255));
        headInputPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Motion type");
        jLabel1.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        headInputPanel.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("/");
        jLabel2.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        headInputPanel.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("V");
        jLabel3.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        headInputPanel.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("H");
        jLabel4.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        headInputPanel.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("S");
        jLabel5.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        headInputPanel.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("/");
        jLabel6.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        headInputPanel.add(jLabel6, gridBagConstraints);

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                symbolButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        headInputPanel.add(jButton1, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("r: rotated");
        jLabel7.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        headInputPanel.add(jLabel7, gridBagConstraints);

        jButton2.setText("<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                symbolButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        headInputPanel.add(jButton2, gridBagConstraints);

        jButton3.setText(">");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                symbolButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        headInputPanel.add(jButton3, gridBagConstraints);

        jButton4.setText("\u02c4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                symbolButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        headInputPanel.add(jButton4, gridBagConstraints);

        jButton5.setText("\u02c5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                symbolButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        headInputPanel.add(jButton5, gridBagConstraints);

        jButton6.setText("\\");
            jButton6.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 6;
            gridBagConstraints.gridy = 3;
            headInputPanel.add(jButton6, gridBagConstraints);

            jButton7.setText("/");
            jButton7.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 7;
            gridBagConstraints.gridy = 3;
            headInputPanel.add(jButton7, gridBagConstraints);

            jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
            jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel8.setText("t: translated");
            jLabel8.setOpaque(true);
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 0;
            gridBagConstraints.gridy = 4;
            gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
            gridBagConstraints.ipadx = 10;
            headInputPanel.add(jLabel8, gridBagConstraints);

            jButton8.setText("\u2534");
            jButton8.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 2;
            gridBagConstraints.gridy = 4;
            headInputPanel.add(jButton8, gridBagConstraints);

            jButton9.setText("\u2514");
            jButton9.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 4;
            gridBagConstraints.gridy = 4;
            headInputPanel.add(jButton9, gridBagConstraints);

            jButton10.setText("\u2568");
            jButton10.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 6;
            gridBagConstraints.gridy = 4;
            headInputPanel.add(jButton10, gridBagConstraints);

            jButton11.setText("\u2565");
            jButton11.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 7;
            gridBagConstraints.gridy = 4;
            headInputPanel.add(jButton11, gridBagConstraints);

            jButton12.setText("\u252c");
            jButton12.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 3;
            gridBagConstraints.gridy = 4;
            headInputPanel.add(jButton12, gridBagConstraints);

            jButton13.setText("\u2518");
            jButton13.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 5;
            gridBagConstraints.gridy = 4;
            headInputPanel.add(jButton13, gridBagConstraints);

            jLabel9.setBackground(new java.awt.Color(0, 0, 0));
            jLabel9.setForeground(new java.awt.Color(255, 255, 255));
            jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel9.setText("AXIS");
            jLabel9.setOpaque(true);
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 1;
            gridBagConstraints.gridy = 0;
            gridBagConstraints.gridwidth = 7;
            gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
            headInputPanel.add(jLabel9, gridBagConstraints);

            headPanel.add(headInputPanel, java.awt.BorderLayout.SOUTH);

            mainTabbedPane.addTab("Head", headPanel);

            eyesPanel.setLayout(new java.awt.BorderLayout());

            eyesIconPanel.setBackground(new java.awt.Color(255, 255, 255));

            eyesIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/exmaralda/partitureditor/multimodalPanel/eyes.png"))); // NOI18N
            eyesIconPanel.add(eyesIconLabel);

            eyesPanel.add(eyesIconPanel, java.awt.BorderLayout.CENTER);

            eyesInputPanel.setBackground(new java.awt.Color(255, 255, 255));
            eyesInputPanel.setLayout(new java.awt.GridBagLayout());

            jLabel10.setBackground(new java.awt.Color(0, 0, 0));
            jLabel10.setForeground(new java.awt.Color(255, 255, 255));
            jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel10.setText("Eye shape");
            jLabel10.setOpaque(true);
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 0;
            gridBagConstraints.gridy = 0;
            gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
            eyesInputPanel.add(jLabel10, gridBagConstraints);

            jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
            jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel11.setText("/");
            jLabel11.setOpaque(true);
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 1;
            gridBagConstraints.gridy = 1;
            gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
            eyesInputPanel.add(jLabel11, gridBagConstraints);

            jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
            jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel12.setText("V");
            jLabel12.setOpaque(true);
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 2;
            gridBagConstraints.gridy = 1;
            gridBagConstraints.gridwidth = 2;
            gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
            eyesInputPanel.add(jLabel12, gridBagConstraints);

            jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
            jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel13.setText("D1");
            jLabel13.setOpaque(true);
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 4;
            gridBagConstraints.gridy = 1;
            gridBagConstraints.gridwidth = 2;
            gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
            eyesInputPanel.add(jLabel13, gridBagConstraints);

            jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
            jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel14.setText("H");
            jLabel14.setOpaque(true);
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 6;
            gridBagConstraints.gridy = 1;
            gridBagConstraints.gridwidth = 2;
            gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
            eyesInputPanel.add(jLabel14, gridBagConstraints);

            jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
            jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel19.setText("D2");
            jLabel19.setOpaque(true);
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 8;
            gridBagConstraints.gridy = 1;
            gridBagConstraints.gridwidth = 2;
            gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
            eyesInputPanel.add(jLabel19, gridBagConstraints);

            jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
            jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel16.setText("open");
            jLabel16.setOpaque(true);
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 0;
            gridBagConstraints.gridy = 3;
            gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
            eyesInputPanel.add(jLabel16, gridBagConstraints);

            jButton27.setText("ϴ");
            jButton27.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 1;
            gridBagConstraints.gridy = 3;
            eyesInputPanel.add(jButton27, gridBagConstraints);

            jButton15.setText("'ϴ'");
            jButton15.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 2;
            gridBagConstraints.gridy = 3;
            eyesInputPanel.add(jButton15, gridBagConstraints);

            jButton16.setText(",ϴ,");
            jButton16.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 3;
            gridBagConstraints.gridy = 3;
            eyesInputPanel.add(jButton16, gridBagConstraints);

            jButton17.setText("''ϴ");
            jButton17.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 4;
            gridBagConstraints.gridy = 3;
            eyesInputPanel.add(jButton17, gridBagConstraints);

            jButton18.setText("ϴ,,");
            jButton18.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 5;
            gridBagConstraints.gridy = 3;
            eyesInputPanel.add(jButton18, gridBagConstraints);

            jButton19.setText("#ϴ");
            jButton19.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 6;
            gridBagConstraints.gridy = 3;
            eyesInputPanel.add(jButton19, gridBagConstraints);

            jButton20.setText("ϴ#");
            jButton20.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 7;
            gridBagConstraints.gridy = 3;
            eyesInputPanel.add(jButton20, gridBagConstraints);

            jButton29.setText(",,ϴ");
            jButton29.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 8;
            gridBagConstraints.gridy = 3;
            eyesInputPanel.add(jButton29, gridBagConstraints);

            jButton30.setText("ϴ''");
            jButton30.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 9;
            gridBagConstraints.gridy = 3;
            eyesInputPanel.add(jButton30, gridBagConstraints);

            jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
            jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel17.setText("narrowed");
            jLabel17.setOpaque(true);
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 0;
            gridBagConstraints.gridy = 4;
            gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
            gridBagConstraints.ipadx = 10;
            eyesInputPanel.add(jLabel17, gridBagConstraints);

            jButton28.setText("=");
            jButton28.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 1;
            gridBagConstraints.gridy = 4;
            eyesInputPanel.add(jButton28, gridBagConstraints);

            jButton21.setText("'='");
            jButton21.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 2;
            gridBagConstraints.gridy = 4;
            eyesInputPanel.add(jButton21, gridBagConstraints);

            jButton22.setText("''=");
            jButton22.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 4;
            gridBagConstraints.gridy = 4;
            eyesInputPanel.add(jButton22, gridBagConstraints);

            jButton23.setText("#=");
            jButton23.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 6;
            gridBagConstraints.gridy = 4;
            eyesInputPanel.add(jButton23, gridBagConstraints);

            jButton24.setText("=#");
            jButton24.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 7;
            gridBagConstraints.gridy = 4;
            eyesInputPanel.add(jButton24, gridBagConstraints);

            jButton25.setText(",=,");
            jButton25.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 3;
            gridBagConstraints.gridy = 4;
            eyesInputPanel.add(jButton25, gridBagConstraints);

            jButton26.setText("=,,");
            jButton26.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 5;
            gridBagConstraints.gridy = 4;
            eyesInputPanel.add(jButton26, gridBagConstraints);

            jLabel18.setBackground(new java.awt.Color(0, 0, 0));
            jLabel18.setForeground(new java.awt.Color(255, 255, 255));
            jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel18.setText("AXIS");
            jLabel18.setOpaque(true);
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 1;
            gridBagConstraints.gridy = 0;
            gridBagConstraints.gridwidth = 9;
            gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
            eyesInputPanel.add(jLabel18, gridBagConstraints);

            jButton31.setText(",,=");
            jButton31.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 8;
            gridBagConstraints.gridy = 4;
            eyesInputPanel.add(jButton31, gridBagConstraints);

            jButton32.setText("=''");
            jButton32.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 9;
            gridBagConstraints.gridy = 4;
            eyesInputPanel.add(jButton32, gridBagConstraints);

            jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
            jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel20.setText("wide open");
            jLabel20.setOpaque(true);
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 0;
            gridBagConstraints.gridy = 2;
            gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
            gridBagConstraints.ipadx = 10;
            eyesInputPanel.add(jLabel20, gridBagConstraints);

            jButton33.setText("O");
            jButton33.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 1;
            gridBagConstraints.gridy = 2;
            eyesInputPanel.add(jButton33, gridBagConstraints);

            jButton34.setText("'O'");
            jButton34.setToolTipText("");
            jButton34.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 2;
            gridBagConstraints.gridy = 2;
            eyesInputPanel.add(jButton34, gridBagConstraints);

            jButton35.setText(",O,");
            jButton35.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 3;
            gridBagConstraints.gridy = 2;
            eyesInputPanel.add(jButton35, gridBagConstraints);

            jButton36.setText("''O");
            jButton36.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 4;
            gridBagConstraints.gridy = 2;
            eyesInputPanel.add(jButton36, gridBagConstraints);

            jButton37.setText("O,,");
            jButton37.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 5;
            gridBagConstraints.gridy = 2;
            eyesInputPanel.add(jButton37, gridBagConstraints);

            jButton38.setText("#O");
            jButton38.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 6;
            gridBagConstraints.gridy = 2;
            eyesInputPanel.add(jButton38, gridBagConstraints);

            jButton39.setText("O#");
            jButton39.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 7;
            gridBagConstraints.gridy = 2;
            eyesInputPanel.add(jButton39, gridBagConstraints);

            jButton40.setText(",,O");
            jButton40.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 8;
            gridBagConstraints.gridy = 2;
            eyesInputPanel.add(jButton40, gridBagConstraints);

            jButton41.setText("O''");
            jButton41.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 9;
            gridBagConstraints.gridy = 2;
            eyesInputPanel.add(jButton41, gridBagConstraints);

            jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
            jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel21.setText("closed");
            jLabel21.setOpaque(true);
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 0;
            gridBagConstraints.gridy = 5;
            gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
            gridBagConstraints.ipadx = 10;
            eyesInputPanel.add(jLabel21, gridBagConstraints);

            jButton42.setText("U");
            jButton42.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 1;
            gridBagConstraints.gridy = 5;
            eyesInputPanel.add(jButton42, gridBagConstraints);

            eyesPanel.add(eyesInputPanel, java.awt.BorderLayout.SOUTH);

            mainTabbedPane.addTab("Eyes", eyesPanel);

            javax.swing.GroupLayout browsPanelLayout = new javax.swing.GroupLayout(browsPanel);
            browsPanel.setLayout(browsPanelLayout);
            browsPanelLayout.setHorizontalGroup(
                browsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 0, Short.MAX_VALUE)
            );
            browsPanelLayout.setVerticalGroup(
                browsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 0, Short.MAX_VALUE)
            );

            mainTabbedPane.addTab("Brows", browsPanel);

            javax.swing.GroupLayout mouthPanelLayout = new javax.swing.GroupLayout(mouthPanel);
            mouthPanel.setLayout(mouthPanelLayout);
            mouthPanelLayout.setHorizontalGroup(
                mouthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 0, Short.MAX_VALUE)
            );
            mouthPanelLayout.setVerticalGroup(
                mouthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 0, Short.MAX_VALUE)
            );

            mainTabbedPane.addTab("Mouth", mouthPanel);

            add(mainTabbedPane, java.awt.BorderLayout.CENTER);

            topPanel.setLayout(new java.awt.BorderLayout());

            periodsPanel.setBackground(new java.awt.Color(255, 255, 255));

            typeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Preparation", "Holding", "Retraction" }));
            typeComboBox.setMaximumSize(new java.awt.Dimension(100, 20));
            typeComboBox.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    typeComboBoxActionPerformed(evt);
                }
            });
            periodsPanel.add(typeComboBox);

            milisecondsSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 500, 1));
            milisecondsSpinner.setMaximumSize(new java.awt.Dimension(100, 20));
            milisecondsSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
                public void stateChanged(javax.swing.event.ChangeEvent evt) {
                    milisecondsSpinnerStateChanged(evt);
                }
            });
            milisecondsSpinner.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
                public void propertyChange(java.beans.PropertyChangeEvent evt) {
                    milisecondsSpinnerPropertyChange(evt);
                }
            });
            periodsPanel.add(milisecondsSpinner);

            milisecondsLabel.setText("ms");
            periodsPanel.add(milisecondsLabel);

            periodButton.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
            periodButton.setText(".>");
            periodButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            periodsPanel.add(periodButton);

            topPanel.add(periodsPanel, java.awt.BorderLayout.CENTER);

            buttonPanel.setBackground(new java.awt.Color(255, 255, 255));

            kineButton.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
            kineButton.setText("{x}");
            kineButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            buttonPanel.add(kineButton);

            kineBeginButton.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
            kineBeginButton.setText("°{x}");
            kineBeginButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            buttonPanel.add(kineBeginButton);

            kineContinueButton.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
            kineContinueButton.setText("---°");
            kineContinueButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    symbolButtonActionPerformed(evt);
                }
            });
            buttonPanel.add(kineContinueButton);

            topPanel.add(buttonPanel, java.awt.BorderLayout.PAGE_END);

            add(topPanel, java.awt.BorderLayout.PAGE_START);
        }// </editor-fold>//GEN-END:initComponents

    
    
    private void milisecondsSpinnerPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_milisecondsSpinnerPropertyChange

    }//GEN-LAST:event_milisecondsSpinnerPropertyChange

    private void milisecondsSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_milisecondsSpinnerStateChanged
        updatePeriodButton();
    }//GEN-LAST:event_milisecondsSpinnerStateChanged

    private void typeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeComboBoxActionPerformed
        updatePeriodButton();
    }//GEN-LAST:event_typeComboBoxActionPerformed

    private void symbolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_symbolButtonActionPerformed
        JButton button = (JButton)evt.getSource();
        String text = button.getText();
        System.out.println("Firing: " + text);
        fireUnicodeKeyPressed(text);                
    }//GEN-LAST:event_symbolButtonActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel browsPanel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JLabel eyesIconLabel;
    private javax.swing.JPanel eyesIconPanel;
    private javax.swing.JPanel eyesInputPanel;
    private javax.swing.JPanel eyesPanel;
    private javax.swing.JLabel headIconLabel;
    private javax.swing.JPanel headIconPanel;
    private javax.swing.JPanel headInputPanel;
    private javax.swing.JPanel headPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton kineBeginButton;
    private javax.swing.JButton kineButton;
    private javax.swing.JButton kineContinueButton;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JLabel milisecondsLabel;
    private javax.swing.JSpinner milisecondsSpinner;
    private javax.swing.JPanel mouthPanel;
    private javax.swing.JButton periodButton;
    private javax.swing.JPanel periodsPanel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JComboBox typeComboBox;
    // End of variables declaration//GEN-END:variables
}
