/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TaggingOptionsPanel.java
 *
 * Created on 12.05.2011, 14:24:02
 */

package org.exmaralda.tagging.swing;

import java.util.prefs.Preferences;
import org.exmaralda.tagging.TaggingProfiles;

/**
 *
 * @author thomas
 */
public class TaggingOptionsPanel extends javax.swing.JPanel {

    /** Creates new form TaggingOptionsPanel */
    public TaggingOptionsPanel() {
        initComponents();
        Preferences preferences = java.util.prefs.Preferences.userRoot().node(TaggingProfiles.PREFERENCES_NODE);
        taggingProfileComboBox.setSelectedItem(preferences.get("tagging-profile-name", "HIAT transcription - words and punctuation"));
        writeSextantFilesCheckBox.setSelected(preferences.getBoolean("write-sextant", true));
        integrateCheckBox.setSelected(preferences.getBoolean("integrate-sextant", true));
        sextantSuffixTextField.setText(preferences.get("sextant-suffix", "_POS"));
    }

    public String getTaggingProfileName(){
        return (String)(taggingProfileComboBox.getSelectedItem());
    }

    public String getFilenameSuffix(){
        return sextantSuffixTextField.getText();
    }

    public boolean writeSextantFiles(){
        return writeSextantFilesCheckBox.isSelected();
    }

    public boolean integrateSextantFiles(){
        return integrateCheckBox.isSelected();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        taggingProfileComboBox = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        sextantSuffixLabel = new javax.swing.JLabel();
        sextantSuffixTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        writeSextantFilesCheckBox = new javax.swing.JCheckBox();
        integrateCheckBox = new javax.swing.JCheckBox();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Tagging Options"));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Tagging Profile: ");
        jLabel1.setMaximumSize(new java.awt.Dimension(113, 14));
        jLabel1.setMinimumSize(new java.awt.Dimension(113, 14));
        jLabel1.setPreferredSize(new java.awt.Dimension(113, 14));
        jPanel1.add(jLabel1);

        taggingProfileComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "HIAT transcription - words and punctuation", "cGAT minimal transcription - words", "Generic - words and punctuation" }));
        taggingProfileComboBox.setMaximumSize(new java.awt.Dimension(450, 20));
        taggingProfileComboBox.setMinimumSize(new java.awt.Dimension(450, 20));
        taggingProfileComboBox.setPreferredSize(new java.awt.Dimension(450, 20));
        jPanel1.add(taggingProfileComboBox);

        add(jPanel1);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        sextantSuffixLabel.setText("Filename Suffix: ");
        sextantSuffixLabel.setMaximumSize(new java.awt.Dimension(113, 14));
        sextantSuffixLabel.setMinimumSize(new java.awt.Dimension(113, 14));
        sextantSuffixLabel.setPreferredSize(new java.awt.Dimension(113, 14));
        jPanel2.add(sextantSuffixLabel);

        sextantSuffixTextField.setText("_POS");
        sextantSuffixTextField.setMaximumSize(new java.awt.Dimension(450, 20));
        sextantSuffixTextField.setMinimumSize(new java.awt.Dimension(450, 20));
        sextantSuffixTextField.setPreferredSize(new java.awt.Dimension(450, 20));
        jPanel2.add(sextantSuffixTextField);

        add(jPanel2);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        writeSextantFilesCheckBox.setSelected(true);
        writeSextantFilesCheckBox.setText("Write Sextant Standoff Annotation Files");
        writeSextantFilesCheckBox.setMaximumSize(new java.awt.Dimension(250, 21));
        writeSextantFilesCheckBox.setMinimumSize(new java.awt.Dimension(250, 21));
        writeSextantFilesCheckBox.setPreferredSize(new java.awt.Dimension(250, 21));
        jPanel3.add(writeSextantFilesCheckBox);

        integrateCheckBox.setSelected(true);
        integrateCheckBox.setText("Integrate result into Segmented Transcription");
        integrateCheckBox.setMaximumSize(new java.awt.Dimension(250, 21));
        integrateCheckBox.setMinimumSize(new java.awt.Dimension(250, 21));
        integrateCheckBox.setPreferredSize(new java.awt.Dimension(250, 21));
        jPanel3.add(integrateCheckBox);

        add(jPanel3);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox integrateCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel sextantSuffixLabel;
    private javax.swing.JTextField sextantSuffixTextField;
    private javax.swing.JComboBox taggingProfileComboBox;
    private javax.swing.JCheckBox writeSextantFilesCheckBox;
    // End of variables declaration//GEN-END:variables

}
