/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TreeTaggerParametersPanel.java
 *
 * Created on 24.03.2011, 13:53:03
 */

package org.exmaralda.tagging.swing;

import java.io.File;
import java.util.prefs.Preferences;
import javax.swing.JFileChooser;
import org.exmaralda.partitureditor.jexmaraldaswing.fileFilters.ParameterFileFilter;
import org.exmaralda.tagging.TaggingProfiles;

/**
 *
 * @author thomas
 */
public class TreeTaggerParametersPanel extends javax.swing.JPanel {

    /** Creates new form TreeTaggerParametersPanel */
    public TreeTaggerParametersPanel() {
        initComponents();
        Preferences preferences = java.util.prefs.Preferences.userRoot().node(TaggingProfiles.PREFERENCES_NODE);
        directoryTextField.setText(preferences.get("directory", ""));
        parametersFileTextField.setText(preferences.get("parameter-file", ""));
        encodingComboBox.setSelectedItem(preferences.get("parameter-file-encoding", "iso8859-1"));
        lemmasCheckBox.setSelected(preferences.getBoolean("lemma-option", true));
        postagsCheckBox.setSelected(preferences.getBoolean("token-option", true));

    }

    public String treeTaggerDirectory = "S:\\TP-Z2\\TAGGING\\TreeTagger\\bin\\tree-tagger.exe";
    public String parameterFile = "S:\\TP-Z2\\TAGGING\\TreeTagger\\lib\\german.par";
    public String[] options = {"token","lemma","sgml","no-unknown"};

    public String getTreeTaggerDirectory(){
        return directoryTextField.getText();
    }

    public String getParameterFile(){
        return parametersFileTextField.getText();
    }

    public String getParameterFileEncoding(){
        return (String)(encodingComboBox.getSelectedItem());
    }

    public String[] getOptions(){
        if (lemmasCheckBox.isSelected() && postagsCheckBox.isSelected()){
            return new String[] {"-token","-lemma","-sgml","-no-unknown"};
        } else if (lemmasCheckBox.isSelected()){
            return new String[] {"-lemma","-sgml","-no-unknown"};
        } else if (postagsCheckBox.isSelected()){
            return new String[] {"-token","-sgml","-no-unknown"};
        }
        return new String[] {"-sgml","-no-unknown"};
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        directoryTextField = new javax.swing.JTextField();
        browseForDirectoryButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        parametersFileTextField = new javax.swing.JTextField();
        encodingComboBox = new javax.swing.JComboBox();
        browseForParametersFileButton = new javax.swing.JButton();
        optionsPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        postagsCheckBox = new javax.swing.JCheckBox();
        lemmasCheckBox = new javax.swing.JCheckBox();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Tree Tagger Parameters"));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Tree Tagger Directory: ");
        jPanel1.add(jLabel1);

        directoryTextField.setPreferredSize(new java.awt.Dimension(450, 20));
        jPanel1.add(directoryTextField);

        browseForDirectoryButton.setText("Browse...");
        browseForDirectoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseForDirectoryButtonActionPerformed(evt);
            }
        });
        jPanel1.add(browseForDirectoryButton);

        add(jPanel1);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("Parameters file: ");
        jLabel2.setMaximumSize(new java.awt.Dimension(113, 14));
        jLabel2.setMinimumSize(new java.awt.Dimension(113, 14));
        jLabel2.setPreferredSize(new java.awt.Dimension(113, 14));
        jPanel2.add(jLabel2);

        parametersFileTextField.setPreferredSize(new java.awt.Dimension(450, 20));
        jPanel2.add(parametersFileTextField);

        encodingComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "iso8859-1", "utf-8" }));
        jPanel2.add(encodingComboBox);

        browseForParametersFileButton.setText("Browse...");
        browseForParametersFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseForParametersFileButtonActionPerformed(evt);
            }
        });
        jPanel2.add(browseForParametersFileButton);

        add(jPanel2);

        optionsPanel.setLayout(new javax.swing.BoxLayout(optionsPanel, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setText("Output:");
        jLabel3.setMaximumSize(new java.awt.Dimension(60, 14));
        jLabel3.setMinimumSize(new java.awt.Dimension(60, 14));
        jLabel3.setPreferredSize(new java.awt.Dimension(60, 14));
        optionsPanel.add(jLabel3);

        postagsCheckBox.setSelected(true);
        postagsCheckBox.setText("Part of Speech Tags");
        optionsPanel.add(postagsCheckBox);

        lemmasCheckBox.setSelected(true);
        lemmasCheckBox.setText("Lemmas");
        optionsPanel.add(lemmasCheckBox);

        add(optionsPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void browseForDirectoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseForDirectoryButtonActionPerformed
        JFileChooser jfc = new JFileChooser();
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jfc.setDialogTitle("Locate the TreeTagger installation directory");
        jfc.setCurrentDirectory(new File(directoryTextField.getText()));
        int a = jfc.showOpenDialog(this);
        if (a == JFileChooser.APPROVE_OPTION){
            directoryTextField.setText(jfc.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_browseForDirectoryButtonActionPerformed

    private void browseForParametersFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseForParametersFileButtonActionPerformed
        JFileChooser jfc = new JFileChooser();
        jfc.setDialogTitle("Locate a TreeTagger parameters file");
        jfc.setFileFilter(new ParameterFileFilter("par", "Tree Tagger Parameter Files (*.par)"));
        jfc.setCurrentDirectory(new File(directoryTextField.getText()));
        int a = jfc.showOpenDialog(this);
        if (a == JFileChooser.APPROVE_OPTION){
            parametersFileTextField.setText(jfc.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_browseForParametersFileButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseForDirectoryButton;
    private javax.swing.JButton browseForParametersFileButton;
    private javax.swing.JTextField directoryTextField;
    private javax.swing.JComboBox encodingComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox lemmasCheckBox;
    private javax.swing.JPanel optionsPanel;
    private javax.swing.JTextField parametersFileTextField;
    private javax.swing.JCheckBox postagsCheckBox;
    // End of variables declaration//GEN-END:variables

}
