/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.exmaralda.exakt.exmaraldaSearch.swing;

import org.exmaralda.exakt.exmaraldaSearch.AdvancedSortDirective;
import org.exmaralda.exakt.exmaraldaSearch.AdvancedSortDirective.SORT_DIRECTION;
import org.exmaralda.exakt.exmaraldaSearch.AdvancedSortDirective.SORT_TYPE;

/**
 *
 * @author bernd
 */
public class AdvancedSortPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdvancedSortPanel
     */
    public AdvancedSortPanel(COMAKWICTable kwic) {
        initComponents();
        ColumnSelectionComboBoxModel comboBoxModel = new ColumnSelectionComboBoxModel(kwic.getWrappedModel());
        columnNameComboBox.setModel(comboBoxModel);
    }
    
    public AdvancedSortDirective getSortDirective(){
        int col = columnNameComboBox.getSelectedIndex();
        SORT_TYPE sortType = SORT_TYPE.valueOf(((String)sortTypeComboBox.getSelectedItem()).toUpperCase());
        SORT_DIRECTION sortDirection = SORT_DIRECTION.valueOf(((String)sortDirectionComboBox.getSelectedItem()).toUpperCase());
        return new AdvancedSortDirective(col, sortType, sortDirection);
    }
    
    public boolean isActive(){
        return activeCheckBox.isSelected();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        activeCheckBox = new javax.swing.JCheckBox();
        columnLabel = new javax.swing.JLabel();
        columnNameComboBox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        sortLabel = new javax.swing.JLabel();
        sortTypeComboBox = new javax.swing.JComboBox<>();
        sortDirectionComboBox = new javax.swing.JComboBox<>();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        activeCheckBox.setSelected(true);
        jPanel1.add(activeCheckBox);

        columnLabel.setText("Sort by column: ");
        jPanel1.add(columnLabel);

        columnNameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(columnNameComboBox);

        add(jPanel1);

        sortLabel.setText("Order: ");
        jPanel2.add(sortLabel);

        sortTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alphabet", "Alphabet_Reversed", "Number" }));
        jPanel2.add(sortTypeComboBox);

        sortDirectionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ascending", "descending" }));
        jPanel2.add(sortDirectionComboBox);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox activeCheckBox;
    private javax.swing.JLabel columnLabel;
    private javax.swing.JComboBox<String> columnNameComboBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> sortDirectionComboBox;
    private javax.swing.JLabel sortLabel;
    private javax.swing.JComboBox<String> sortTypeComboBox;
    // End of variables declaration//GEN-END:variables
}
