/*
 * ChangeZoomDialog.java
 *
 * Created on 15. Mai 2008, 13:37
 */

package org.exmaralda.folker.timeview;

import org.exmaralda.folker.utilities.FOLKERInternationalizer;

/**
 *
 * @author  thomas
 */
public class ChangeZoomDialog extends javax.swing.JDialog {
    
    /** Creates new form ChangeZoomDialog */
    public ChangeZoomDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        horizontalSliderPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        zoomLevelSlider = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        verticalSliderPanel = new javax.swing.JPanel();
        magnifyLevelSlider = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setText("1px \u2259");
        horizontalSliderPanel.add(jLabel1);

        zoomLevelSlider.setMajorTickSpacing(20);
        zoomLevelSlider.setMinorTickSpacing(10);
        zoomLevelSlider.setPaintLabels(true);
        zoomLevelSlider.setPaintTicks(true);
        zoomLevelSlider.setToolTipText(FOLKERInternationalizer.getString("dialog.zoom.horizontal"));
        zoomLevelSlider.setValue(0);
        zoomLevelSlider.setInverted(true);
        horizontalSliderPanel.add(zoomLevelSlider);

        jLabel2.setText(" ms");
        horizontalSliderPanel.add(jLabel2);

        getContentPane().add(horizontalSliderPanel, java.awt.BorderLayout.CENTER);

        magnifyLevelSlider.setMaximum(30);
        magnifyLevelSlider.setMinimum(7);
        magnifyLevelSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        magnifyLevelSlider.setToolTipText(FOLKERInternationalizer.getString("dialog.zoom.vertical"));
        magnifyLevelSlider.setValue(10);
        magnifyLevelSlider.setPreferredSize(new java.awt.Dimension(25, 50));
        verticalSliderPanel.add(magnifyLevelSlider);

        getContentPane().add(verticalSliderPanel, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeZoomDialog(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel horizontalSliderPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JSlider magnifyLevelSlider;
    private javax.swing.JPanel verticalSliderPanel;
    public javax.swing.JSlider zoomLevelSlider;
    // End of variables declaration//GEN-END:variables
    
}
