/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FolkerTranscriptionsWizardPanel.java
 *
 * Created on 23.03.2010, 15:17:24
 */

package org.exmaralda.exakt.wizard.folkercorpuswizard;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.util.Vector;

/**
 *
 * @author thomas
 */
public class FolkerTranscriptionsWizardPanel extends javax.swing.JPanel implements MouseListener {

    FileSelectionTableModel model;

    /** Creates new form FolkerTranscriptionsWizardPanel */
    public FolkerTranscriptionsWizardPanel() {
        initComponents();
        filesTable.addMouseListener(this);

    }

    public void setFiles(Vector<File> files){
        model = new FileSelectionTableModel(files);
        filesTable.setModel(model);
        filesTable.getColumnModel().getColumn(0).setPreferredWidth(150);
        filesTable.getColumnModel().getColumn(1).setPreferredWidth(2000);
        filesTable.getColumnModel().getColumn(0).setHeaderValue("Include");
        filesTable.getColumnModel().getColumn(1).setHeaderValue("Transcription");
        FileSelectionTableCellRenderer renderer = new FileSelectionTableCellRenderer();
        filesTable.getColumnModel().getColumn(0).setCellRenderer(renderer);
        filesTable.getColumnModel().getColumn(1).setCellRenderer(renderer);
        filesTable.setRowHeight(22);
        filesTable.setSelectionMode(filesTable.getSelectionModel().SINGLE_INTERVAL_SELECTION);

        countLabel.setText(Integer.toString(files.size()) + " of " + Integer.toString(files.size()) + " selected.");

    }

    Vector<File> getFiles() {
        return model.getSelected();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        filesTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        countLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        filesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Include", "Transcription"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(filesTable);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        countLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        countLabel.setForeground(java.awt.SystemColor.activeCaption);
        countLabel.setText("jLabel1");
        jPanel1.add(countLabel);

        add(jPanel1, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JLabel countLabel;
    private javax.swing.JTable filesTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void mouseClicked(MouseEvent e) {
        if (e.getClickCount()==2){
            int index = filesTable.getSelectedRow();
            model.toggleSelection(index);
            countLabel.setText(Integer.toString(model.countSelected()) + " of " + Integer.toString(model.getRowCount()) + " selected.");

        }
    }

    public void mousePressed(MouseEvent e) {
    }

    public void mouseReleased(MouseEvent e) {
    }

    public void mouseEntered(MouseEvent e) {
    }

    public void mouseExited(MouseEvent e) {
    }

}
