/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FolkerParametersPanel.java
 *
 * Created on 23.03.2010, 16:36:42
 */

package org.exmaralda.exakt.wizard.folkercorpuswizard;

/**
 *
 * @author thomas
 */
public class FolkerParametersPanel extends javax.swing.JPanel {

    /** Creates new form FolkerParametersPanel */
    public FolkerParametersPanel() {
        initComponents();
    }

    Object[] getParameters() {
        Object[] returnValue = new Object[3];
        returnValue[0] = new Boolean(separateRadioButton.isSelected());
        returnValue[1] = directoryTextField.getText();
        returnValue[2] = new Boolean(writeBasicCheckBox.isSelected());

        return returnValue;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        separateRadioButton = new javax.swing.JRadioButton();
        directoryTextField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        sameFolderRadioButton = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        writeBasicCheckBox = new javax.swing.JCheckBox();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Write EXMARaLDA transcriptions...");
        jPanel3.add(jLabel1);

        jPanel1.add(jPanel3);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        buttonGroup1.add(separateRadioButton);
        separateRadioButton.setSelected(true);
        separateRadioButton.setText("... to a separate directory: ");
        jPanel2.add(separateRadioButton);

        directoryTextField.setText("exmaralda");
        directoryTextField.setPreferredSize(new java.awt.Dimension(200, 20));
        directoryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directoryTextFieldActionPerformed(evt);
            }
        });
        directoryTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                directoryTextFieldFocusGained(evt);
            }
        });
        jPanel2.add(directoryTextField);

        jPanel1.add(jPanel2);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        buttonGroup1.add(sameFolderRadioButton);
        sameFolderRadioButton.setText("... to the same directory as the original file");
        jPanel4.add(sameFolderRadioButton);

        jPanel1.add(jPanel4);

        add(jPanel1);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        writeBasicCheckBox.setText("Generate Basic Transcriptions");
        jPanel5.add(writeBasicCheckBox);

        add(jPanel5);
    }// </editor-fold>//GEN-END:initComponents

    private void directoryTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_directoryTextFieldFocusGained
        this.separateRadioButton.setSelected(true);
}//GEN-LAST:event_directoryTextFieldFocusGained

    private void directoryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directoryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_directoryTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField directoryTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton sameFolderRadioButton;
    private javax.swing.JRadioButton separateRadioButton;
    private javax.swing.JCheckBox writeBasicCheckBox;
    // End of variables declaration//GEN-END:variables

}
