<?
// coma/mac updates
// name = version name
// numeric = numeric value to compare versions
// file = direct download link
// url = link to download page
// note = remark

$ver["current"]["type"]="current";
$ver["current"]["name"]="@current@";
$ver["current"]["numeric"]="@currentnumeric@";
$ver["current"]["file"]="";
$ver["current"]["url"]="http://www.exmaralda.org/downloads.html";
$ver["current"]["note"]="recommended version";

$ver["latest"]["type"]="latest";
$ver["latest"]["name"]="@latest@";
$ver["latest"]["numeric"]="@latestnumeric@";
$ver["latest"]["file"]="";
$ver["latest"]["url"]="http://www.exmaralda.org/previews2.html";
$ver["latest"]["note"]="latest version";

$included_file="coma_mac.inc";

?>
