<?
// partitur editor updates
// name = version name
// numeric = numeric value to compare versions
// file = direct download link
// url = link to download page
// note = remark


$ver["current"]["name"]="@current@";
$ver["current"]["numeric"]="@currentnumeric@";
$ver["current"]["file"]="";
$ver["current"]["url"]="http://www.exmaralda.org/downloads.html";
$ver["current"]["note"]="two different versions for ppc or intel macs";

$ver["latest"]["name"]="@latest@";
$ver["latest"]["numeric"]="@latestnumeric@";
$ver["latest"]["file"]="";
$ver["latest"]["url"]="http://www.exmaralda.org/previews2.html";
$ver["latest"]["note"]="two different versions for ppc or intel macs";

?>
