/*
 * AbstractOKCancelDialog.java
 *
 * Created on 10. Januar 2007, 17:57
 */

package org.exmaralda.exakt.search.swing;

import java.applet.Applet;
import java.awt.Dialog;
import javax.swing.KeyStroke;
import java.awt.event.KeyEvent;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JRootPane;
import javax.swing.JComponent;



/**
 *
 * @author  thomas
 */
public class AbstractOKCancelDialog extends javax.swing.JDialog {
    
    boolean ok = false;
    ActionListener actionListener;
    
    /** Creates new form AbstractOKCancelDialog */
    public AbstractOKCancelDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        actionListener = new ActionListener() {     
            public void actionPerformed(ActionEvent actionEvent) {
                ok = false;
                closeDialog();
            }
        };
        KeyStroke stroke = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);
        this.getRootPane().registerKeyboardAction(actionListener, stroke, JComponent.WHEN_IN_FOCUSED_WINDOW);
        getRootPane().setDefaultButton(okButton);        
        java.awt.Dimension dialogSize = this.getPreferredSize();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(screenSize.width/2 - dialogSize.width/2, screenSize.height/2 - dialogSize.height/2);        
    }

    public AbstractOKCancelDialog(Dialog owner, boolean modal) {
        super(owner, modal);
        initComponents();
        actionListener = new ActionListener() {
            public void actionPerformed(ActionEvent actionEvent) {
                ok = false;
                closeDialog();
            }
        };
        KeyStroke stroke = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);
        this.getRootPane().registerKeyboardAction(actionListener, stroke, JComponent.WHEN_IN_FOCUSED_WINDOW);
        getRootPane().setDefaultButton(okButton);
        java.awt.Dimension dialogSize = this.getPreferredSize();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(screenSize.width/2 - dialogSize.width/2, screenSize.height/2 - dialogSize.height/2);
    }
    
    public AbstractOKCancelDialog(java.awt.Frame parent, boolean modal, JComponent c){
        this(parent, modal);
        this.add(c);
        pack();
    }

    public AbstractOKCancelDialog(Dialog owner, boolean modal, JComponent c) {
        this(owner, modal);
        this.add(c);
        pack();
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        okCancelPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        okButton.setText("OK");
        okButton.setToolTipText("Submit changes");
        okButton.setMaximumSize(new java.awt.Dimension(65, 23));
        okButton.setMinimumSize(new java.awt.Dimension(65, 23));
        okButton.setPreferredSize(new java.awt.Dimension(65, 23));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        okCancelPanel.add(okButton);

        cancelButton.setText("Cancel");
        cancelButton.setToolTipText("Don't submit changes");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        okCancelPanel.add(cancelButton);

        getContentPane().add(okCancelPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        ok = false;
        closeDialog();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        ok = true;
        closeDialog();
    }//GEN-LAST:event_okButtonActionPerformed
    
    private void closeDialog(){
        setVisible (false);
        dispose ();                    
    }
    
    public boolean isApproved(){
        return ok;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AbstractOKCancelDialog(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel okCancelPanel;
    // End of variables declaration//GEN-END:variables
    
}
