/*
 * AnalysisSelectionPanel.java
 *
 * Created on 18. Juni 2007, 11:49
 */

package org.exmaralda.exakt.search.swing;
import org.exmaralda.exakt.search.analyses.*;


/**
 *
 * @author  thomas
 */
public class AnalysisSelectionPanel extends javax.swing.JPanel {
    
    /** Creates new form AnalysisSelectionPanel */
    public AnalysisSelectionPanel() {
        initComponents();
        categoriesPanel.setVisible(false);
    }
    
    int count = 0;
    
    public void setAnalysis(AnalysisInterface ai){
        //System.out.println("NAMMMMME: " + ai.getName());
        if (ai instanceof BinaryAnalysis){
            typeComboBox.setSelectedIndex(2);
        } else if (ai instanceof FreeAnalysis){
            typeComboBox.setSelectedIndex(0);            
        } else if (ai instanceof ClosedCategoryListAnalysis){
            typeComboBox.setSelectedIndex(1);            
            ClosedCategoryListAnalysis ccla = (ClosedCategoryListAnalysis)ai;
            String cattext = "";
            for (int pos=0; pos<ccla.getCategories().length; pos++){
                String category = ccla.getCategories()[pos];
                cattext+=category;
                if (pos<ccla.getCategories().length-1){
                    cattext+=",\n";
                }
            }
            categoriesTextArea.setText(cattext);
        }
        nameTextField.setText(ai.getName());
        nameTextField.selectAll();
    }
    
    public AnalysisInterface getAnalysis(){
        String name = nameTextField.getText();
        if (typeComboBox.getSelectedIndex()==2){
            return new BinaryAnalysis(name);
        }
        if (typeComboBox.getSelectedIndex()==1){
            String text = categoriesTextArea.getText().replace("\n", "");
            String[] cats = text.split("\\,");
            return new ClosedCategoryListAnalysis(name, cats);
        }
        return new FreeAnalysis(name);
    }

    public void init() {
        count++;
        nameTextField.setText("Analysis" + Integer.toString(count));
        nameTextField.selectAll();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        analysisPanel = new javax.swing.JPanel();
        namePanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        typePanel = new javax.swing.JPanel();
        typeLabel = new javax.swing.JLabel();
        typeComboBox = new javax.swing.JComboBox();
        parametersPanel = new javax.swing.JPanel();
        categoriesPanel = new javax.swing.JPanel();
        categoriesLabel = new javax.swing.JLabel();
        categoriesScrollPane = new javax.swing.JScrollPane();
        categoriesTextArea = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        analysisPanel.setLayout(new javax.swing.BoxLayout(analysisPanel, javax.swing.BoxLayout.Y_AXIS));

        namePanel.setLayout(new javax.swing.BoxLayout(namePanel, javax.swing.BoxLayout.LINE_AXIS));

        nameLabel.setText("Analysis name: ");
        nameLabel.setMaximumSize(new java.awt.Dimension(110, 14));
        nameLabel.setMinimumSize(new java.awt.Dimension(110, 14));
        nameLabel.setPreferredSize(new java.awt.Dimension(110, 14));
        namePanel.add(nameLabel);

        nameTextField.setMaximumSize(new java.awt.Dimension(700, 19));
        nameTextField.setMinimumSize(new java.awt.Dimension(50, 19));
        nameTextField.setPreferredSize(new java.awt.Dimension(200, 19));
        namePanel.add(nameTextField);

        analysisPanel.add(namePanel);

        typePanel.setLayout(new javax.swing.BoxLayout(typePanel, javax.swing.BoxLayout.LINE_AXIS));

        typeLabel.setText("Analysis type: ");
        typeLabel.setMaximumSize(new java.awt.Dimension(110, 14));
        typeLabel.setMinimumSize(new java.awt.Dimension(110, 14));
        typeLabel.setPreferredSize(new java.awt.Dimension(110, 14));
        typePanel.add(typeLabel);

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Free", "Closed category list", "Binary" }));
        typeComboBox.setMaximumSize(new java.awt.Dimension(700, 22));
        typeComboBox.setMinimumSize(new java.awt.Dimension(50, 22));
        typeComboBox.setPreferredSize(new java.awt.Dimension(200, 22));
        typeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeComboBoxActionPerformed(evt);
            }
        });
        typePanel.add(typeComboBox);

        analysisPanel.add(typePanel);

        add(analysisPanel, java.awt.BorderLayout.NORTH);

        parametersPanel.setLayout(new javax.swing.BoxLayout(parametersPanel, javax.swing.BoxLayout.LINE_AXIS));

        categoriesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Parameters"));
        categoriesPanel.setLayout(new javax.swing.BoxLayout(categoriesPanel, javax.swing.BoxLayout.LINE_AXIS));

        categoriesLabel.setText("Categories: ");
        categoriesLabel.setToolTipText("Enter categories separated by comma, use <ENTER> if you like");
        categoriesPanel.add(categoriesLabel);

        categoriesTextArea.setColumns(20);
        categoriesTextArea.setFont(new java.awt.Font("Courier", 0, 12)); // NOI18N
        categoriesTextArea.setRows(10);
        categoriesTextArea.setText("Tuwort,\nWiewort,\nNamenwort");
        categoriesScrollPane.setViewportView(categoriesTextArea);

        categoriesPanel.add(categoriesScrollPane);

        parametersPanel.add(categoriesPanel);

        add(parametersPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void typeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeComboBoxActionPerformed
        categoriesPanel.setVisible(typeComboBox.getSelectedIndex()==1);
        ((javax.swing.JDialog)getTopLevelAncestor()).pack();
    }//GEN-LAST:event_typeComboBoxActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel analysisPanel;
    private javax.swing.JLabel categoriesLabel;
    private javax.swing.JPanel categoriesPanel;
    private javax.swing.JScrollPane categoriesScrollPane;
    private javax.swing.JTextArea categoriesTextArea;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel namePanel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JPanel parametersPanel;
    private javax.swing.JComboBox typeComboBox;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JPanel typePanel;
    // End of variables declaration//GEN-END:variables
    
   
    
}
