/*
 * FilterTargetSelectionDialog.java
 *
 * Created on 2. Februar 2007, 12:49
 */

package org.exmaralda.exakt.search.swing;

/**
 *
 * @author  thomas
 */
public class FilterTargetSelectionDialog extends AbstractOKCancelDialog {
    
    public static final int LEFT_CONTEXT = 0;
    public static final int MATCH_TEXT = 1;
    public static final int RIGHT_CONTEXT = 2;
    
    /** Creates new form FilterTargetSelectionDialog */
    public FilterTargetSelectionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        buttonGroup = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        radioButtonPanel = new javax.swing.JPanel();
        leftContextButton = new javax.swing.JRadioButton();
        matchTextButton = new javax.swing.JRadioButton();
        rightContextButton = new javax.swing.JRadioButton();
        invertPanel = new javax.swing.JPanel();
        invertCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Filter specification");
        mainPanel.setLayout(new java.awt.GridLayout(2, 1));

        buttonGroup.add(leftContextButton);
        leftContextButton.setText("Left context");
        leftContextButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        leftContextButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        radioButtonPanel.add(leftContextButton);

        buttonGroup.add(matchTextButton);
        matchTextButton.setSelected(true);
        matchTextButton.setText("Match text");
        matchTextButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        matchTextButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        radioButtonPanel.add(matchTextButton);

        buttonGroup.add(rightContextButton);
        rightContextButton.setText("Right context");
        rightContextButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        rightContextButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        radioButtonPanel.add(rightContextButton);

        mainPanel.add(radioButtonPanel);

        invertCheckBox.setText("Inverse filter");
        invertCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        invertCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));
        invertPanel.add(invertCheckBox);

        mainPanel.add(invertPanel);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FilterTargetSelectionDialog(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    public int getSelection(){
        if (leftContextButton.isSelected()) return LEFT_CONTEXT;
        if (rightContextButton.isSelected()) return RIGHT_CONTEXT;
        return MATCH_TEXT;
    }
    
    public boolean getInversion(){
        return invertCheckBox.isSelected();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JCheckBox invertCheckBox;
    private javax.swing.JPanel invertPanel;
    private javax.swing.JRadioButton leftContextButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JRadioButton matchTextButton;
    private javax.swing.JPanel radioButtonPanel;
    private javax.swing.JRadioButton rightContextButton;
    // End of variables declaration//GEN-END:variables
    
}
