/*
 * InputHelperDialog.java
 *
 * Created on 19. Januar 2007, 15:26
 */

package org.exmaralda.exakt.search.swing;

import com.sun.media.renderer.video.Java2DRenderer;
import javax.swing.KeyStroke;
import java.awt.event.KeyEvent;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JRootPane;
import javax.swing.JComponent;


/**
 *
 * @author  thomas
 */
public class InputHelperDialog extends javax.swing.JDialog {
    
    public InputHelperPanel inputHelperPanel;
    //COMAKWICSearchPanel parent;
    javax.swing.JPanel parent;
    
    public boolean changed = false;
    
    /** Creates new form InputHelperDialog */
    public InputHelperDialog(javax.swing.JPanel p) {
        super((java.awt.Frame)null, false);
        parent = p;
        initComponents();        
        setInputHelperPanel(new InputHelperPanel());
        getContentPane().add(getInputHelperPanel(), java.awt.BorderLayout.CENTER);
        ActionListener actionListener = new ActionListener() {     
            public void actionPerformed(ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        };
        KeyStroke stroke = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);
        this.getRootPane().registerKeyboardAction(actionListener, stroke, JComponent.WHEN_IN_FOCUSED_WINDOW);
        getInputHelperPanel().okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        getInputHelperPanel().cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getInputHelperPanel().textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        pack();
    }
    
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
        changed = true;
        setVisible(false);
    }                                        
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
        changed = false;
        setVisible(false);        
    }                                        
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setTitle("Input Helper");
        setBackground(new java.awt.Color(255, 255, 255));
        setModal(true);
        setUndecorated(true);
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new InputHelperDialog(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public InputHelperPanel getInputHelperPanel() {
        return inputHelperPanel;
    }

    public void setInputHelperPanel(InputHelperPanel inputHelperPanel) {
        this.inputHelperPanel = inputHelperPanel;
    }
    
}
