/*
 * SquirrelMainFrame.java
 *
 * Created on 11. Juni 2004, 12:11
 */

package org.exmaralda.zecke;

import org.exmaralda.partitureditor.partiture.PartitureTableWithActions;
import org.exmaralda.partitureditor.jexmaralda.convert.StylesheetFactory;
import org.exmaralda.partitureditor.jexmaralda.TierFormatTable;
import org.exmaralda.partitureditor.jexmaralda.BasicTranscription;
import org.exmaralda.partitureditor.partiture.*;
import javax.swing.tree.*;
import org.exmaralda.partitureditor.jexmaralda.*;
import org.exmaralda.partitureditor.jexmaralda.*;

/**
 *
 * @author  thomas
 */
public class SquirrelMainFrame extends javax.swing.JFrame {
    
    PartitureTableWithActions partitur;
    _TranscriptionSearchInternalFrame searchFrame1 = new _TranscriptionSearchInternalFrame();
    _TranscriptionSearchInternalFrame searchFrame2 = new _TranscriptionSearchInternalFrame();
    _TranscriptionSearchInternalFrame searchFrame3 = new _TranscriptionSearchInternalFrame();
    
    /** Creates new form SquirrelMainFrame */
    public SquirrelMainFrame() {
        StartupSplashScreen splashScreen = new StartupSplashScreen(this);
        initComponents();
        partitur = new PartitureTableWithActions(null);
        partitur.setLocked(true);
        partitur.scaleConstant = -1;
        partitur.setCellBorderWidth(0);
        partiturPanel.add(partitur);
        try {
            BasicTranscription bt = new BasicTranscription("d:\\aaa_beispiele\\Helge_neu\\Helge_Basic.xml");
            StylesheetFactory sf = new StylesheetFactory();
            String formatString = 
                sf.applyExternalStylesheetToString("d:\\exmaralda_stylesheets\\HIAT_FormatTable4BasicTranscription_Squirrel.xsl", bt.toXML());
            TierFormatTable tft = new TierFormatTable();
            tft.TierFormatTableFromString(formatString);
            partitur.getModel().setTranscriptionAndTierFormatTable(bt, tft);
        } catch (Exception e){
            e.printStackTrace();
        }
        //partitur.getModel().resetTranscription();
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("Corpus");
        corpusTree.setModel(new CorpusTreeModel(root));
        corpusTree.setCellRenderer(new CorpusTreeCellRenderer());
        desktopPane.add(searchFrame1);
        desktopPane.add(searchFrame2);
        desktopPane.add(searchFrame3);
        searchFrame1.show();
        searchFrame2.show();
        searchFrame3.show();
        pack();
        mainSplitPane.setDividerLocation(0.75);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        mainSplitPane = new javax.swing.JSplitPane();
        corpusSearchSplitPane = new javax.swing.JSplitPane();
        corpusTreeScrollPane = new javax.swing.JScrollPane();
        corpusTree = new javax.swing.JTree();
        desktopPane = new javax.swing.JDesktopPane();
        partiturPanel = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        showButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setTitle("EXMARaLDA SQUIRREL");
        setIconImage(getIconImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        mainSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        mainSplitPane.setOneTouchExpandable(true);
        corpusSearchSplitPane.setOneTouchExpandable(true);
        corpusTreeScrollPane.setViewportView(corpusTree);

        corpusSearchSplitPane.setLeftComponent(corpusTreeScrollPane);

        corpusSearchSplitPane.setRightComponent(desktopPane);

        mainSplitPane.setLeftComponent(corpusSearchSplitPane);

        partiturPanel.setLayout(new javax.swing.BoxLayout(partiturPanel, javax.swing.BoxLayout.X_AXIS));

        buttonPanel.setLayout(new javax.swing.BoxLayout(buttonPanel, javax.swing.BoxLayout.Y_AXIS));

        showButton.setText("Show");
        showButton.setMaximumSize(new java.awt.Dimension(70, 26));
        showButton.setMinimumSize(new java.awt.Dimension(70, 26));
        showButton.setPreferredSize(new java.awt.Dimension(70, 26));
        buttonPanel.add(showButton);

        clearButton.setText("Clear");
        clearButton.setMaximumSize(new java.awt.Dimension(70, 26));
        clearButton.setMinimumSize(new java.awt.Dimension(70, 26));
        clearButton.setPreferredSize(new java.awt.Dimension(70, 26));
        buttonPanel.add(clearButton);

        partiturPanel.add(buttonPanel);

        mainSplitPane.setRightComponent(partiturPanel);

        getContentPane().add(mainSplitPane, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("View");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Search");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Window");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }//GEN-END:initComponents
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try{
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        }           
        catch (Exception e) {
                e.printStackTrace();        
        }
        new SquirrelMainFrame().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton clearButton;
    private javax.swing.JSplitPane corpusSearchSplitPane;
    private javax.swing.JTree corpusTree;
    private javax.swing.JScrollPane corpusTreeScrollPane;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSplitPane mainSplitPane;
    private javax.swing.JPanel partiturPanel;
    private javax.swing.JButton showButton;
    // End of variables declaration//GEN-END:variables
    
}
