/*
 * EditMetaInformationDialog.java
 *
 * Created on 3. August 2001, 13:11
 */

package org.exmaralda.partitureditor.jexmaraldaswing;

import org.exmaralda.common.helpers.Internationalizer;
import org.exmaralda.partitureditor.jexmaraldaswing.fileDialogs.*;
import java.io.*;
/**
 *
 * @author  Thomas
 * @version 
 */
public class EditMetaInformationDialog extends JEscapeDialog {

    private org.exmaralda.partitureditor.jexmaralda.MetaInformation metaInformation;
    private org.exmaralda.partitureditor.udInformationTable.UDInformationPanel tablePanel;
    private javax.swing.JButton templateButton;
    private String currentFilename;
    //private UDInformationTableModel tableModel;
    
    
    /** Creates new form EditMetaInformationDialog */
    public EditMetaInformationDialog(java.awt.Frame parent,boolean modal, org.exmaralda.partitureditor.jexmaralda.MetaInformation mi) {
        super (parent, modal);
        templateButton = new javax.swing.JButton();
        templateButton.setPreferredSize (new java.awt.Dimension(170, 27));
        templateButton.setMaximumSize (new java.awt.Dimension(170, 27));
        templateButton.setMinimumSize (new java.awt.Dimension(150, 27));
        templateButton.setText ("Template...");
        templateButton.addActionListener (new java.awt.event.ActionListener () {
            public void actionPerformed (java.awt.event.ActionEvent evt) {
                templateButtonActionPerformed (evt);
            }
        }
        );                
        change = false;
        metaInformation = mi.makeCopy();
        //tableModel = new UDInformationTableModel(metaInformation.getUDMetaInformation());
        initComponents ();
                
        updateReferencedFiles();
        
        this.getRootPane().setDefaultButton(okButton);
        tablePanel = new org.exmaralda.partitureditor.udInformationTable.UDInformationPanel();
        tablePanel.setUDInformation(metaInformation.getUDMetaInformation());
        tablePanel.getButtonPanel().add(templateButton);        
        jPanel17.add(tablePanel);
        pack ();
        Internationalizer.internationalizeDialogToolTips(this);


    }
    
    private void updateReferencedFiles(){
        String text = "";
        if (metaInformation.getReferencedFile().length()==0){
            text = "--- no file ---";
        } else {
            text = new File(metaInformation.getReferencedFile()).getName();
            if (metaInformation.getReferencedFiles().size()>1){
                text += " (+ " + Integer.toString(metaInformation.getReferencedFiles().size()-1) + " more)";
            }
        }
        referencedFilesLabel.setText(text);        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        projectNamePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        projectNameTextField = new javax.swing.JTextField();
        projectNameTextField.setText(metaInformation.getProjectName());
        transcriptionNamePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        transcriptionNameTextField = new javax.swing.JTextField();
        transcriptionNameTextField.setText(metaInformation.getTranscriptionName());
        transcriptionConventionPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        transcriptionConventionTextField = new javax.swing.JTextField();
        transcriptionConventionTextField.setText(metaInformation.getTranscriptionConvention());
        referencedFilePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        referencedFilesLabel = new javax.swing.JLabel();
        editReferencedFilesButton = new javax.swing.JButton();
        editReferencedFilesButton.setMnemonic('B');
        jPanel3 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        commentScrollPane = new javax.swing.JScrollPane();
        commentEditorPane = new javax.swing.JTextArea();
        jPanel14 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        okButton.setMnemonic('O');
        cancelButton = new javax.swing.JButton();
        cancelButton.setMnemonic('C');

        setTitle("Edit meta information");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        mainPanel.setLayout(new javax.swing.BoxLayout(mainPanel, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Fixed attributes"));
        jPanel1.setMaximumSize(new java.awt.Dimension(600, 135));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        projectNamePanel.setPreferredSize(new java.awt.Dimension(430, 30));
        projectNamePanel.setLayout(new javax.swing.BoxLayout(projectNamePanel, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Project name: ");
        jLabel1.setMaximumSize(new java.awt.Dimension(180, 16));
        jLabel1.setMinimumSize(new java.awt.Dimension(140, 16));
        jLabel1.setPreferredSize(new java.awt.Dimension(180, 16));
        projectNamePanel.add(jLabel1);

        projectNameTextField.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        projectNameTextField.setMinimumSize(new java.awt.Dimension(150, 20));
        projectNameTextField.setPreferredSize(new java.awt.Dimension(250, 30));
        projectNamePanel.add(projectNameTextField);

        jPanel1.add(projectNamePanel);

        transcriptionNamePanel.setMaximumSize(new java.awt.Dimension(600, 30));
        transcriptionNamePanel.setPreferredSize(new java.awt.Dimension(470, 30));
        transcriptionNamePanel.setLayout(new javax.swing.BoxLayout(transcriptionNamePanel, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("Transcription name: ");
        jLabel2.setMaximumSize(new java.awt.Dimension(180, 16));
        jLabel2.setMinimumSize(new java.awt.Dimension(140, 16));
        jLabel2.setPreferredSize(new java.awt.Dimension(180, 16));
        transcriptionNamePanel.add(jLabel2);

        transcriptionNameTextField.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        transcriptionNameTextField.setMinimumSize(new java.awt.Dimension(150, 20));
        transcriptionNameTextField.setPreferredSize(new java.awt.Dimension(250, 30));
        transcriptionNamePanel.add(transcriptionNameTextField);

        jPanel1.add(transcriptionNamePanel);

        transcriptionConventionPanel.setMaximumSize(new java.awt.Dimension(600, 30));
        transcriptionConventionPanel.setPreferredSize(new java.awt.Dimension(470, 35));
        transcriptionConventionPanel.setLayout(new javax.swing.BoxLayout(transcriptionConventionPanel, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setText("Transcription convention: ");
        jLabel3.setMaximumSize(new java.awt.Dimension(180, 16));
        jLabel3.setMinimumSize(new java.awt.Dimension(140, 16));
        jLabel3.setPreferredSize(new java.awt.Dimension(180, 16));
        transcriptionConventionPanel.add(jLabel3);

        transcriptionConventionTextField.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        transcriptionConventionTextField.setMinimumSize(new java.awt.Dimension(150, 20));
        transcriptionConventionTextField.setPreferredSize(new java.awt.Dimension(250, 30));
        transcriptionConventionPanel.add(transcriptionConventionTextField);

        jPanel1.add(transcriptionConventionPanel);

        referencedFilePanel.setMaximumSize(new java.awt.Dimension(600, 30));
        referencedFilePanel.setPreferredSize(new java.awt.Dimension(470, 27));
        referencedFilePanel.setLayout(new javax.swing.BoxLayout(referencedFilePanel, javax.swing.BoxLayout.LINE_AXIS));

        jLabel4.setText("Referenced media file(s)");
        jLabel4.setMaximumSize(new java.awt.Dimension(180, 16));
        jLabel4.setMinimumSize(new java.awt.Dimension(140, 16));
        jLabel4.setPreferredSize(new java.awt.Dimension(180, 16));
        referencedFilePanel.add(jLabel4);

        referencedFilesLabel.setForeground(java.awt.SystemColor.desktop);
        referencedFilesLabel.setText("jLabel5");
        referencedFilesLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        referencedFilesLabel.setMaximumSize(new java.awt.Dimension(400, 20));
        referencedFilesLabel.setMinimumSize(new java.awt.Dimension(100, 20));
        referencedFilesLabel.setPreferredSize(new java.awt.Dimension(150, 20));
        referencedFilePanel.add(referencedFilesLabel);

        editReferencedFilesButton.setText("Edit...");
        editReferencedFilesButton.setMaximumSize(new java.awt.Dimension(90, 27));
        editReferencedFilesButton.setMinimumSize(new java.awt.Dimension(90, 27));
        editReferencedFilesButton.setPreferredSize(new java.awt.Dimension(100, 27));
        editReferencedFilesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editReferencedFilesButtonActionPerformed(evt);
            }
        });
        referencedFilePanel.add(editReferencedFilesButton);

        jPanel1.add(referencedFilePanel);

        mainPanel.add(jPanel1);

        jPanel3.setMaximumSize(new java.awt.Dimension(600, 600));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 425));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jPanel17.setMaximumSize(new java.awt.Dimension(600, 400));
        jPanel17.setMinimumSize(new java.awt.Dimension(10, 20));
        jPanel17.setPreferredSize(new java.awt.Dimension(200, 225));
        jPanel17.setLayout(new javax.swing.BoxLayout(jPanel17, javax.swing.BoxLayout.LINE_AXIS));
        jPanel3.add(jPanel17);

        jPanel2.setMaximumSize(new java.awt.Dimension(600, 200));
        jPanel2.setMinimumSize(new java.awt.Dimension(200, 100));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        commentScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Comment"));
        commentScrollPane.setMaximumSize(new java.awt.Dimension(600, 200));
        commentScrollPane.setMinimumSize(new java.awt.Dimension(200, 200));
        commentScrollPane.setPreferredSize(new java.awt.Dimension(200, 200));

        commentEditorPane.setLineWrap(true);
        commentEditorPane.setWrapStyleWord(true);
        commentEditorPane.setMaximumSize(new java.awt.Dimension(200, 1600));
        commentEditorPane.setMinimumSize(new java.awt.Dimension(200, 100));
        commentEditorPane.setPreferredSize(new java.awt.Dimension(200, 1600));
        commentEditorPane.setText(metaInformation.getComment());
        commentScrollPane.setViewportView(commentEditorPane);

        jPanel2.add(commentScrollPane);

        jPanel3.add(jPanel2);

        mainPanel.add(jPanel3);

        jPanel14.setLayout(new javax.swing.BoxLayout(jPanel14, javax.swing.BoxLayout.LINE_AXIS));

        okButton.setText("OK");
        okButton.setMaximumSize(new java.awt.Dimension(110, 27));
        okButton.setMinimumSize(new java.awt.Dimension(83, 27));
        okButton.setPreferredSize(new java.awt.Dimension(110, 27));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        jPanel14.add(okButton);

        cancelButton.setText("Cancel");
        cancelButton.setMaximumSize(new java.awt.Dimension(110, 27));
        cancelButton.setMinimumSize(new java.awt.Dimension(83, 27));
        cancelButton.setPreferredSize(new java.awt.Dimension(110, 27));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel14.add(cancelButton);

        mainPanel.add(jPanel14);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

  private void cancelButtonActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
// Add your handling code here:
    setVisible (false);
    dispose ();    
  }//GEN-LAST:event_cancelButtonActionPerformed

  private void okButtonActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
// Add your handling code here:
    this.tablePanel.table.commitCellEdit();
    change=true;
    setVisible (false);
    dispose ();    
  }//GEN-LAST:event_okButtonActionPerformed

  private void udInformationTableMouseClicked (java.awt.event.MouseEvent evt) {//GEN-FIRST:event_udInformationTableMouseClicked
// Add your handling code here:
  }//GEN-LAST:event_udInformationTableMouseClicked

  private void removeButtonActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
// Add your handling code here:
  }//GEN-LAST:event_removeButtonActionPerformed

  private void addButtonActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
  }//GEN-LAST:event_addButtonActionPerformed

  private void editReferencedFilesButtonActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editReferencedFilesButtonActionPerformed
    EditReferencedFilesDialog dialog = new EditReferencedFilesDialog(null, true, metaInformation.getReferencedFiles());
    dialog.setLocationRelativeTo(this);
    dialog.setVisible(true);
    
    metaInformation.setReferencedFiles(dialog.getReferencedFiles());
    this.updateReferencedFiles();
    
      // Add your handling code here:
    // TODO!
      /*javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
    chooser.setFileSelectionMode(javax.swing.JFileChooser.FILES_ONLY);
    chooser.setFileFilter(new org.exmaralda.partitureditor.jexmaraldaswing.fileFilters.MediaFileFilter());
    chooser.setCurrentDirectory(new java.io.File(getCurrentFilename()));
    int returnval = chooser.showOpenDialog(this);
    if(returnval == javax.swing.JFileChooser.APPROVE_OPTION) {
        String filename = chooser.getSelectedFile().getPath();
        referencedFileTextField.setText(filename);
    }*/
}//GEN-LAST:event_editReferencedFilesButtonActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible (false);
        dispose ();
    }//GEN-LAST:event_closeDialog

    /**
    * @param args the command line arguments
    */
    public static void main (String args[]) {
//        new EditMetaInformationDialog (new javax.swing.JFrame (), true).show ();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextArea commentEditorPane;
    private javax.swing.JScrollPane commentScrollPane;
    private javax.swing.JButton editReferencedFilesButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel projectNamePanel;
    private javax.swing.JTextField projectNameTextField;
    private javax.swing.JPanel referencedFilePanel;
    private javax.swing.JLabel referencedFilesLabel;
    private javax.swing.JPanel transcriptionConventionPanel;
    private javax.swing.JTextField transcriptionConventionTextField;
    private javax.swing.JPanel transcriptionNamePanel;
    private javax.swing.JTextField transcriptionNameTextField;
    // End of variables declaration//GEN-END:variables

    public org.exmaralda.partitureditor.jexmaralda.MetaInformation getMetaInformation(){
        return metaInformation;
    }
    
    public boolean editMetaInformation(){
        java.awt.Dimension dialogSize = this.getPreferredSize();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(screenSize.width/2 - dialogSize.width/2, screenSize.height/2 - dialogSize.height/2);
        this.setVisible(true);
        
        if (!change){return false;}
        metaInformation.setProjectName(projectNameTextField.getText());
        metaInformation.setTranscriptionName(transcriptionNameTextField.getText());
        metaInformation.setTranscriptionConvention(transcriptionConventionTextField.getText());
        // TODO!
        //metaInformation.setReferencedFile(referencedFileTextField.getText());
        metaInformation.setComment(commentEditorPane.getText());
        metaInformation.setUDMetaInformation(tablePanel.getUDInformation());
        /*javax.swing.table.DefaultTableModel tm = ((javax.swing.table.DefaultTableModel)udInformationTable.getModel());
        for (int row=0; row<tm.getRowCount(); row++){
            metaInformation.getUDMetaInformation().setAttribute((String)tm.getValueAt(row,0),(String)tm.getValueAt(row,1));
        } */       
        return true;
    }
    
  private void templateButtonActionPerformed (java.awt.event.ActionEvent evt) {
    // Add your handling code here:
        OpenBasicTranscriptionDialog dialog = new OpenBasicTranscriptionDialog();
        if (dialog.openTranscription(this)){
            org.exmaralda.partitureditor.jexmaralda.BasicTranscription templateTranscription = dialog.getTranscription();
            metaInformation.makeUDAttributesFromTemplate(templateTranscription.getHead().getMetaInformation());
            tablePanel.setUDInformation(metaInformation.getUDMetaInformation());
        }      
        
  }

    public String getCurrentFilename() {
        return currentFilename;
    }

    public void setCurrentFilename(String currentFilename) {
        this.currentFilename = currentFilename;
    }

    
}