/*
 * EditTierFormatPanel.java
 *
 * Created on 9. August 2001, 16:26
 */

package org.exmaralda.partitureditor.jexmaraldaswing;

import org.exmaralda.partitureditor.jexmaralda.*;

/**
 *
 * @author  Thomas
 * @version 
 */
public class EditTierFormatPanel extends javax.swing.JPanel {

    private static String[] STYLES = {"Plain", "Bold", "Italic"};
    private static String[] SIZES = {"1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","20","24","32","48"};
    private static String[] ALIGNMENT = {"Left", "Center", "Right"};
    private static String[] BORDER_STYLES = {"Solid","Dotted","Dashed"};
    private String[] FONTS;
    private TierFormat tierFormat;

    private String testString = "Some special symbols: \u2022 / \u203F / \u02D9";

    /** Creates new form EditTierFormatPanel */
    public EditTierFormatPanel(TierFormat tf) {
        tierFormat = tf.makeCopy();
        java.awt.GraphicsEnvironment ge = java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment();
        FONTS = ge.getAvailableFontFamilyNames();
        initComponents ();
        setSelections();
        formatTestField();
    }

    public TierFormat getTierFormat(){
        try{
            String txt = fixedHeightTextField.getText();
            short height = Short.parseShort(txt);
            if (height<0) throw new NumberFormatException();
            tierFormat.setProperty("fixed-row-height",Short.toString(height));
        } catch(NumberFormatException nfe){}
        return tierFormat;
    }
    
    public void setTierFormat(TierFormat tf){
        tierFormat = tf.makeCopy();
        setSelections();
        formatTestField();
    }                   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        heightCalculationButtonGroup = new javax.swing.ButtonGroup();
        fontPropertiesPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fontComboBox = new javax.swing.JComboBox(FONTS);
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        leftCheckBox = new javax.swing.JCheckBox();
        rightCheckBox = new javax.swing.JCheckBox();
        topCheckBox = new javax.swing.JCheckBox();
        bottomCheckBox = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        styleComboBox = new javax.swing.JComboBox(STYLES);
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        borderColorButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        sizeComboBox = new javax.swing.JComboBox(SIZES);
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        borderStyleComboBox = new javax.swing.JComboBox(BORDER_STYLES);
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        textColorButton = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        generousRadioButton = new javax.swing.JRadioButton();
        miserlyRadioButton = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        bgColorButton = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel101 = new javax.swing.JLabel();
        fixedRadioButton = new javax.swing.JRadioButton();
        fixedHeightTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        alignmentComboBox = new javax.swing.JComboBox(ALIGNMENT);
        jPanel15 = new javax.swing.JPanel();
        testPanel = new javax.swing.JPanel();
        testTextField = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        fontPropertiesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Formatting properties"));
        fontPropertiesPanel.setLayout(new java.awt.GridLayout(7, 2, 5, 0));

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Font:");
        jLabel1.setMaximumSize(new java.awt.Dimension(100, 16));
        jLabel1.setMinimumSize(new java.awt.Dimension(100, 16));
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel3.add(jLabel1);

        fontComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fontComboBoxActionPerformed(evt);
            }
        });
        jPanel3.add(fontComboBox);

        fontPropertiesPanel.add(jPanel3);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jLabel7.setText("Border sides:");
        jLabel7.setMaximumSize(new java.awt.Dimension(100, 16));
        jLabel7.setMinimumSize(new java.awt.Dimension(100, 16));
        jLabel7.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel2.add(jLabel7);

        leftCheckBox.setText("Left");
        leftCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftCheckBoxActionPerformed(evt);
            }
        });
        jPanel2.add(leftCheckBox);

        rightCheckBox.setText("Right");
        rightCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightCheckBoxActionPerformed(evt);
            }
        });
        jPanel2.add(rightCheckBox);

        topCheckBox.setText("Top");
        topCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topCheckBoxActionPerformed(evt);
            }
        });
        jPanel2.add(topCheckBox);

        bottomCheckBox.setText("Bottom");
        bottomCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottomCheckBoxActionPerformed(evt);
            }
        });
        jPanel2.add(bottomCheckBox);

        fontPropertiesPanel.add(jPanel2);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("Font style:");
        jLabel2.setMaximumSize(new java.awt.Dimension(100, 16));
        jLabel2.setMinimumSize(new java.awt.Dimension(100, 16));
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel4.add(jLabel2);

        styleComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                styleComboBoxActionPerformed(evt);
            }
        });
        jPanel4.add(styleComboBox);

        fontPropertiesPanel.add(jPanel4);

        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.LINE_AXIS));

        jLabel8.setText("Border color:");
        jLabel8.setMaximumSize(new java.awt.Dimension(100, 16));
        jLabel8.setMinimumSize(new java.awt.Dimension(100, 16));
        jLabel8.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel11.add(jLabel8);

        borderColorButton.setBackground(java.awt.Color.red);
        borderColorButton.setText("Edit...");
        borderColorButton.setMaximumSize(new java.awt.Dimension(100, 20));
        borderColorButton.setMinimumSize(new java.awt.Dimension(100, 20));
        borderColorButton.setPreferredSize(new java.awt.Dimension(100, 20));
        borderColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borderColorButtonActionPerformed(evt);
            }
        });
        jPanel11.add(borderColorButton);

        fontPropertiesPanel.add(jPanel11);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setText("Font size:");
        jLabel3.setMaximumSize(new java.awt.Dimension(100, 16));
        jLabel3.setMinimumSize(new java.awt.Dimension(100, 16));
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel5.add(jLabel3);

        sizeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeComboBoxActionPerformed(evt);
            }
        });
        jPanel5.add(sizeComboBox);

        fontPropertiesPanel.add(jPanel5);

        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.LINE_AXIS));

        jLabel9.setText("Border style:");
        jLabel9.setMaximumSize(new java.awt.Dimension(100, 16));
        jLabel9.setMinimumSize(new java.awt.Dimension(100, 16));
        jLabel9.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel12.add(jLabel9);

        borderStyleComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borderStyleComboBoxActionPerformed(evt);
            }
        });
        jPanel12.add(borderStyleComboBox);

        fontPropertiesPanel.add(jPanel12);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));
        fontPropertiesPanel.add(jPanel6);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
        fontPropertiesPanel.add(jPanel1);

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jLabel4.setText("Text color:");
        jLabel4.setMaximumSize(new java.awt.Dimension(100, 16));
        jLabel4.setMinimumSize(new java.awt.Dimension(100, 16));
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel7.add(jLabel4);

        textColorButton.setBackground(java.awt.Color.red);
        textColorButton.setText("Edit...");
        textColorButton.setMaximumSize(new java.awt.Dimension(100, 20));
        textColorButton.setMinimumSize(new java.awt.Dimension(100, 20));
        textColorButton.setPreferredSize(new java.awt.Dimension(100, 20));
        textColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textColorButtonActionPerformed(evt);
            }
        });
        jPanel7.add(textColorButton);

        fontPropertiesPanel.add(jPanel7);

        jPanel16.setLayout(new javax.swing.BoxLayout(jPanel16, javax.swing.BoxLayout.LINE_AXIS));

        jLabel10.setText("Height calculation:");
        jLabel10.setMaximumSize(new java.awt.Dimension(100, 16));
        jLabel10.setMinimumSize(new java.awt.Dimension(100, 16));
        jLabel10.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel16.add(jLabel10);

        heightCalculationButtonGroup.add(generousRadioButton);
        generousRadioButton.setSelected(true);
        generousRadioButton.setText("Generous");
        generousRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generousRadioButtonActionPerformed(evt);
            }
        });
        jPanel16.add(generousRadioButton);

        heightCalculationButtonGroup.add(miserlyRadioButton);
        miserlyRadioButton.setText("Miserly");
        miserlyRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miserlyRadioButtonActionPerformed(evt);
            }
        });
        jPanel16.add(miserlyRadioButton);

        fontPropertiesPanel.add(jPanel16);

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));

        jLabel5.setText("Background color:");
        jLabel5.setMaximumSize(new java.awt.Dimension(100, 16));
        jLabel5.setMinimumSize(new java.awt.Dimension(100, 16));
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel8.add(jLabel5);

        bgColorButton.setBackground(java.awt.Color.red);
        bgColorButton.setText("Edit...");
        bgColorButton.setMaximumSize(new java.awt.Dimension(100, 20));
        bgColorButton.setMinimumSize(new java.awt.Dimension(100, 20));
        bgColorButton.setPreferredSize(new java.awt.Dimension(100, 20));
        bgColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgColorButtonActionPerformed(evt);
            }
        });
        jPanel8.add(bgColorButton);

        fontPropertiesPanel.add(jPanel8);

        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.LINE_AXIS));

        jLabel101.setMaximumSize(new java.awt.Dimension(100, 16));
        jLabel101.setMinimumSize(new java.awt.Dimension(100, 16));
        jLabel101.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel9.add(jLabel101);

        heightCalculationButtonGroup.add(fixedRadioButton);
        fixedRadioButton.setText("Fixed: ");
        fixedRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixedRadioButtonActionPerformed(evt);
            }
        });
        jPanel9.add(fixedRadioButton);

        fixedHeightTextField.setEditable(false);
        fixedHeightTextField.setMaximumSize(new java.awt.Dimension(30, 20));
        fixedHeightTextField.setPreferredSize(new java.awt.Dimension(30, 20));
        fixedHeightTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixedHeightTextFieldActionPerformed(evt);
            }
        });
        jPanel9.add(fixedHeightTextField);

        jLabel11.setText("Pixels");
        jPanel9.add(jLabel11);

        fontPropertiesPanel.add(jPanel9);

        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.LINE_AXIS));

        jLabel6.setText("Alignment:");
        jLabel6.setMaximumSize(new java.awt.Dimension(100, 16));
        jLabel6.setMinimumSize(new java.awt.Dimension(100, 16));
        jLabel6.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel10.add(jLabel6);

        alignmentComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alignmentComboBoxActionPerformed(evt);
            }
        });
        jPanel10.add(alignmentComboBox);

        fontPropertiesPanel.add(jPanel10);
        fontPropertiesPanel.add(jPanel15);

        add(fontPropertiesPanel, java.awt.BorderLayout.CENTER);

        testPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Test area"));
        testPanel.setLayout(new javax.swing.BoxLayout(testPanel, javax.swing.BoxLayout.LINE_AXIS));

        testTextField.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        testTextField.setText(testString);
        testTextField.setMaximumSize(new java.awt.Dimension(2147483647, 100));
        testTextField.setMinimumSize(new java.awt.Dimension(4, 60));
        testTextField.setPreferredSize(new java.awt.Dimension(101, 100));
        testTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testTextFieldActionPerformed(evt);
            }
        });
        testPanel.add(testTextField);

        add(testPanel, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    private void fixedRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fixedRadioButtonActionPerformed
        // Add your handling code here:
        if (fixedRadioButton.isSelected()){
            tierFormat.setProperty("row-height-calculation", "Fixed");
            fixedHeightTextField.setEditable(true);
        }                    
    }//GEN-LAST:event_fixedRadioButtonActionPerformed

    private void fixedHeightTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fixedHeightTextFieldActionPerformed
        // Add your handling code here:
        String txt = fixedHeightTextField.getText();
        try{
            short height = Short.parseShort(txt);
            if (height<0) throw new NumberFormatException();
            tierFormat.setProperty("fixed-row-height",Short.toString(height));
        } catch(NumberFormatException nfe){
            javax.swing.JOptionPane errorDialog = new javax.swing.JOptionPane();
            errorDialog.showMessageDialog(this, "Not a positive number.");       
            fixedHeightTextField.setText("10");
        }
        fixedHeightTextField.selectAll();
    }//GEN-LAST:event_fixedHeightTextFieldActionPerformed

    private void miserlyRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miserlyRadioButtonActionPerformed
        // Add your handling code here:
        //System.out.println("Now");
        if (miserlyRadioButton.isSelected()){
            tierFormat.setProperty("row-height-calculation", "Miserly");
            fixedHeightTextField.setEditable(false);
        }
    }//GEN-LAST:event_miserlyRadioButtonActionPerformed

    private void generousRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generousRadioButtonActionPerformed
        // Add your handling code here:
        if (generousRadioButton.isSelected()){
            tierFormat.setProperty("row-height-calculation", "Generous");
            fixedHeightTextField.setEditable(false);
        }            
    }//GEN-LAST:event_generousRadioButtonActionPerformed

    private void bottomCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottomCheckBoxActionPerformed
        // Add your handling code here:
        if (bottomCheckBox.isSelected()){
            tierFormat.setProperty("chunk-border",tierFormat.getProperty("chunk-border") + "b");
            return;
        } else {
            tierFormat.removeBorder("chunk-border","b");
        }                
    }//GEN-LAST:event_bottomCheckBoxActionPerformed

    private void topCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topCheckBoxActionPerformed
        // Add your handling code here:
        if (topCheckBox.isSelected()){
            tierFormat.setProperty("chunk-border",tierFormat.getProperty("chunk-border") + "t");
            return;
        } else {
            tierFormat.removeBorder("chunk-border","t");
        }                
    }//GEN-LAST:event_topCheckBoxActionPerformed

    private void rightCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightCheckBoxActionPerformed
        // Add your handling code here:
        if (rightCheckBox.isSelected()){
            tierFormat.setProperty("chunk-border",tierFormat.getProperty("chunk-border") + "r");
            return;
        } else {
            tierFormat.removeBorder("chunk-border","r");
        }                
    }//GEN-LAST:event_rightCheckBoxActionPerformed

    private void leftCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftCheckBoxActionPerformed
        // Add your handling code here:
        if (leftCheckBox.isSelected()){
            tierFormat.setProperty("chunk-border",tierFormat.getProperty("chunk-border") + "l");
            return;
        } else {
            tierFormat.removeBorder("chunk-border","l");
        }        
    }//GEN-LAST:event_leftCheckBoxActionPerformed

    private void borderColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borderColorButtonActionPerformed
        // Add your handling code here:
        java.awt.Color color = javax.swing.JColorChooser.showDialog(this, "Choose a color", tierFormat.getBgcolor());
        borderColorButton.setBackground(color);        
        tierFormat.setColor("chunk-border-color",color);        
    }//GEN-LAST:event_borderColorButtonActionPerformed

    private void borderStyleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borderStyleComboBoxActionPerformed
        // Add your handling code here:
        String newStyle = (String)borderStyleComboBox.getSelectedItem();
        tierFormat.setProperty("chunk-border-style",newStyle.toLowerCase());
    }//GEN-LAST:event_borderStyleComboBoxActionPerformed

    private void bgColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgColorButtonActionPerformed
        // Add your handling code here:
        java.awt.Color color = javax.swing.JColorChooser.showDialog(this, "Choose a color", tierFormat.getBgcolor());
        bgColorButton.setBackground(color);        
        testTextField.setBackground(color);
        tierFormat.setColor("bg-color",color);
    }//GEN-LAST:event_bgColorButtonActionPerformed

    private void textColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textColorButtonActionPerformed
        // Add your handling code here:
        java.awt.Color color = javax.swing.JColorChooser.showDialog(this, "Choose a color", tierFormat.getTextcolor());
        textColorButton.setBackground(color);
        testTextField.setForeground(color);
        tierFormat.setColor("font-color",color);        
    }//GEN-LAST:event_textColorButtonActionPerformed

  private void alignmentComboBoxActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alignmentComboBoxActionPerformed
// Add your handling code here:
    String newAlignment = (String)alignmentComboBox.getSelectedItem();
    tierFormat.setAlignmentName(newAlignment);
    formatTestField();
  }//GEN-LAST:event_alignmentComboBoxActionPerformed

  private void sizeComboBoxActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeComboBoxActionPerformed
// Add your handling code here:
    Integer newSize = new Integer((String)sizeComboBox.getSelectedItem());
    tierFormat.setSize(newSize.intValue());
    formatTestField();
  }//GEN-LAST:event_sizeComboBoxActionPerformed

  private void styleComboBoxActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_styleComboBoxActionPerformed
// Add your handling code here:
    String newStyle = (String)styleComboBox.getSelectedItem();
    tierFormat.setStyleName(newStyle);
    formatTestField();
  }//GEN-LAST:event_styleComboBoxActionPerformed

  private void fontComboBoxActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fontComboBoxActionPerformed
// Add your handling code here:
    String newFont = (String)fontComboBox.getSelectedItem();
    tierFormat.setFontName(newFont);
    formatTestField();
  }//GEN-LAST:event_fontComboBoxActionPerformed

  private void testTextFieldActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testTextFieldActionPerformed
// Add your handling code here:
  }//GEN-LAST:event_testTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox alignmentComboBox;
    private javax.swing.JButton bgColorButton;
    private javax.swing.JButton borderColorButton;
    private javax.swing.JComboBox borderStyleComboBox;
    private javax.swing.JCheckBox bottomCheckBox;
    private javax.swing.JTextField fixedHeightTextField;
    private javax.swing.JRadioButton fixedRadioButton;
    private javax.swing.JComboBox fontComboBox;
    private javax.swing.JPanel fontPropertiesPanel;
    private javax.swing.JRadioButton generousRadioButton;
    private javax.swing.ButtonGroup heightCalculationButtonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JCheckBox leftCheckBox;
    private javax.swing.JRadioButton miserlyRadioButton;
    private javax.swing.JCheckBox rightCheckBox;
    private javax.swing.JComboBox sizeComboBox;
    private javax.swing.JComboBox styleComboBox;
    private javax.swing.JPanel testPanel;
    private javax.swing.JTextField testTextField;
    private javax.swing.JButton textColorButton;
    private javax.swing.JCheckBox topCheckBox;
    // End of variables declaration//GEN-END:variables

    public void setEnabled(boolean value){
        testTextField.setEnabled(value);
        alignmentComboBox.setEnabled(value);
        bgColorButton.setEnabled(value);
        textColorButton.setEnabled(value);
        fontComboBox.setEnabled(value);
        styleComboBox.setEnabled(value);
        sizeComboBox.setEnabled(value);
    }
    
    private void formatTestField(){
        testTextField.setForeground(tierFormat.getTextcolor());
        testTextField.setBackground(tierFormat.getBgcolor());
        testTextField.setHorizontalAlignment(tierFormat.getAlignment());
        testTextField.setFont(tierFormat.getFont());
        //testTextField.repaint();
    }
    
    private void setSelections(){
        fontComboBox.setSelectedItem(tierFormat.getFontName());
        styleComboBox.setSelectedItem(tierFormat.getStyleName());
        sizeComboBox.setSelectedItem(tierFormat.getSizeAsString());
        textColorButton.setBackground(tierFormat.getTextcolor());
        bgColorButton.setBackground(tierFormat.getBgcolor());
        borderColorButton.setBackground(tierFormat.getColor("chunk-border-color"));        
        String bs = tierFormat.getProperty("chunk-border-style", "solid").substring(0,1).toUpperCase()
                    + tierFormat.getProperty("chunk-border-style", "solid").substring(1);
        borderStyleComboBox.setSelectedItem(bs);
        alignmentComboBox.setSelectedItem(tierFormat.getAlignmentName());
        leftCheckBox.setSelected(tierFormat.getProperty("chunk-border").indexOf('l')>=0);
        rightCheckBox.setSelected(tierFormat.getProperty("chunk-border").indexOf('r')>=0);
        topCheckBox.setSelected(tierFormat.getProperty("chunk-border").indexOf('t')>=0);
        bottomCheckBox.setSelected(tierFormat.getProperty("chunk-border").indexOf('b')>=0);
        if (tierFormat.getProperty("row-height-calculation","Generous").equals("Generous")){
            generousRadioButton.setSelected(true);
        } else if (tierFormat.getProperty("row-height-calculation","Generous").equals("Miserly")) {
            miserlyRadioButton.setSelected(true);
        } else {
            fixedRadioButton.setSelected(true);
            fixedHeightTextField.setEditable(true);
        }
        fixedHeightTextField.setText(tierFormat.getProperty("fixed-row-height","10"));
    }
         
}