/*
 * EditTierFormatDialog.java
 *
 * Created on 9. August 2001, 17:36
 */

package org.exmaralda.partitureditor.jexmaraldaswing;

import org.exmaralda.common.helpers.Internationalizer;

/**
 *
 * @author  Thomas
 * @version 
 */
public class EditTierFormatDialog extends JEscapeDialog {

    private EditTierFormatPanel editTierFormatPanel;
    private org.exmaralda.partitureditor.jexmaralda.TierFormat tierFormat;
    
    /** Creates new form EditTierFormatDialog */
    public EditTierFormatDialog(java.awt.Frame parent,boolean modal) {
        super (parent, modal);
        tierFormat = new org.exmaralda.partitureditor.jexmaralda.TierFormat();
        editTierFormatPanel = new EditTierFormatPanel(tierFormat);
        initComponents ();
        this.getRootPane().setDefaultButton(okButton);
        pack ();
        Internationalizer.internationalizeDialogToolTips(this);        
    }

    /** Creates new form EditTierFormatDialog */
    public EditTierFormatDialog(java.awt.Frame parent,boolean modal, org.exmaralda.partitureditor.jexmaralda.TierFormat tf) {
        super (parent, modal);
        tierFormat = tf.makeCopy();
        editTierFormatPanel = new EditTierFormatPanel(tierFormat);
        initComponents ();
        pack ();
        Internationalizer.internationalizeDialogToolTips(this);        
    }

    public org.exmaralda.partitureditor.jexmaralda.TierFormat getTierFormat(){
        return tierFormat;
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents () {//GEN-BEGIN:initComponents
        buttonPanel = new javax.swing.JPanel ();
        getContentPane ().add (editTierFormatPanel, java.awt.BorderLayout.CENTER);
        okButton = new javax.swing.JButton ();
        okButton.setMnemonic('O');
        cancelButton = new javax.swing.JButton ();
        cancelButton.setMnemonic('C');
        setTitle ("Edit tier format");
        addWindowListener (new java.awt.event.WindowAdapter () {
            public void windowClosing (java.awt.event.WindowEvent evt) {
                closeDialog (evt);
            }
        }
        );


          okButton.setPreferredSize (new java.awt.Dimension(80, 27));
          okButton.setMaximumSize (new java.awt.Dimension(80, 27));
          okButton.setMinimumSize (new java.awt.Dimension(80, 27));
          okButton.setText ("OK");
          okButton.addActionListener (new java.awt.event.ActionListener () {
              public void actionPerformed (java.awt.event.ActionEvent evt) {
                  okButtonActionPerformed (evt);
              }
          }
          );
  
          buttonPanel.add (okButton);
  
          cancelButton.setPreferredSize (new java.awt.Dimension(80, 27));
          cancelButton.setMaximumSize (new java.awt.Dimension(80, 27));
          cancelButton.setMinimumSize (new java.awt.Dimension(80, 27));
          cancelButton.setText ("Cancel");
          cancelButton.addActionListener (new java.awt.event.ActionListener () {
              public void actionPerformed (java.awt.event.ActionEvent evt) {
                  cancelButtonActionPerformed (evt);
              }
          }
          );
  
          buttonPanel.add (cancelButton);
  

        getContentPane ().add (buttonPanel, java.awt.BorderLayout.SOUTH);

    }//GEN-END:initComponents

  private void cancelButtonActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
// Add your handling code here:
        change = false;
        setVisible (false);
        dispose ();    
  }//GEN-LAST:event_cancelButtonActionPerformed

  private void okButtonActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
// Add your handling code here:
        change = true;
        tierFormat = editTierFormatPanel.getTierFormat();
        setVisible (false);
        dispose ();    
  }//GEN-LAST:event_okButtonActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        change = false;
        setVisible (false);
        dispose ();
    }//GEN-LAST:event_closeDialog

    /**
    * @param args the command line arguments
    */
    public static void main (String args[]) {
//        new EditTierFormatDialog (new javax.swing.JFrame (), true).show ();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton okButton;
    private javax.swing.JButton cancelButton;
    // End of variables declaration//GEN-END:variables

    
    public boolean editTierFormat(){
        java.awt.Dimension dialogSize = this.getPreferredSize();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(screenSize.width/2 - dialogSize.width/2, screenSize.height/2 - dialogSize.height/2);
        this.show();
        return change;
    }
}