/*
 * EditTierOrderDialog.java
 *
 * Created on 16. August 2001, 15:44
 */

package org.exmaralda.partitureditor.jexmaraldaswing;

import org.exmaralda.common.helpers.Internationalizer;
import org.exmaralda.partitureditor.jexmaralda.TierDescriptions;
import org.exmaralda.partitureditor.jexmaralda.BasicTranscription;
import org.exmaralda.partitureditor.jexmaralda.*;
import java.util.*;
/**
 *
 * @author  Thomas
 * @version 
 */
public class EditTierOrderDialog extends JEscapeDialog {

    private javax.swing.DefaultListModel tiersListModel;
    private String[] tierOrder;
    
    /** Creates new form EditTierOrderDialog */
    public EditTierOrderDialog(java.awt.Frame parent,boolean modal, BasicTranscription transcription) {
        super (parent, modal);
        tierOrder = transcription.getBody().getAllTierIDs();
        tiersListModel = new javax.swing.DefaultListModel();
        TierDescriptions td = new TierDescriptions(transcription);
        for (int pos=0; pos<tierOrder.length; pos++){
           String listEntry = new String(tierOrder[pos] + " (" + td.getTierDescriptionForTierID(tierOrder[pos]) + ")");
           tiersListModel.addElement(listEntry);
        }
        initComponents ();
        this.getRootPane().setDefaultButton(okButton);
        pack ();
        Internationalizer.internationalizeDialogToolTips(this);
    }

    public String[] getTierOrder(){
        return tierOrder;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tiersScrollPane = new javax.swing.JScrollPane();
        tiersList = new javax.swing.JList(tiersListModel);
        moveButtonPanel = new javax.swing.JPanel();
        upButton = new javax.swing.JButton();
        upButton.setMnemonic('u');
        upButton.setEnabled(false);
        downButton = new javax.swing.JButton();
        downButton.setMnemonic('d');
        downButton.setEnabled(false);
        buttonPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        okButton.setMnemonic('O');
        cancelButton = new javax.swing.JButton();
        cancelButton.setMnemonic('C');

        setTitle("Change tier order");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        tiersScrollPane.setPreferredSize(new java.awt.Dimension(258, 200));

        tiersList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                tiersListValueChanged(evt);
            }
        });
        tiersScrollPane.setViewportView(tiersList);

        getContentPane().add(tiersScrollPane, java.awt.BorderLayout.CENTER);

        moveButtonPanel.setLayout(new javax.swing.BoxLayout(moveButtonPanel, javax.swing.BoxLayout.Y_AXIS));

        upButton.setText("Up");
        upButton.setMaximumSize(new java.awt.Dimension(107, 27));
        upButton.setMinimumSize(new java.awt.Dimension(107, 27));
        upButton.setPreferredSize(new java.awt.Dimension(107, 27));
        upButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upButtonActionPerformed(evt);
            }
        });
        moveButtonPanel.add(upButton);

        downButton.setText("Down");
        downButton.setMaximumSize(new java.awt.Dimension(107, 27));
        downButton.setMinimumSize(new java.awt.Dimension(107, 27));
        downButton.setPreferredSize(new java.awt.Dimension(107, 27));
        downButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downButtonActionPerformed(evt);
            }
        });
        moveButtonPanel.add(downButton);

        getContentPane().add(moveButtonPanel, java.awt.BorderLayout.EAST);

        okButton.setText("OK");
        okButton.setMaximumSize(new java.awt.Dimension(110, 27));
        okButton.setMinimumSize(new java.awt.Dimension(80, 27));
        okButton.setPreferredSize(new java.awt.Dimension(110, 27));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(okButton);

        cancelButton.setText("Cancel");
        cancelButton.setMaximumSize(new java.awt.Dimension(110, 27));
        cancelButton.setMinimumSize(new java.awt.Dimension(80, 27));
        cancelButton.setPreferredSize(new java.awt.Dimension(110, 27));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(cancelButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

  private void cancelButtonActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
// Add your handling code here:
    change=false;
    setVisible (false);
    dispose ();        
  }//GEN-LAST:event_cancelButtonActionPerformed

  private void okButtonActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
// Add your handling code here:
    Vector result = new Vector();
    for (int pos=0; pos<tiersListModel.getSize(); pos++){
        String value = (String)tiersListModel.elementAt(pos);
        String tierID = value.substring(0, value.indexOf(" ("));
        result.addElement(tierID);
    }
    tierOrder = StringUtilities.stringVectorToArray(result);
    change=true;
    setVisible (false);
    dispose ();    
  }//GEN-LAST:event_okButtonActionPerformed

  private void downButtonActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downButtonActionPerformed
// Add your handling code here:
    int selection = tiersList.getSelectedIndex();
    String value = new String((String)tiersListModel.getElementAt(selection));
    String valueBelow = new String((String)tiersListModel.getElementAt(selection+1));
    tiersListModel.setElementAt(value, selection+1);
    tiersListModel.setElementAt(valueBelow, selection);
    tiersList.setSelectedIndex(selection+1);    
  }//GEN-LAST:event_downButtonActionPerformed

  private void upButtonActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upButtonActionPerformed
// Add your handling code here:
    int selection = tiersList.getSelectedIndex();
    String value = new String((String)tiersListModel.getElementAt(selection));
    String valueAbove = new String((String)tiersListModel.getElementAt(selection-1));
    tiersListModel.setElementAt(value, selection-1);
    tiersListModel.setElementAt(valueAbove, selection);
    tiersList.setSelectedIndex(selection-1);
  }//GEN-LAST:event_upButtonActionPerformed

  private void tiersListValueChanged (javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_tiersListValueChanged
// Add your handling code here:
    upButton.setEnabled(true);
    downButton.setEnabled(true);
    int selection = tiersList.getSelectedIndex();    
    if ((selection==-1) || (selection==0)){
        upButton.setEnabled(false);
    }
    if ((selection==-1) || (selection==tiersListModel.getSize()-1)){
        downButton.setEnabled(false);
    }            
  }//GEN-LAST:event_tiersListValueChanged

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        change=false;
        setVisible (false);
        dispose ();
    }//GEN-LAST:event_closeDialog

    /**
    * @param args the command line arguments
    */
    public static void main (String args[]) {
//        new EditTierOrderDialog (new javax.swing.JFrame (), true).show ();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton downButton;
    private javax.swing.JPanel moveButtonPanel;
    private javax.swing.JButton okButton;
    private javax.swing.JList tiersList;
    private javax.swing.JScrollPane tiersScrollPane;
    private javax.swing.JButton upButton;
    // End of variables declaration//GEN-END:variables

    public boolean editTierOrder(){
       java.awt.Dimension dialogSize = this.getPreferredSize();
       java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
       this.setLocation(screenSize.width/2 - dialogSize.width/2, screenSize.height/2 - dialogSize.height/2);
       show();
       return change;
    }
}