/*
 * SingleTierSelectionDialog.java
 *
 * Created on 4. Dezember 2007, 10:50
 */

package org.exmaralda.partitureditor.jexmaraldaswing;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.exmaralda.partitureditor.jexmaralda.Tier;
import org.exmaralda.partitureditor.jexmaralda.BasicTranscription;
import org.exmaralda.partitureditor.jexmaralda.JexmaraldaException;

/**
 *
 * @author  thomas
 */
public class SingleSpeakerSelectionDialog extends OKCancelDialog {
    
    javax.swing.DefaultComboBoxModel comboBoxModel;
    List<String> speakerIDs;
    
    /** Creates new form SingleTierSelectionDialog
     * @param bt
     * @param parent
     * @param modal */
    public SingleSpeakerSelectionDialog(BasicTranscription bt, List<String> speakerIDs, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSpeakers(bt, speakerIDs);
    }
    
    public void setExplanationText(String text){
        explanationLabel.setText(text);
    }
    
    final void setSpeakers(BasicTranscription bt, List<String> speakerIDs){
        String[] descs = new String[speakerIDs.size()];
        int pos=0;
        for (String speakerID : speakerIDs){
            try {
                String abb = bt.getHead().getSpeakertable().getSpeakerWithID(speakerID).getAbbreviation();
                descs[pos] = speakerID + " (" + abb + ")";
                pos++;
            } catch (JexmaraldaException ex) {
                Logger.getLogger(SingleSpeakerSelectionDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        comboBoxModel = new javax.swing.DefaultComboBoxModel(descs);
        speakerSelectionComboBox.setModel(comboBoxModel);
        this.speakerIDs = speakerIDs;
    }
    
    public String getSelectedSpeakerID(){
        return speakerIDs.get(speakerSelectionComboBox.getSelectedIndex());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        speakerSelectionComboBox = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        explanationLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Speaker selection");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setMinimumSize(new java.awt.Dimension(250, 60));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 60));

        speakerSelectionComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        speakerSelectionComboBox.setMaximumSize(new java.awt.Dimension(200, 22));
        speakerSelectionComboBox.setMinimumSize(new java.awt.Dimension(200, 22));
        speakerSelectionComboBox.setPreferredSize(new java.awt.Dimension(200, 22));
        jPanel1.add(speakerSelectionComboBox);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        explanationLabel.setText("jLabel1");
        jPanel2.add(explanationLabel);

        getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        speakerSelectionComboBox.requestFocus();
    }//GEN-LAST:event_formComponentShown
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    }

    @Override
    public void setVisible(boolean b) {
        if(b){
            java.awt.Dimension dialogSize = this.getPreferredSize();
            java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
            this.setLocation(screenSize.width/2 - dialogSize.width/2, screenSize.height/2 - dialogSize.height/2);             
        }
        super.setVisible(b);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel explanationLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox speakerSelectionComboBox;
    // End of variables declaration//GEN-END:variables
    
}
