/*
 * SingleTierSelectionDialog.java
 *
 * Created on 4. Dezember 2007, 10:50
 */

package org.exmaralda.partitureditor.jexmaraldaswing;

import org.exmaralda.partitureditor.jexmaralda.Tier;
import org.exmaralda.partitureditor.jexmaralda.BasicTranscription;

/**
 *
 * @author  thomas
 */
public class SingleTierSelectionDialog extends OKCancelDialog {
    
    javax.swing.DefaultComboBoxModel comboBoxModel;
    String[] tierIDs;
    
    /** Creates new form SingleTierSelectionDialog */
    public SingleTierSelectionDialog(BasicTranscription bt, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTranscription(bt);
    }
    
    void setTranscription(BasicTranscription bt){
        String[] descs = new String[bt.getBody().getNumberOfTiers()];
        for (int pos=0; pos<bt.getBody().getNumberOfTiers(); pos++){
            Tier t = bt.getBody().getTierAt(pos);
            String d = t.getDescription(bt.getHead().getSpeakertable());
            String id = t.getID();
            descs[pos] = d + " (" + id + ")";
        }
        comboBoxModel = new javax.swing.DefaultComboBoxModel(descs);
        tierSelectionComboBox.setModel(comboBoxModel);
        tierIDs = bt.getBody().getAllTierIDs();
    }
    
    public String getSelectedTierID(){
        return tierIDs[tierSelectionComboBox.getSelectedIndex()];
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tierSelectionComboBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tier selection");

        jPanel1.setMinimumSize(new java.awt.Dimension(250, 60));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 60));

        tierSelectionComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tierSelectionComboBox.setMaximumSize(new java.awt.Dimension(200, 22));
        tierSelectionComboBox.setMinimumSize(new java.awt.Dimension(200, 22));
        tierSelectionComboBox.setPreferredSize(new java.awt.Dimension(200, 22));
        jPanel1.add(tierSelectionComboBox);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    }

    public void setVisible(boolean b) {
        if(b){
            java.awt.Dimension dialogSize = this.getPreferredSize();
            java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
            this.setLocation(screenSize.width/2 - dialogSize.width/2, screenSize.height/2 - dialogSize.height/2);             
        }
        super.setVisible(b);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox tierSelectionComboBox;
    // End of variables declaration//GEN-END:variables
    
}
