/*
 * SpeakerContributionNavigationDialog.java
 *
 * Created on 1. April 2004, 13:53
 */

package org.exmaralda.partitureditor.jexmaraldaswing;

import org.exmaralda.common.helpers.Internationalizer;
import org.exmaralda.partitureditor.partiture.PartitureTableWithActions;
import org.exmaralda.partitureditor.jexmaralda.Event;
import org.exmaralda.partitureditor.jexmaralda.SpeakerContribution;
import java.util.*;
import org.exmaralda.partitureditor.jexmaralda.*;
import org.exmaralda.partitureditor.partiture.*;

/**
 *
 * @author  thomas
 */
public class SpeakerContributionNavigationDialog extends javax.swing.JDialog {
    
    Vector speakerContributions;
    Hashtable tliMappings;
    String[] descriptions;
    PartitureTableWithActions table;
    
    /** Creates new form SpeakerContributionNavigationDialog */
    public SpeakerContributionNavigationDialog( java.awt.Frame parent, boolean modal, 
                                                Vector scs, Hashtable tlim, PartitureTableWithActions t) {
        super(parent, modal);
        tliMappings = tlim;
        speakerContributions = scs;
        table = t; 
        descriptions = new String[scs.size()];
        for (int pos=0; pos<speakerContributions.size(); pos++){
            SpeakerContribution sc = (SpeakerContribution)(speakerContributions.elementAt(pos));
            String desc = sc.getMain().getDescription();
            descriptions[pos] = desc;            
        }        
        initComponents();
        scList.setSelectedIndex(0);
        Internationalizer.internationalizeDialogToolTips(this);        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        scList = new javax.swing.JList(descriptions);
        gotoPanel = new javax.swing.JPanel();
        gotoButton = new javax.swing.JButton();

        setTitle("Segments outside the common timeline");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        mainPanel.setLayout(new javax.swing.BoxLayout(mainPanel, javax.swing.BoxLayout.LINE_AXIS));

        scList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(scList);

        mainPanel.add(jScrollPane1);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        gotoButton.setText("Go to");
        gotoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoButtonActionPerformed(evt);
            }
        });
        gotoPanel.add(gotoButton);

        getContentPane().add(gotoPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gotoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotoButtonActionPerformed
        // Add your handling code here:
        int index = scList.getSelectedIndex();
        SpeakerContribution sc = (SpeakerContribution)(speakerContributions.elementAt(index));
        String start = sc.getMain().getStart();
        String correspondingStart = (String)(tliMappings.get(start));
        System.out.println(correspondingStart);
        
        // make a dummy search result and send it to the table
        // so that it scrolls to the offending positiion
        org.exmaralda.partitureditor.search.EventSearchResult esr = new org.exmaralda.partitureditor.search.EventSearchResult();
        Event ev = new Event();
        ev.setStart(correspondingStart);
        esr.event = ev;
        esr.tierID = "";
        table.processSearchResult(esr);        
    }//GEN-LAST:event_gotoButtonActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void scListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scListMouseClicked
        if (evt.getClickCount()==2){
            this.gotoButtonActionPerformed(null);
        }
    }//GEN-LAST:event_scListMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //new SpeakerContributionNavigationDialog(new javax.swing.JFrame(), true).show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gotoButton;
    private javax.swing.JPanel gotoPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JList scList;
    // End of variables declaration//GEN-END:variables
    
    public void show(){
        java.awt.Dimension dialogSize = this.getPreferredSize();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(screenSize.width/2 - dialogSize.width/2, screenSize.height/2 - dialogSize.height/2);        
        super.show();
    }
        
}
