/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.exmaralda.partitureditor.jexmaraldaswing;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

/**
 *
 * @author Thomas_Schmidt
 */
public class SplitLongEventDialog extends javax.swing.JDialog {

    public boolean approved = false;
    
    /**
     * Creates new form SplitLongEventDialog
     * @param parent
     * @param modal
     */
    public SplitLongEventDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        // disable input - we only want the cursor
        eventTextArea.addKeyListener(new KeyListener(){

            @Override
            public void keyTyped(KeyEvent e) {
                if (!(isArrowKey(e.getKeyCode()))){
                    e.consume();
                }
            }

            @Override
            public void keyPressed(KeyEvent e) {
                if (!(isArrowKey(e.getKeyCode()))){
                    e.consume();
                }                
            }

            @Override
            public void keyReleased(KeyEvent e) {
                if (!(isArrowKey(e.getKeyCode()))){
                    e.consume();
                }                
            }
        });        
    }
    
    private boolean isArrowKey(int keyCode){
        return (
                keyCode==KeyEvent.VK_LEFT || 
                keyCode==KeyEvent.VK_RIGHT || 
                keyCode==KeyEvent.VK_UP || 
                keyCode==KeyEvent.VK_DOWN ||
                keyCode==KeyEvent.VK_KP_LEFT || 
                keyCode==KeyEvent.VK_KP_RIGHT || 
                keyCode==KeyEvent.VK_KP_UP || 
                keyCode==KeyEvent.VK_KP_DOWN 
                );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eventTextScrollPane = new javax.swing.JScrollPane();
        eventTextArea = new javax.swing.JTextArea();
        buttonPanel = new javax.swing.JPanel();
        splitButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Split long event");

        eventTextScrollPane.setMinimumSize(new java.awt.Dimension(600, 400));
        eventTextScrollPane.setPreferredSize(new java.awt.Dimension(600, 400));

        eventTextArea.setColumns(20);
        eventTextArea.setLineWrap(true);
        eventTextArea.setRows(5);
        eventTextArea.setWrapStyleWord(true);
        eventTextArea.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                eventTextAreaCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        eventTextScrollPane.setViewportView(eventTextArea);

        getContentPane().add(eventTextScrollPane, java.awt.BorderLayout.CENTER);

        splitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/exmaralda/partitureditor/partiture/Icons/Split.png"))); // NOI18N
        splitButton.setText("Split");
        splitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                splitButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(splitButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(cancelButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void splitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_splitButtonActionPerformed
        approved = true;
        dispose();
    }//GEN-LAST:event_splitButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void eventTextAreaCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_eventTextAreaCaretPositionChanged

    }//GEN-LAST:event_eventTextAreaCaretPositionChanged

    
    public int getCursorPosition(){
        return eventTextArea.getCaretPosition();
    }
    
    public void setText(String eventText){
        eventTextArea.setText(eventText);
        eventTextArea.setCaretPosition(eventText.length()/2);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplitLongEventDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplitLongEventDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplitLongEventDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplitLongEventDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SplitLongEventDialog dialog = new SplitLongEventDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextArea eventTextArea;
    private javax.swing.JScrollPane eventTextScrollPane;
    private javax.swing.JButton splitButton;
    // End of variables declaration//GEN-END:variables
}
