/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.exmaralda.partitureditor.jexmaraldaswing;

import com.klg.jclass.table.JCTableDataEvent;
import com.klg.jclass.table.JCTableDataListener;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import org.exmaralda.folker.utilities.PreferencesUtilities;
import org.exmaralda.partitureditor.jexmaralda.BasicTranscription;
import org.exmaralda.partitureditor.jexmaralda.Event;
import org.exmaralda.partitureditor.jexmaralda.Tier;
import org.exmaralda.partitureditor.jexmaraldaswing.fileFilters.ParameterFileFilter;
import org.exmaralda.partitureditor.partiture.AbstractTranscriptionTableModel;
import org.exmaralda.partitureditor.partiture.PartiturEditor;
import org.exmaralda.partitureditor.search.EventSearchResult;
import org.exmaralda.partitureditor.search.SearchResultListener;
import org.exmaralda.partitureditor.sound.Playable;

// new for #382


/**
 *
 * @author thomas.schmidt
 */
public class TabulateEventsTableDialog extends javax.swing.JDialog implements JCTableDataListener, TableModelListener {

    List<SearchResultListener> searchResultListenerList = new ArrayList<>();
    List<JCTableDataListener> tableDataListenerList = new ArrayList<>();
    BasicTranscription transcription;
    Tier mainTier;
    TabulateEventsTableModel tableModel;
    
    int rowIndex;
    Playable player;
    
    /**
     * Creates new form ListEventsDialog
     * @param parent
     * @param modal
     * @param transcription
     * @param mainTier
     * @param dependentTiers
     */
    public TabulateEventsTableDialog(java.awt.Frame parent, boolean modal, BasicTranscription transcription, Tier mainTier, Tier[] dependentTiers) {
        super(parent, modal);
        this.mainTier = mainTier;
        this.transcription = transcription;
        initComponents();
        tableModel = new TabulateEventsTableModel(transcription, mainTier, dependentTiers);
        tableModel.theTable = eventTable;
        tableModel.addTableModelListener(this);
        tableModel.fireTableDataChanged();
        eventTable.setModel(tableModel);
        eventTable.setDefaultRenderer(Double.class, new ListEventsTableCellRenderer());
        eventTable.setDefaultRenderer(Integer.class, new ListEventsTableCellRenderer());
        eventTable.setDefaultRenderer(String.class, new ListEventsTableCellRenderer());
        eventTable.getColumnModel().getColumn(0).setPreferredWidth(40);
        eventTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        eventTable.getColumnModel().getColumn(2).setPreferredWidth(100);
        eventTable.getColumnModel().getColumn(3).setPreferredWidth(60);
        eventTable.getColumnModel().getColumn(4).setPreferredWidth(250);
        for (int i=0; i<dependentTiers.length; i++){
            eventTable.getColumnModel().getColumn(5 + i).setPreferredWidth(250);            
        }
        eventTable.setRowHeight(18);
        displayNameLabel.setText(mainTier.getDisplayName());
        //Dimension d = new Dimension(eventListPanel.getPreferredSize().width + dependentTiers.length * 250, eventListPanel.getPreferredSize().height);
        //eventListPanel.setPreferredSize(d);
        pack();
        
    }
    
    public void setPlayer(Playable player){
        this.player = player;
    }
    
    public void addSearchResultListener(SearchResultListener listener){
        searchResultListenerList.add(listener);
    }
    
    public void addTableDataListener(JCTableDataListener listener){
        tableDataListenerList.add(listener);
    }


    public void fireSearchResult(EventSearchResult esr){
        for (SearchResultListener listener : searchResultListenerList){
            listener.processSearchResult(esr);
        }
    }

    public void fireDataChanged(JCTableDataEvent evt){
        for (JCTableDataListener listener : tableDataListenerList){
            listener.dataChanged(evt);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eventListPanel = new javax.swing.JPanel();
        eventTableScrollPane = new javax.swing.JScrollPane();
        eventTable = new javax.swing.JTable();
        topPanel = new javax.swing.JPanel();
        displayNameLabel = new javax.swing.JLabel();
        bottomPanel = new javax.swing.JPanel();
        exportButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tabulate events");

        eventListPanel.setMaximumSize(new java.awt.Dimension(1200, 800));
        eventListPanel.setPreferredSize(new java.awt.Dimension(820, 400));
        eventListPanel.setLayout(new java.awt.BorderLayout());

        eventTableScrollPane.setMaximumSize(new java.awt.Dimension(1200, 800));
        eventTableScrollPane.setPreferredSize(new java.awt.Dimension(620, 400));

        eventTable.setAutoCreateRowSorter(true);
        eventTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        eventTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        eventTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        eventTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        eventTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eventTableMouseClicked(evt);
            }
        });
        eventTableScrollPane.setViewportView(eventTable);

        eventListPanel.add(eventTableScrollPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(eventListPanel, java.awt.BorderLayout.CENTER);

        displayNameLabel.setText("jLabel1");
        topPanel.add(displayNameLabel);

        getContentPane().add(topPanel, java.awt.BorderLayout.PAGE_START);

        exportButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/exmaralda/partitureditor/partiture/Icons/file-csv-solid-full.png"))); // NOI18N
        exportButton.setText("Export...");
        exportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportButtonActionPerformed(evt);
            }
        });
        bottomPanel.add(exportButton);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        bottomPanel.add(closeButton);

        getContentPane().add(bottomPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eventTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventTableMouseClicked
        if (evt.getClickCount()==2){
            int index = eventTable.convertRowIndexToModel(eventTable.getSelectedRow());
            
            Event event = mainTier.getEventAt(index);
            EventSearchResult esr = new EventSearchResult();
            esr.tierID = mainTier.getID();
            esr.event = event;
            esr.offset = 0;
            esr.tierName = mainTier.getDisplayName();
            esr.length = event.getDescription().length();
            fireSearchResult(esr);
        }
    }//GEN-LAST:event_eventTableMouseClicked

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void exportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        PartiturEditor pe = (PartiturEditor)getParent();
        ParameterFileFilter csvFilter = new ParameterFileFilter("csv", "Comma separated values, UTF-8 (*.csv)");
        fileChooser.setFileFilter(csvFilter);
        fileChooser.setDialogTitle("Export tabulated events as CSV file");
        String userNode = pe.getPreferencesNode();
        java.util.prefs.Preferences settings = java.util.prefs.Preferences.userRoot().node(userNode);
        String startDirectory = settings.get("LastExportDirectory", PreferencesUtilities.getProperty("workingDirectory", ""));
        File startDirectoryFile = new File(startDirectory);
        if (startDirectoryFile.isDirectory()){
            fileChooser.setCurrentDirectory(startDirectoryFile);
        } else {
            fileChooser.setCurrentDirectory(startDirectoryFile.getParentFile());            
        }
        
        int approved = fileChooser.showSaveDialog(this);
        if (approved==JFileChooser.APPROVE_OPTION){
            FileOutputStream fos = null;
            File selectedFile = fileChooser.getSelectedFile();
            settings.put("LastExportDirectory", selectedFile.getAbsolutePath());        
            String filename = selectedFile.getAbsolutePath();

            //check whether or not the selected file has an extension
            if (!selectedFile.getName().contains(".")){
                filename+=".csv";
            }

            File exportFile = new File(filename);
            
            try {
                if (exportFile.exists()){
                    int option = JOptionPane.showConfirmDialog(pe, "File " + exportFile.getAbsolutePath() + " exists.\nOverwrite?");
                    pe.getPartitur().status("CSV saving canceled.");
                    if (option!=JOptionPane.YES_OPTION) return;
                }   String csv = tableModel.toCSV();
                System.out.println("Started writing CSV document..." + exportFile.getAbsolutePath());
                fos = new FileOutputStream(exportFile);
                fos.write("\uFEFF".getBytes("UTF-8")); // BOM BOM
                fos.write(csv.getBytes("UTF-8"));
                fos.close();
                System.out.println("CSV document written.");
                pe.getPartitur().status("CSV file " + exportFile.getAbsolutePath() + " written. ");
            } catch (IOException ex) {
                Logger.getLogger(TabulateEventsTableDialog.class.getName()).log(Level.SEVERE, null, ex);
                String message = "File " + exportFile.getAbsolutePath() + "\ncould not be written. Error message:\n" + ex.getLocalizedMessage();
                JOptionPane.showMessageDialog(pe, message);
                pe.getPartitur().status("Error writing CSV.");
            } finally {
                try {
                    fos.close();
                } catch (IOException ex) {
                    Logger.getLogger(TabulateEventsTableDialog.class.getName()).log(Level.SEVERE, null, ex);
                    String message = "File " + exportFile.getAbsolutePath() + "\ncould not be written. Error message:\n" + ex.getLocalizedMessage();
                    JOptionPane.showMessageDialog(pe, message);
                    pe.getPartitur().status("Error writing CSV.");
                }
            }
        }
    }//GEN-LAST:event_exportButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabulateEventsTableDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabulateEventsTableDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabulateEventsTableDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabulateEventsTableDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                /*ListEventsDialog dialog = new ListEventsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);*/
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel displayNameLabel;
    private javax.swing.JPanel eventListPanel;
    private javax.swing.JTable eventTable;
    private javax.swing.JScrollPane eventTableScrollPane;
    private javax.swing.JButton exportButton;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void dataChanged(JCTableDataEvent evt) {
        int command = evt.getCommand();
        switch(command){
            case JCTableDataEvent.RESET :
                this.dispose();
                break;
                
            case JCTableDataEvent.CHANGE_VALUE : 
                if (evt.getRow()==rowIndex){
                    tableModel.fireTableDataChanged();
                }
                break;
                
            case JCTableDataEvent.REMOVE_ROW :
                if (evt.getRow()==rowIndex){
                    dispose();
                }
                break;
                
            case JCTableDataEvent.ADD_COLUMN :
                tableModel.fireTableDataChanged();
                break;
            
            case JCTableDataEvent.REMOVE_COLUMN :
                tableModel.fireTableDataChanged();
                break;
                
            case JCTableDataEvent.CHANGE_ROW_LABEL :
                if (evt.getRow()==rowIndex){
                    tableModel.fireTableDataChanged();                    
                }
                break;
                
                               
            case AbstractTranscriptionTableModel.ROWS_SWAPPED :
                break;
                
            case AbstractTranscriptionTableModel.AREA_CHANGED :
                break;
            
            case AbstractTranscriptionTableModel.CELL_SPAN_CHANGED :
                if (evt.getRow()==rowIndex){
                    tableModel.fireTableDataChanged();
                }
                break;
        }


    }

    @Override
    public void tableChanged(TableModelEvent e) {
        if (e.getType()==TableModelEvent.UPDATE){
            JCTableDataEvent event = new JCTableDataEvent(this, rowIndex, e.getFirstRow(), 0, 0, JCTableDataEvent.CHANGE_VALUE );
            this.fireDataChanged(event);
        }
    }
}
