/*
 * WelcomeMessagePanel.java
 *
 * Created on 7. November 2001, 12:33
 */

package org.exmaralda.partitureditor.jexmaraldaswing;

import org.exmaralda.common.helpers.Internationalizer;

/**
 *
 * @author  Thomas
 */
public class WelcomeMessagePanel extends javax.swing.JPanel {

    /** Creates new form WelcomeMessagePanel */
    public WelcomeMessagePanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextArea();
        jTextArea3 = new javax.swing.JTextArea();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        jLabel1.setBackground(java.awt.Color.red);
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/exmaralda/partitureditor/partiture/Icons/Exmaralda.gif")));
        jLabel1.setText("EXMARaLDA");
        add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("   PARTITUR-EDITOR");
        jPanel1.add(jLabel2);

        jTextArea1.setBackground(java.awt.Color.lightGray);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 11));
        jTextArea1.setText(" Version 1.3.5  (xxxxx 2008)\n        (C) 2001 - 2008  by Thomas Schmidt.\n         thomas.schmidt@uni-hamburg.de\n         http://www.exmaralda.org");
        jPanel1.add(jTextArea1);

        jTextArea3.setBackground(java.awt.Color.lightGray);
        jTextArea3.setEditable(false);
        jTextArea3.setFont(new java.awt.Font("Monospaced", 0, 11));
        jTextArea3.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea3.setText(Internationalizer.getString(
            "German localization by Annette Schnieder"
            + System.getProperty("line.separator")
            + "Turkish localization by Tulay Selcuk"
            + System.getProperty("line.separator")
            + "Swedish localization by Hanna Hedeland"
        )        );
        jPanel1.add(jTextArea3);

        jTextArea2.setBackground(java.awt.Color.lightGray);
        jTextArea2.setEditable(false);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 0, 10));
        jTextArea2.setText("       Thanks to all beta testers and bug reporters.");
        jPanel1.add(jTextArea2);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 11));
        jLabel3.setForeground(java.awt.Color.red);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Please do not copy, redistribute etc. ");
        jPanel1.add(jLabel3);

        add(jPanel1, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables

}
