/*
 * CharReplaceDialog.java
 *
 * Created on 29. Oktober 2002, 12:34
 */

package org.exmaralda.partitureditor.exHIATDOS.swing;

import java.util.*;

/**
 *
 * @author  Thomas
 */
public class CharReplaceDialog extends org.exmaralda.partitureditor.jexmaraldaswing.JEscapeDialog {

    char[][] STANDARD_CHARS = {
                              {'\u017D', '\u00C4'},     // großes Ä
                              {'\u201E', '\u00E4'},     // kleines ä
                              {'\u2122', '\u00D6'},     // großes Ö
                              {'\u201D', '\u00F6'},     // kleines ö
                              {'\u0161', '\u00DC'},     // großes Ü
                              {'\u0081', '\u00FC'},     // kleines ü
                              {'\u00E1', '\u00DF'},     // sz (ß)   
                             };
    
    Vector charReplace;
    
    /** Creates new form CharReplaceDialog */
    public CharReplaceDialog(java.awt.Frame parent, boolean modal, char[][] cr) {
        super(parent, modal);
        initComponents();
        this.getRootPane().setDefaultButton(okButton);
        charReplace = new Vector();
        for (int pos=0; pos<cr.length; pos++){
            charReplace.addElement(cr[pos]);
        }
        setListContent();
        if (charReplace.size()>0){
            jList1.setSelectedIndex(0);
        }
        org.exmaralda.common.helpers.Internationalizer.internationalizeDialogToolTips(this);
    }
    
    public char[][] getCharReplace(){
        char[][] result = new char[charReplace.size()][2];
        for (int pos=0; pos<charReplace.size(); pos++){
            result[pos] = (char[])(charReplace.elementAt(pos));
        }
        return result;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        setTitle("Replace symbols");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(50, 300));
        jList1.setFont(new java.awt.Font("Arial Unicode MS", 0, 12));
        jList1.setMaximumSize(new java.awt.Dimension(50, 1000));
        jList1.setMinimumSize(new java.awt.Dimension(10, 10));
        jList1.setPreferredSize(new java.awt.Dimension(50, 1000));
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        jButton1.setText("Remove");
        jButton1.setMaximumSize(new java.awt.Dimension(96, 26));
        jButton1.setMinimumSize(new java.awt.Dimension(96, 26));
        jButton1.setPreferredSize(new java.awt.Dimension(96, 26));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel4.add(jButton1);

        jButton2.setText("Remove all");
        jButton2.setMaximumSize(new java.awt.Dimension(96, 26));
        jButton2.setPreferredSize(new java.awt.Dimension(96, 26));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel4.add(jButton2);

        jButton3.setText("Standard");
        jButton3.setMaximumSize(new java.awt.Dimension(96, 26));
        jButton3.setMinimumSize(new java.awt.Dimension(96, 26));
        jButton3.setPreferredSize(new java.awt.Dimension(96, 26));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel4.add(jButton3);

        jPanel1.add(jPanel4);

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(3, 1));

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.X_AXIS));

        jLabel2.setText("To be replaced: ");
        jLabel2.setMaximumSize(new java.awt.Dimension(100, 16));
        jLabel2.setMinimumSize(new java.awt.Dimension(100, 16));
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel5.add(jLabel2);

        jTextField1.setFont(new java.awt.Font("Courier New", 0, 12));
        jTextField1.setMaximumSize(new java.awt.Dimension(50, 20));
        jTextField1.setMinimumSize(new java.awt.Dimension(50, 20));
        jTextField1.setPreferredSize(new java.awt.Dimension(50, 20));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jPanel5.add(jTextField1);

        jLabel1.setMaximumSize(new java.awt.Dimension(20, 10));
        jLabel1.setPreferredSize(new java.awt.Dimension(20, 10));
        jPanel5.add(jLabel1);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel4.setText("(Enter decimal unicode number)");
        jPanel5.add(jLabel4);

        jPanel2.add(jPanel5);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.X_AXIS));

        jLabel3.setText("Replacement: ");
        jLabel3.setMaximumSize(new java.awt.Dimension(100, 16));
        jLabel3.setMinimumSize(new java.awt.Dimension(100, 16));
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel6.add(jLabel3);

        jTextField2.setFont(new java.awt.Font("Courier New", 0, 12));
        jTextField2.setMaximumSize(new java.awt.Dimension(50, 20));
        jTextField2.setMinimumSize(new java.awt.Dimension(50, 20));
        jTextField2.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel6.add(jTextField2);

        jLabel6.setMaximumSize(new java.awt.Dimension(20, 10));
        jLabel6.setPreferredSize(new java.awt.Dimension(20, 10));
        jPanel6.add(jLabel6);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel5.setText("(Enter decimal unicode number)");
        jPanel6.add(jLabel5);

        jPanel2.add(jPanel6);

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jPanel7.add(addButton);

        jPanel2.add(jPanel7);

        getContentPane().add(jPanel2);

        okButton.setText("OK");
        okButton.setMaximumSize(new java.awt.Dimension(73, 26));
        okButton.setMinimumSize(new java.awt.Dimension(73, 26));
        okButton.setPreferredSize(new java.awt.Dimension(73, 26));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        jPanel3.add(okButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jPanel3.add(cancelButton);

        getContentPane().add(jPanel3);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Add your handling code here:
        charReplace = new Vector();
        for (int pos=0; pos<STANDARD_CHARS.length; pos++){
            charReplace.addElement(STANDARD_CHARS[pos]);
        }
        setListContent();        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // Add your handling code here:
        change = false;
        setVisible(false);
        dispose();                
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // Add your handling code here:
        change = true;
        setVisible(false);
        dispose();                
    }//GEN-LAST:event_okButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Add your handling code here:
        charReplace = new Vector();
        setListContent();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Add your handling code here:
        if (jList1.getSelectedIndex()>=0){
            charReplace.removeElementAt(jList1.getSelectedIndex());
            this.setListContent();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // Add your handling code here:
        try {
            int i1 = Integer.parseInt(jTextField1.getText());
            int i2 = Integer.parseInt(jTextField2.getText());
            if (i1<0 || i1 > 65535 || i2<0 || i2 > 65536) {
                throw new NumberFormatException();
            }
            char c1 = (char)i1;
            char c2 = (char)i2;
            char[] newc = {c1, c2};
            charReplace.addElement(newc);
            this.setListContent();
        } catch (NumberFormatException nfe){
                javax.swing.JOptionPane errorDialog = new javax.swing.JOptionPane();
                errorDialog.showMessageDialog(  this.getParent(),
                                        "Error in unicode numbers!",
                                        "Error",
                                        javax.swing.JOptionPane.ERROR_MESSAGE);              
        }
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        change = false;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        //new CharReplaceDialog(new javax.swing.JFrame(), true).show();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

    private void setListContent(){
        Vector listData = new Vector();
        for (int pos=0; pos<charReplace.size(); pos++){
            char[] c = (char[])(charReplace.elementAt(pos));
            int i1 = c[0];
            int i2 = c[1];
            String text = c[0] + " (" + i1 + ") " + "\u21A6" + " " + c[1] + " (" + i2 + ") ";
            listData.addElement(text);
        }
        jList1.setListData(listData);
        if (charReplace.size()>0){
            jList1.setSelectedIndex(0);
        }
    }
    
    public void show(){
        java.awt.Dimension dialogSize = this.getPreferredSize();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(screenSize.width/2 - dialogSize.width/2, screenSize.height/2 - dialogSize.height/2);
        super.show();
    }
}
