/*
 * mainPanel.java
 *
 * Created on 9. Mai 2008, 13:59
 */

package org.exmaralda.folker.application;

import java.awt.Component;
import java.awt.Font;
import org.exmaralda.folker.gui.VirtualKey;
import org.exmaralda.folker.utilities.FOLKERInternationalizer;
import org.exmaralda.folker.utilities.PreferencesUtilities;

/**
 *
 * @author  thomas
 */
public class MainPanel extends javax.swing.JPanel {
           
    
    ApplicationControl applicationControl;
    
    /** Creates new form mainPanel */
    public MainPanel(ApplicationControl ac) {
        applicationControl = ac;
        
        initComponents();        
        initComponents2();

        String os = System.getProperty("os.name").substring(0,3);
        if (os.equalsIgnoreCase("mac")) {
            configureForMac();
        }

        progressBar.setVisible(false);

    }

    void setVirtualKeyFonts(Font f) {
        for (Component c : virtualKeyboardPanel.getComponents()){
            if (c instanceof VirtualKey){
                ((VirtualKey)c).setFont(f);
            }
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timeTextViewsSplitPane = new javax.swing.JSplitPane();
        timeViewPanel = new javax.swing.JPanel();
        infoPanel = new javax.swing.JPanel();
        playerInfoPanel = new javax.swing.JPanel();
        markTimePanel = new javax.swing.JPanel();
        markTimeLabel = new javax.swing.JLabel();
        startTimePanel = new javax.swing.JPanel();
        startTimePanelLabel = new javax.swing.JLabel();
        startTimeLabel = new javax.swing.JLabel();
        cursorTimePanel = new javax.swing.JPanel();
        cursorTimePanelLabel = new javax.swing.JLabel();
        cursorTimeLabel = new javax.swing.JLabel();
        stopTimePanel = new javax.swing.JPanel();
        stopTimeLabel = new javax.swing.JLabel();
        stopTimePanelLabel = new javax.swing.JLabel();
        selectionLengthPanel = new javax.swing.JPanel();
        selectionLengthLabel = new javax.swing.JLabel();
        waveFormInfoPanel = new javax.swing.JPanel();
        secondsPerPixelLabel = new javax.swing.JLabel();
        zoomToggleButton = new javax.swing.JToggleButton();
        navigatePanel = new javax.swing.JPanel();
        navigateButton = new javax.swing.JButton();
        controlsPanel = new javax.swing.JPanel();
        playerControlsPanel = new javax.swing.JPanel();
        selectionControlsPanel = new javax.swing.JPanel();
        playLastSecondBeforeSelectionButton = new javax.swing.JButton();
        playFirstSecondOfSelectionButton = new javax.swing.JButton();
        playSelectionButton = new javax.swing.JButton();
        playLastSecondOfSelectionButton = new javax.swing.JButton();
        playFirstSecondAfterSelectionButton = new javax.swing.JButton();
        loopSelectionButton = new javax.swing.JButton();
        playButton = new javax.swing.JButton();
        pauseButton = new javax.swing.JToggleButton();
        stopButton = new javax.swing.JButton();
        selectionsControlPanel = new javax.swing.JPanel();
        shiftSelectionButton = new javax.swing.JButton();
        detachSelectionButton = new javax.swing.JButton();
        playbackControlsPanel = new javax.swing.JPanel();
        playNextSegmentButton = new javax.swing.JButton();
        textViewPanel = new javax.swing.JPanel();
        textViewsTabbedPane = new javax.swing.JTabbedPane();
        eventViewPanel = new javax.swing.JPanel();
        eventViewScrollPane = new javax.swing.JScrollPane();
        eventViewButtonPanel = new javax.swing.JPanel();
        addEventButton = new javax.swing.JButton();
        appendEventButton = new javax.swing.JButton();
        removeEventButton = new javax.swing.JButton();
        timestampEventButton = new javax.swing.JButton();
        splitEventInListButton = new javax.swing.JButton();
        mergeEventsInListButton = new javax.swing.JButton();
        insertPauseButton = new javax.swing.JButton();
        nextErrorButton = new javax.swing.JButton();
        addMaskButton = new javax.swing.JButton();
        partiturViewPanel = new javax.swing.JPanel();
        partiturViewButtonPanel = new javax.swing.JPanel();
        splitEventButton = new javax.swing.JButton();
        mergeEventsButton = new javax.swing.JButton();
        shiftLeftButton = new javax.swing.JButton();
        shiftRightButton = new javax.swing.JButton();
        shrinkLeftButton = new javax.swing.JButton();
        shrinkRightButton = new javax.swing.JButton();
        extendLeftButton = new javax.swing.JButton();
        extendRightButton = new javax.swing.JButton();
        addEventInPartiturButton = new javax.swing.JButton();
        insertPauseInPartiturButton = new javax.swing.JButton();
        removeEventInPartiturButton = new javax.swing.JButton();
        maskInPartiturButton = new javax.swing.JButton();
        contributionViewPanel = new javax.swing.JPanel();
        contributionViewSplitPane = new javax.swing.JSplitPane();
        contributionTablePanel = new javax.swing.JPanel();
        contributionViewTableScrollPane = new javax.swing.JScrollPane();
        contributionViewButtonPanel = new javax.swing.JPanel();
        nextErrorButton2 = new javax.swing.JButton();
        contributionTextPanel = new javax.swing.JPanel();
        contributionViewTextAreaScrollPane = new javax.swing.JScrollPane();
        contributionTextButtonPanel = new javax.swing.JPanel();
        splitInContributionButton = new javax.swing.JButton();
        virtualKeyboardPanel = new javax.swing.JPanel();
        commentButton = new javax.swing.JButton();
        accentButton = new javax.swing.JButton();
        strongAccentButton = new javax.swing.JButton();
        removeAccentButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        statusInfoPanel = new javax.swing.JPanel();
        statusPanel = new javax.swing.JPanel();
        statusMessageLabel = new javax.swing.JLabel();
        infoPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        playerLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        parseLevelLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.BorderLayout());

        timeTextViewsSplitPane.setDividerLocation(200);
        timeTextViewsSplitPane.setDividerSize(12);
        timeTextViewsSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        timeViewPanel.setLayout(new java.awt.BorderLayout());

        infoPanel.setLayout(new java.awt.BorderLayout());

        markTimePanel.setLayout(new javax.swing.BoxLayout(markTimePanel, javax.swing.BoxLayout.LINE_AXIS));

        markTimeLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        markTimeLabel.setForeground(new java.awt.Color(255, 0, 0));
        markTimeLabel.setText("-");
        markTimeLabel.setToolTipText(FOLKERInternationalizer.getString("waveform.markposition"));
        markTimePanel.add(markTimeLabel);

        playerInfoPanel.add(markTimePanel);

        startTimePanel.setLayout(new javax.swing.BoxLayout(startTimePanel, javax.swing.BoxLayout.LINE_AXIS));

        startTimePanelLabel.setForeground(java.awt.Color.blue);
        startTimePanelLabel.setText("[");
        startTimePanel.add(startTimePanelLabel);

        startTimeLabel.setForeground(new java.awt.Color(51, 204, 0));
        startTimeLabel.setText("-");
        startTimeLabel.setToolTipText(FOLKERInternationalizer.getString("waveform.startposition"));
        startTimePanel.add(startTimeLabel);

        playerInfoPanel.add(startTimePanel);

        cursorTimePanel.setLayout(new javax.swing.BoxLayout(cursorTimePanel, javax.swing.BoxLayout.LINE_AXIS));
        cursorTimePanel.add(cursorTimePanelLabel);

        cursorTimeLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cursorTimeLabel.setText("-");
        cursorTimeLabel.setToolTipText(FOLKERInternationalizer.getString("waveform.cursorposition"));
        cursorTimePanel.add(cursorTimeLabel);

        playerInfoPanel.add(cursorTimePanel);

        stopTimePanel.setLayout(new javax.swing.BoxLayout(stopTimePanel, javax.swing.BoxLayout.LINE_AXIS));

        stopTimeLabel.setForeground(new java.awt.Color(255, 0, 51));
        stopTimeLabel.setText("-");
        stopTimeLabel.setToolTipText(FOLKERInternationalizer.getString("waveform.stopposition"));
        stopTimePanel.add(stopTimeLabel);

        stopTimePanelLabel.setForeground(java.awt.Color.blue);
        stopTimePanelLabel.setText("]");
        stopTimePanel.add(stopTimePanelLabel);

        playerInfoPanel.add(stopTimePanel);

        selectionLengthPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        selectionLengthPanel.setForeground(new java.awt.Color(102, 102, 102));
        selectionLengthPanel.setLayout(new javax.swing.BoxLayout(selectionLengthPanel, javax.swing.BoxLayout.LINE_AXIS));

        selectionLengthLabel.setText("-");
        selectionLengthLabel.setToolTipText(FOLKERInternationalizer.getString("waveform.selectionlength"));
        selectionLengthPanel.add(selectionLengthLabel);

        playerInfoPanel.add(selectionLengthPanel);

        infoPanel.add(playerInfoPanel, java.awt.BorderLayout.CENTER);

        waveFormInfoPanel.setLayout(new javax.swing.BoxLayout(waveFormInfoPanel, javax.swing.BoxLayout.LINE_AXIS));

        secondsPerPixelLabel.setText("1px=0.0005s ");
        waveFormInfoPanel.add(secondsPerPixelLabel);

        zoomToggleButton.setText("jToggleButton1");
        waveFormInfoPanel.add(zoomToggleButton);

        infoPanel.add(waveFormInfoPanel, java.awt.BorderLayout.EAST);

        navigateButton.setText("jButton1");
        navigatePanel.add(navigateButton);

        infoPanel.add(navigatePanel, java.awt.BorderLayout.WEST);

        timeViewPanel.add(infoPanel, java.awt.BorderLayout.NORTH);

        controlsPanel.setLayout(new java.awt.BorderLayout());

        selectionControlsPanel.setLayout(new javax.swing.BoxLayout(selectionControlsPanel, javax.swing.BoxLayout.LINE_AXIS));

        playLastSecondBeforeSelectionButton.setText("jButton1");
        selectionControlsPanel.add(playLastSecondBeforeSelectionButton);

        playFirstSecondOfSelectionButton.setText("jButton1");
        selectionControlsPanel.add(playFirstSecondOfSelectionButton);

        playSelectionButton.setText("jButton1");
        selectionControlsPanel.add(playSelectionButton);

        playLastSecondOfSelectionButton.setText("jButton1");
        selectionControlsPanel.add(playLastSecondOfSelectionButton);

        playFirstSecondAfterSelectionButton.setText("jButton1");
        selectionControlsPanel.add(playFirstSecondAfterSelectionButton);

        playerControlsPanel.add(selectionControlsPanel);

        loopSelectionButton.setText("jButton1");
        playerControlsPanel.add(loopSelectionButton);

        playButton.setText("jButton1");
        playerControlsPanel.add(playButton);

        pauseButton.setText("jToggleButton1");
        playerControlsPanel.add(pauseButton);

        stopButton.setText("jButton1");
        playerControlsPanel.add(stopButton);

        controlsPanel.add(playerControlsPanel, java.awt.BorderLayout.CENTER);

        shiftSelectionButton.setText("shiftSelectionButton");
        selectionsControlPanel.add(shiftSelectionButton);

        detachSelectionButton.setText("jButton1");
        selectionsControlPanel.add(detachSelectionButton);

        controlsPanel.add(selectionsControlPanel, java.awt.BorderLayout.EAST);

        playNextSegmentButton.setText("jButton1");
        playbackControlsPanel.add(playNextSegmentButton);

        controlsPanel.add(playbackControlsPanel, java.awt.BorderLayout.WEST);

        timeViewPanel.add(controlsPanel, java.awt.BorderLayout.SOUTH);

        timeTextViewsSplitPane.setLeftComponent(timeViewPanel);

        textViewPanel.setLayout(new java.awt.BorderLayout());

        eventViewPanel.setLayout(new java.awt.BorderLayout());
        eventViewPanel.add(eventViewScrollPane, java.awt.BorderLayout.CENTER);

        eventViewButtonPanel.setLayout(new javax.swing.BoxLayout(eventViewButtonPanel, javax.swing.BoxLayout.Y_AXIS));

        addEventButton.setText("jButton1");
        addEventButton.setMaximumSize(new java.awt.Dimension(30, 30));
        addEventButton.setMinimumSize(new java.awt.Dimension(30, 30));
        addEventButton.setPreferredSize(new java.awt.Dimension(30, 30));
        addEventButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEventButtonActionPerformed(evt);
            }
        });
        eventViewButtonPanel.add(addEventButton);

        appendEventButton.setText("jButton1");
        appendEventButton.setMaximumSize(new java.awt.Dimension(30, 30));
        appendEventButton.setMinimumSize(new java.awt.Dimension(30, 30));
        appendEventButton.setPreferredSize(new java.awt.Dimension(30, 30));
        eventViewButtonPanel.add(appendEventButton);

        removeEventButton.setText("jButton1");
        removeEventButton.setMaximumSize(new java.awt.Dimension(30, 30));
        removeEventButton.setMinimumSize(new java.awt.Dimension(30, 30));
        removeEventButton.setPreferredSize(new java.awt.Dimension(30, 30));
        eventViewButtonPanel.add(removeEventButton);

        timestampEventButton.setText("jButton1");
        timestampEventButton.setMaximumSize(new java.awt.Dimension(30, 30));
        timestampEventButton.setMinimumSize(new java.awt.Dimension(30, 30));
        timestampEventButton.setPreferredSize(new java.awt.Dimension(30, 30));
        eventViewButtonPanel.add(timestampEventButton);

        splitEventInListButton.setText("jButton1");
        splitEventInListButton.setMaximumSize(new java.awt.Dimension(30, 30));
        splitEventInListButton.setMinimumSize(new java.awt.Dimension(30, 30));
        splitEventInListButton.setPreferredSize(new java.awt.Dimension(30, 30));
        eventViewButtonPanel.add(splitEventInListButton);

        mergeEventsInListButton.setText("jButton1");
        mergeEventsInListButton.setMaximumSize(new java.awt.Dimension(30, 30));
        mergeEventsInListButton.setMinimumSize(new java.awt.Dimension(30, 30));
        mergeEventsInListButton.setPreferredSize(new java.awt.Dimension(30, 30));
        eventViewButtonPanel.add(mergeEventsInListButton);

        insertPauseButton.setText("jButton1");
        insertPauseButton.setMaximumSize(new java.awt.Dimension(30, 30));
        insertPauseButton.setMinimumSize(new java.awt.Dimension(30, 30));
        insertPauseButton.setPreferredSize(new java.awt.Dimension(30, 30));
        eventViewButtonPanel.add(insertPauseButton);

        nextErrorButton.setText("jButton1");
        nextErrorButton.setMaximumSize(new java.awt.Dimension(30, 30));
        nextErrorButton.setMinimumSize(new java.awt.Dimension(30, 30));
        nextErrorButton.setPreferredSize(new java.awt.Dimension(30, 30));
        eventViewButtonPanel.add(nextErrorButton);

        addMaskButton.setText("jButton1");
        addMaskButton.setMaximumSize(new java.awt.Dimension(30, 30));
        addMaskButton.setMinimumSize(new java.awt.Dimension(30, 30));
        addMaskButton.setPreferredSize(new java.awt.Dimension(30, 30));
        addMaskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMaskButtonActionPerformed(evt);
            }
        });
        eventViewButtonPanel.add(addMaskButton);

        eventViewPanel.add(eventViewButtonPanel, java.awt.BorderLayout.EAST);

        textViewsTabbedPane.addTab(FOLKERInternationalizer.getString("gui.segments"), null, eventViewPanel, FOLKERInternationalizer.getString("gui.segmentstooltip"));

        partiturViewPanel.setLayout(new java.awt.BorderLayout());

        splitEventButton.setText("jButton1");
        splitEventButton.setPreferredSize(new java.awt.Dimension(24, 24));
        partiturViewButtonPanel.add(splitEventButton);

        mergeEventsButton.setText("jButton1");
        mergeEventsButton.setPreferredSize(new java.awt.Dimension(24, 24));
        partiturViewButtonPanel.add(mergeEventsButton);

        shiftLeftButton.setText("jButton1");
        shiftLeftButton.setPreferredSize(new java.awt.Dimension(24, 24));
        partiturViewButtonPanel.add(shiftLeftButton);

        shiftRightButton.setText("jButton1");
        shiftRightButton.setPreferredSize(new java.awt.Dimension(24, 24));
        partiturViewButtonPanel.add(shiftRightButton);

        shrinkLeftButton.setText("jButton1");
        shrinkLeftButton.setPreferredSize(new java.awt.Dimension(24, 24));
        partiturViewButtonPanel.add(shrinkLeftButton);

        shrinkRightButton.setText("jButton1");
        shrinkRightButton.setPreferredSize(new java.awt.Dimension(24, 24));
        partiturViewButtonPanel.add(shrinkRightButton);

        extendLeftButton.setText("jButton2");
        extendLeftButton.setPreferredSize(new java.awt.Dimension(24, 24));
        partiturViewButtonPanel.add(extendLeftButton);

        extendRightButton.setText("jButton1");
        extendRightButton.setPreferredSize(new java.awt.Dimension(24, 24));
        partiturViewButtonPanel.add(extendRightButton);

        addEventInPartiturButton.setText("jButton1");
        addEventInPartiturButton.setPreferredSize(new java.awt.Dimension(24, 24));
        partiturViewButtonPanel.add(addEventInPartiturButton);

        insertPauseInPartiturButton.setText("jButton1");
        insertPauseInPartiturButton.setPreferredSize(new java.awt.Dimension(24, 24));
        partiturViewButtonPanel.add(insertPauseInPartiturButton);

        removeEventInPartiturButton.setText("jButton1");
        removeEventInPartiturButton.setPreferredSize(new java.awt.Dimension(24, 24));
        partiturViewButtonPanel.add(removeEventInPartiturButton);

        maskInPartiturButton.setText("jButton1");
        partiturViewButtonPanel.add(maskInPartiturButton);

        partiturViewPanel.add(partiturViewButtonPanel, java.awt.BorderLayout.NORTH);

        textViewsTabbedPane.addTab(FOLKERInternationalizer.getString("gui.partitur"), null, partiturViewPanel, FOLKERInternationalizer.getString("gui.partiturtooltip"));

        contributionViewPanel.setAlignmentX(0.0F);
        contributionViewPanel.setLayout(new java.awt.BorderLayout());

        contributionViewSplitPane.setDividerSize(10);
        contributionViewSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        contributionViewSplitPane.setResizeWeight(1.0);

        contributionTablePanel.setLayout(new java.awt.BorderLayout());

        contributionViewTableScrollPane.setMinimumSize(new java.awt.Dimension(20, 100));
        contributionViewTableScrollPane.setPreferredSize(new java.awt.Dimension(800, 400));
        contributionTablePanel.add(contributionViewTableScrollPane, java.awt.BorderLayout.CENTER);

        contributionViewButtonPanel.setAlignmentX(0.0F);
        contributionViewButtonPanel.setLayout(new javax.swing.BoxLayout(contributionViewButtonPanel, javax.swing.BoxLayout.Y_AXIS));

        nextErrorButton2.setText("jButton1");
        nextErrorButton2.setMaximumSize(new java.awt.Dimension(30, 30));
        nextErrorButton2.setMinimumSize(new java.awt.Dimension(30, 30));
        nextErrorButton2.setPreferredSize(new java.awt.Dimension(30, 30));
        contributionViewButtonPanel.add(nextErrorButton2);

        contributionTablePanel.add(contributionViewButtonPanel, java.awt.BorderLayout.EAST);

        contributionViewSplitPane.setLeftComponent(contributionTablePanel);

        contributionTextPanel.setLayout(new java.awt.BorderLayout());

        contributionViewTextAreaScrollPane.setMinimumSize(new java.awt.Dimension(10, 100));
        contributionViewTextAreaScrollPane.setPreferredSize(new java.awt.Dimension(600, 150));
        contributionTextPanel.add(contributionViewTextAreaScrollPane, java.awt.BorderLayout.CENTER);

        contributionTextButtonPanel.setLayout(new javax.swing.BoxLayout(contributionTextButtonPanel, javax.swing.BoxLayout.Y_AXIS));

        splitInContributionButton.setText("jButton1");
        splitInContributionButton.setMaximumSize(new java.awt.Dimension(30, 30));
        splitInContributionButton.setMinimumSize(new java.awt.Dimension(30, 30));
        splitInContributionButton.setPreferredSize(new java.awt.Dimension(30, 30));
        contributionTextButtonPanel.add(splitInContributionButton);

        contributionTextPanel.add(contributionTextButtonPanel, java.awt.BorderLayout.EAST);

        contributionViewSplitPane.setRightComponent(contributionTextPanel);

        contributionViewPanel.add(contributionViewSplitPane, java.awt.BorderLayout.CENTER);

        textViewsTabbedPane.addTab(FOLKERInternationalizer.getString("gui.contributions"), null, contributionViewPanel, FOLKERInternationalizer.getString("gui.contributionstooltip"));

        textViewPanel.add(textViewsTabbedPane, java.awt.BorderLayout.CENTER);
        textViewsTabbedPane.getAccessibleContext().setAccessibleName(FOLKERInternationalizer.getString("gui.segments"));

        virtualKeyboardPanel.setBackground(java.awt.SystemColor.controlShadow);

        commentButton.setText("<<xxx> ...>");
        commentButton.setToolTipText("Kommentar");
        commentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commentButtonActionPerformed(evt);
            }
        });
        virtualKeyboardPanel.add(commentButton);

        accentButton.setText("abAB");
        accentButton.setToolTipText("Akzent");
        accentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accentButtonActionPerformed(evt);
            }
        });
        virtualKeyboardPanel.add(accentButton);

        strongAccentButton.setText("ab!AB!");
        strongAccentButton.setToolTipText("starker Akzent");
        strongAccentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strongAccentButtonActionPerformed(evt);
            }
        });
        virtualKeyboardPanel.add(strongAccentButton);

        removeAccentButton.setText("ABab");
        removeAccentButton.setToolTipText("Akzentmarkierungen entfernen");
        removeAccentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAccentButtonActionPerformed(evt);
            }
        });
        virtualKeyboardPanel.add(removeAccentButton);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        virtualKeyboardPanel.add(jSeparator1);

        textViewPanel.add(virtualKeyboardPanel, java.awt.BorderLayout.NORTH);

        timeTextViewsSplitPane.setRightComponent(textViewPanel);

        add(timeTextViewsSplitPane, java.awt.BorderLayout.CENTER);

        statusInfoPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        statusInfoPanel.setLayout(new java.awt.BorderLayout());

        statusPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        statusPanel.setLayout(new javax.swing.BoxLayout(statusPanel, javax.swing.BoxLayout.LINE_AXIS));

        statusMessageLabel.setText("Folker gestartet. ");
        statusPanel.add(statusMessageLabel);

        progressBar.setToolTipText("Bitte warten...");
        progressBar.setIndeterminate(true);
        progressBar.setMaximumSize(new java.awt.Dimension(100, 19));
        progressBar.setPreferredSize(new java.awt.Dimension(100, 19));
        statusPanel.add(progressBar);

        statusInfoPanel.add(statusPanel, java.awt.BorderLayout.WEST);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Player: ");
        infoPanel2.add(jLabel1);

        playerLabel.setText("xxx");
        infoPanel2.add(playerLabel);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Parse-Level: ");
        infoPanel2.add(jLabel2);

        parseLevelLabel.setText("xxx");
        infoPanel2.add(parseLevelLabel);

        statusInfoPanel.add(infoPanel2, java.awt.BorderLayout.EAST);

        add(statusInfoPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void commentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commentButtonActionPerformed
        applicationControl.insertGATComment();
    }//GEN-LAST:event_commentButtonActionPerformed

    private void accentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accentButtonActionPerformed
       applicationControl.insertAccent();
    }//GEN-LAST:event_accentButtonActionPerformed

    private void strongAccentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strongAccentButtonActionPerformed
       applicationControl.insertStrongAccent();
    }//GEN-LAST:event_strongAccentButtonActionPerformed

    private void removeAccentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAccentButtonActionPerformed
        applicationControl.removeAccent();
    }//GEN-LAST:event_removeAccentButtonActionPerformed

    private void addEventButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEventButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addEventButtonActionPerformed

    private void addMaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMaskButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addMaskButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton accentButton;
    public javax.swing.JButton addEventButton;
    public javax.swing.JButton addEventInPartiturButton;
    public javax.swing.JButton addMaskButton;
    public javax.swing.JButton appendEventButton;
    javax.swing.JButton commentButton;
    private javax.swing.JPanel contributionTablePanel;
    private javax.swing.JPanel contributionTextButtonPanel;
    javax.swing.JPanel contributionTextPanel;
    private javax.swing.JPanel contributionViewButtonPanel;
    javax.swing.JPanel contributionViewPanel;
    public javax.swing.JSplitPane contributionViewSplitPane;
    public javax.swing.JScrollPane contributionViewTableScrollPane;
    public javax.swing.JScrollPane contributionViewTextAreaScrollPane;
    private javax.swing.JPanel controlsPanel;
    public javax.swing.JLabel cursorTimeLabel;
    private javax.swing.JPanel cursorTimePanel;
    private javax.swing.JLabel cursorTimePanelLabel;
    public javax.swing.JButton detachSelectionButton;
    private javax.swing.JPanel eventViewButtonPanel;
    public javax.swing.JPanel eventViewPanel;
    javax.swing.JScrollPane eventViewScrollPane;
    public javax.swing.JButton extendLeftButton;
    public javax.swing.JButton extendRightButton;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JPanel infoPanel2;
    public javax.swing.JButton insertPauseButton;
    public javax.swing.JButton insertPauseInPartiturButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JButton loopSelectionButton;
    public javax.swing.JLabel markTimeLabel;
    private javax.swing.JPanel markTimePanel;
    public javax.swing.JButton maskInPartiturButton;
    public javax.swing.JButton mergeEventsButton;
    public javax.swing.JButton mergeEventsInListButton;
    public javax.swing.JButton navigateButton;
    private javax.swing.JPanel navigatePanel;
    public javax.swing.JButton nextErrorButton;
    public javax.swing.JButton nextErrorButton2;
    public javax.swing.JLabel parseLevelLabel;
    private javax.swing.JPanel partiturViewButtonPanel;
    javax.swing.JPanel partiturViewPanel;
    public javax.swing.JToggleButton pauseButton;
    public javax.swing.JButton playButton;
    public javax.swing.JButton playFirstSecondAfterSelectionButton;
    public javax.swing.JButton playFirstSecondOfSelectionButton;
    public javax.swing.JButton playLastSecondBeforeSelectionButton;
    public javax.swing.JButton playLastSecondOfSelectionButton;
    public javax.swing.JButton playNextSegmentButton;
    public javax.swing.JButton playSelectionButton;
    private javax.swing.JPanel playbackControlsPanel;
    private javax.swing.JPanel playerControlsPanel;
    private javax.swing.JPanel playerInfoPanel;
    public javax.swing.JLabel playerLabel;
    public final javax.swing.JProgressBar progressBar = new javax.swing.JProgressBar();
    javax.swing.JButton removeAccentButton;
    public javax.swing.JButton removeEventButton;
    public javax.swing.JButton removeEventInPartiturButton;
    public javax.swing.JLabel secondsPerPixelLabel;
    private javax.swing.JPanel selectionControlsPanel;
    public javax.swing.JLabel selectionLengthLabel;
    private javax.swing.JPanel selectionLengthPanel;
    private javax.swing.JPanel selectionsControlPanel;
    public javax.swing.JButton shiftLeftButton;
    public javax.swing.JButton shiftRightButton;
    public javax.swing.JButton shiftSelectionButton;
    public javax.swing.JButton shrinkLeftButton;
    public javax.swing.JButton shrinkRightButton;
    public javax.swing.JButton splitEventButton;
    public javax.swing.JButton splitEventInListButton;
    public javax.swing.JButton splitInContributionButton;
    public javax.swing.JLabel startTimeLabel;
    private javax.swing.JPanel startTimePanel;
    private javax.swing.JLabel startTimePanelLabel;
    private javax.swing.JPanel statusInfoPanel;
    public javax.swing.JLabel statusMessageLabel;
    private javax.swing.JPanel statusPanel;
    public javax.swing.JButton stopButton;
    public javax.swing.JLabel stopTimeLabel;
    private javax.swing.JPanel stopTimePanel;
    private javax.swing.JLabel stopTimePanelLabel;
    javax.swing.JButton strongAccentButton;
    javax.swing.JPanel textViewPanel;
    public javax.swing.JTabbedPane textViewsTabbedPane;
    public javax.swing.JSplitPane timeTextViewsSplitPane;
    private javax.swing.JPanel timeViewPanel;
    public javax.swing.JButton timestampEventButton;
    javax.swing.JPanel virtualKeyboardPanel;
    private javax.swing.JPanel waveFormInfoPanel;
    public javax.swing.JToggleButton zoomToggleButton;
    // End of variables declaration//GEN-END:variables
    
    void initComponents2(){
        timeViewPanel.add(applicationControl.timeViewScrollPane, java.awt.BorderLayout.CENTER);

        eventViewScrollPane.setViewportView(applicationControl.eventListTable);     
        contributionViewTableScrollPane.setViewportView(applicationControl.contributionListTable);
        contributionViewTextAreaScrollPane.setViewportView(applicationControl.contributionTextPane);
        
        partiturViewPanel.add(applicationControl.partitur, java.awt.BorderLayout.CENTER);

        initVirtualKeyboard();
    }

    private void initVirtualKeyboard() {
        Font font = new java.awt.Font("Arial Unicode MS", Font.PLAIN, 12);
        String customFont = PreferencesUtilities.getProperty("font", "");
        if (customFont.length()>0){
            font = new java.awt.Font(customFont, Font.PLAIN, 12);
        }
        String[][] keyDefs = {
            {"(.) ", "keyboard.micropause"},
            {"\u00B0", "keyboard.breathe"},
            {"\u0294", "keyboard.glottalstop"},
            {"\u007C", "keyboard.segmentseparator"},

            {"\u2013", "keyboard.level"},

            {"\u2191", "keyboard.smalljumpup"},
            {"\u2191\u2191", "keyboard.bigjumpup"},
            {"\u2193", "keyboard.smalljumpdown"},
            {"\u2193\u2193", "keyboard.bigjumpdown"},
            {"\u0060", "keyboard.accentfall"},
            {"\u00B4", "keyboard.accentrise"},
            {"\u00AF", "keyboard.accentlevel"},
            {"\u02C6", "keyboard.accentrisefall"},
            {"\u02C7", "keyboard.accentfallrise"}
        };
        for (String[] keyDef : keyDefs){
            VirtualKey vk = new VirtualKey(keyDef[0], FOLKERInternationalizer.getString(keyDef[1]), font);
            virtualKeyboardPanel.add(vk);
        }


    }

    void configureForMac(){
        playLastSecondBeforeSelectionButton.putClientProperty("JButton.buttonType", "segmented");
        playLastSecondBeforeSelectionButton.putClientProperty("JButton.segmentPosition","first");
        playFirstSecondOfSelectionButton.putClientProperty("JButton.buttonType", "segmented");
        playFirstSecondOfSelectionButton.putClientProperty("JButton.segmentPosition","middle");
        playSelectionButton.putClientProperty("JButton.buttonType", "segmented");
        playSelectionButton.putClientProperty("JButton.segmentPosition","middle");
        playLastSecondOfSelectionButton.putClientProperty("JButton.buttonType", "segmented");
        playLastSecondOfSelectionButton.putClientProperty("JButton.segmentPosition","middle");
        playFirstSecondAfterSelectionButton.putClientProperty("JButton.buttonType", "segmented");
        playFirstSecondAfterSelectionButton.putClientProperty("JButton.segmentPosition","last");
    }

}
