/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.exmaralda.partitureditor.jexmaraldaswing.fileDialogs;

/**
 *
 * @author Schmidt
 */
public class TCFExportAccessoryPanel extends javax.swing.JPanel {

    /**
     * Creates new form TCFExportAccessoryPanel
     */
    public TCFExportAccessoryPanel() {
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        languageComboBox = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        segmentationComboBox = new javax.swing.JComboBox();
        ;

        setBorder(javax.swing.BorderFactory.createTitledBorder("TCF Export Parameters"));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Language"));

        languageComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "de", "en", "cs", "es", "fr", "it", "nl", "ro" }));
        languageComboBox.setMaximumSize(new java.awt.Dimension(100, 25));
        languageComboBox.setMinimumSize(new java.awt.Dimension(100, 25));
        languageComboBox.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel1.add(languageComboBox);

        add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Segmentation"));

        segmentationComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "HIAT", "cGAT Minimal", "Generic"}));
        segmentationComboBox.setMaximumSize(new java.awt.Dimension(100, 25));
        segmentationComboBox.setMinimumSize(new java.awt.Dimension(100, 25));
        segmentationComboBox.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel2.add(segmentationComboBox);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JComboBox languageComboBox;
    public javax.swing.JComboBox segmentationComboBox;
    // End of variables declaration//GEN-END:variables
}
