/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RegexLibraryEntryPanel.java
 *
 * Created on 04.08.2010, 13:32:45
 */

package org.exmaralda.exakt.regex;

import javax.swing.text.BadLocationException;
import org.exmaralda.common.jdomutilities.IOUtilities;
import org.jdom.Element;

/**
 *
 * @author thomas
 */
public class RegexLibraryEntryPanel extends javax.swing.JPanel {

    /** Creates new form RegexLibraryEntryPanel */
    public RegexLibraryEntryPanel() {
        initComponents();
    }

    public void setEntry(Element entryElement){
        nameTextField.setText(entryElement.getAttributeValue("name"));
        regexTextField.setText(entryElement.getChildText("regex"));
        String description = IOUtilities.elementToString(entryElement.getChild("description")).replaceAll("<description>", "").replaceAll("</description>", "");
        //descriptionEditorPane.setText("<html><head></head><body>" + description + "</body></html>");
        descriptionEditorPane.setText(description);
        descriptionEditorPane.setCaretPosition(0);
        String explanation = IOUtilities.elementToString(entryElement.getChild("explanation")).replaceAll("<explanation>", "").replaceAll("</explanation>", "");
        //explanationEditorPane.setText("<html><head></head><body>" + explanation + "</body></html>");
        explanationEditorPane.setText(explanation);
        explanationEditorPane.setCaretPosition(0);
        String examples = "";
        for (Object o : entryElement.getChild("examples").getChildren()){
            Element example = (Element)o;
            examples+=example.getText() + "<br/>";
        }
        //examplesEditorPane.setText("<html><head></head><body>" + examples + "</body></html>");
        examplesEditorPane.setText(examples);
        examplesEditorPane.setCaretPosition(0);        
    }

    public Element getEntry()  {
        Element entry = new Element("entry");
        entry.setAttribute("name", nameTextField.getText());

        Element regex = new Element("regex");
        regex.setText(regexTextField.getText());
        entry.addContent(regex);

        Element description = new Element("description");
        try {
            description.setText(descriptionEditorPane.getDocument().getText(0, descriptionEditorPane.getDocument().getLength()));
        } catch (BadLocationException ex) {
            ex.printStackTrace();
        }
        entry.addContent(description);

        Element explanation = new Element("explanation");
        try {
            explanation.setText(explanationEditorPane.getDocument().getText(0, explanationEditorPane.getDocument().getLength()));
        } catch (BadLocationException ex) {
            ex.printStackTrace();
        }
        entry.addContent(explanation);

        Element examples = new Element("examples");
        try {
            String examplesText = examplesEditorPane.getDocument().getText(0, examplesEditorPane.getDocument().getLength());
            for (String ex : examplesText.split("\\n")){
                if (ex.trim().length()==0) continue;
                Element example = new Element("example");
                example.setText(ex);
                examples.addContent(example);
            }
        } catch (BadLocationException ex) {
            ex.printStackTrace();
        }
        entry.addContent(examples);
        return entry;

    }


    public void setEditable(boolean editable){
        nameTextField.setEditable(editable);
        regexTextField.setEditable(editable);
        descriptionEditorPane.setEditable(editable);
        explanationEditorPane.setEditable(editable);
        examplesEditorPane.setEditable(editable);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        descriptionPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionEditorPane = new javax.swing.JEditorPane();
        explanationPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        explanationEditorPane = new javax.swing.JEditorPane();
        examplesPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        examplesEditorPane = new javax.swing.JEditorPane();
        jPanel2 = new javax.swing.JPanel();
        namePanel = new javax.swing.JPanel();
        nameTextField = new javax.swing.JTextField();
        regexPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        regexTextField = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(3, 1));

        descriptionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Description"));
        descriptionPanel.setLayout(new javax.swing.BoxLayout(descriptionPanel, javax.swing.BoxLayout.LINE_AXIS));

        descriptionEditorPane.setBackground(new java.awt.Color(240, 240, 240));
        descriptionEditorPane.setContentType("text/html");
        descriptionEditorPane.setEditable(false);
        descriptionEditorPane.setPreferredSize(new java.awt.Dimension(400, 70));
        jScrollPane1.setViewportView(descriptionEditorPane);

        descriptionPanel.add(jScrollPane1);

        jPanel1.add(descriptionPanel);

        explanationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Explanation"));
        explanationPanel.setLayout(new javax.swing.BoxLayout(explanationPanel, javax.swing.BoxLayout.LINE_AXIS));

        explanationEditorPane.setBackground(new java.awt.Color(240, 240, 240));
        explanationEditorPane.setContentType("text/html");
        explanationEditorPane.setEditable(false);
        explanationEditorPane.setPreferredSize(new java.awt.Dimension(400, 70));
        jScrollPane2.setViewportView(explanationEditorPane);

        explanationPanel.add(jScrollPane2);

        jPanel1.add(explanationPanel);

        examplesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Examples"));
        examplesPanel.setLayout(new javax.swing.BoxLayout(examplesPanel, javax.swing.BoxLayout.LINE_AXIS));

        examplesEditorPane.setContentType("text/html");
        examplesEditorPane.setEditable(false);
        examplesEditorPane.setPreferredSize(new java.awt.Dimension(400, 70));
        jScrollPane3.setViewportView(examplesEditorPane);

        examplesPanel.add(jScrollPane3);

        jPanel1.add(examplesPanel);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        namePanel.setLayout(new javax.swing.BoxLayout(namePanel, javax.swing.BoxLayout.LINE_AXIS));

        nameTextField.setBackground(new java.awt.Color(255, 255, 255));
        nameTextField.setEditable(false);
        nameTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameTextField.setPreferredSize(new java.awt.Dimension(400, 30));
        namePanel.add(nameTextField);

        jPanel2.add(namePanel);

        regexPanel.setLayout(new javax.swing.BoxLayout(regexPanel, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Regular Expression: ");
        regexPanel.add(jLabel1);

        regexTextField.setEditable(false);
        regexTextField.setFont(new java.awt.Font("Tahoma", 1, 14));
        regexTextField.setForeground(javax.swing.UIManager.getDefaults().getColor("TitledBorder.titleColor"));
        regexTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        regexTextField.setPreferredSize(new java.awt.Dimension(400, 30));
        regexPanel.add(regexTextField);

        jPanel2.add(regexPanel);

        add(jPanel2, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane descriptionEditorPane;
    private javax.swing.JPanel descriptionPanel;
    private javax.swing.JEditorPane examplesEditorPane;
    private javax.swing.JPanel examplesPanel;
    private javax.swing.JEditorPane explanationEditorPane;
    private javax.swing.JPanel explanationPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel namePanel;
    public javax.swing.JTextField nameTextField;
    private javax.swing.JPanel regexPanel;
    public javax.swing.JTextField regexTextField;
    // End of variables declaration//GEN-END:variables


}
