/*
 * CleanupDialog.java
 *
 * Created on 11. Juli 2002, 12:48
 */

package org.exmaralda.partitureditor.jexmaraldaswing;

import org.exmaralda.common.helpers.Internationalizer;

/**
 *
 * @author  Thomas
 */
public class CleanupDialog extends JEscapeDialog {

    public boolean change = false; 
    
    /** Creates new form CleanupDialog
     * @param parent */
    public CleanupDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.getRootPane().setDefaultButton(okButton);
        Internationalizer.internationalizeDialogToolTips(this);        
    }

    public boolean removeUnusedSpeakers(){
        return removeUnusedSpeakersCheckBox.isSelected();        
    }


    public boolean removeEmptyEvents(){
        return removeEmptyEventsCheckBox.isSelected();        
    }

    public boolean bridgeGaps(){
        return bridgeGapsCheckBox.isSelected();        
    }
    
    public double getMaxDiff(){
        return bridgeGapsSlider.getValue();
    }

    public boolean smoothTimeline(){
        return smoothTimelineCheckBox.isSelected();
    }
    
    public double getThreshhold(){
        return smoothTimelineSlider.getValue();
    }

    public boolean removeUnusedTLI(){
        return removeUnusedTLICheckBox.isSelected();        
    }
    
    public boolean removeGaps(){
        return removeGapsCheckBox.isSelected();
    }
    
    public boolean normalizeIDs(){
        //return false;
        return normalizeIDsCheckBox.isSelected();
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        removeUnusedSpeakersPanel = new javax.swing.JPanel();
        removeUnusedSpeakersCheckBox = new javax.swing.JCheckBox();
        removeEmtpyEventsPanel = new javax.swing.JPanel();
        removeEmptyEventsCheckBox = new javax.swing.JCheckBox();
        smoothTimelinePanel = new javax.swing.JPanel();
        smoothTimelineCheckBox = new javax.swing.JCheckBox();
        smoothTimelineSlider = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        bridgeGapsPanel = new javax.swing.JPanel();
        bridgeGapsCheckBox = new javax.swing.JCheckBox();
        bridgeGapsSlider = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        removeUnusedTimelineITemsPanel = new javax.swing.JPanel();
        removeUnusedTLICheckBox = new javax.swing.JCheckBox();
        removeGapsPanel = new javax.swing.JPanel();
        removeGapsCheckBox = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        normalizeIDsPanel = new javax.swing.JPanel();
        normalizeIDsCheckBox = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        okCancelPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setTitle("Clean up");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        mainPanel.setLayout(new java.awt.GridLayout(7, 1));

        removeUnusedSpeakersPanel.setLayout(new javax.swing.BoxLayout(removeUnusedSpeakersPanel, javax.swing.BoxLayout.LINE_AXIS));

        removeUnusedSpeakersCheckBox.setSelected(true);
        removeUnusedSpeakersCheckBox.setText("Remove unused speakers");
        removeUnusedSpeakersCheckBox.setToolTipText("Remove events without a description");
        removeUnusedSpeakersPanel.add(removeUnusedSpeakersCheckBox);

        mainPanel.add(removeUnusedSpeakersPanel);

        removeEmtpyEventsPanel.setLayout(new javax.swing.BoxLayout(removeEmtpyEventsPanel, javax.swing.BoxLayout.LINE_AXIS));

        removeEmptyEventsCheckBox.setSelected(true);
        removeEmptyEventsCheckBox.setText("Remove empty events");
        removeEmptyEventsCheckBox.setToolTipText("Remove events without a description");
        removeEmtpyEventsPanel.add(removeEmptyEventsCheckBox);

        mainPanel.add(removeEmtpyEventsPanel);

        smoothTimelinePanel.setLayout(new javax.swing.BoxLayout(smoothTimelinePanel, javax.swing.BoxLayout.LINE_AXIS));

        smoothTimelineCheckBox.setSelected(true);
        smoothTimelineCheckBox.setText("Smooth timeline with a threshhold of");
        smoothTimelineCheckBox.setToolTipText("Treat nearby timeline items as identical ");
        smoothTimelinePanel.add(smoothTimelineCheckBox);

        smoothTimelineSlider.setMajorTickSpacing(50);
        smoothTimelineSlider.setMaximum(200);
        smoothTimelineSlider.setMinorTickSpacing(10);
        smoothTimelineSlider.setPaintLabels(true);
        smoothTimelineSlider.setPaintTicks(true);
        smoothTimelineSlider.setValue(10);
        smoothTimelineSlider.setPreferredSize(new java.awt.Dimension(180, 47));
        smoothTimelinePanel.add(smoothTimelineSlider);

        jLabel2.setText(" ms");
        smoothTimelinePanel.add(jLabel2);

        mainPanel.add(smoothTimelinePanel);

        bridgeGapsPanel.setLayout(new javax.swing.BoxLayout(bridgeGapsPanel, javax.swing.BoxLayout.LINE_AXIS));

        bridgeGapsCheckBox.setSelected(true);
        bridgeGapsCheckBox.setText("Bridge gaps smaller than ");
        bridgeGapsCheckBox.setToolTipText("Treat nearby timeline items as identical if the corresponding interval is a gap");
        bridgeGapsPanel.add(bridgeGapsCheckBox);

        bridgeGapsSlider.setMajorTickSpacing(250);
        bridgeGapsSlider.setMaximum(1000);
        bridgeGapsSlider.setMinorTickSpacing(100);
        bridgeGapsSlider.setPaintLabels(true);
        bridgeGapsSlider.setPaintTicks(true);
        bridgeGapsPanel.add(bridgeGapsSlider);

        jLabel1.setText(" ms");
        bridgeGapsPanel.add(jLabel1);

        mainPanel.add(bridgeGapsPanel);

        removeUnusedTimelineITemsPanel.setLayout(new javax.swing.BoxLayout(removeUnusedTimelineITemsPanel, javax.swing.BoxLayout.LINE_AXIS));

        removeUnusedTLICheckBox.setSelected(true);
        removeUnusedTLICheckBox.setText("Remove unused timeline items");
        removeUnusedTLICheckBox.setToolTipText("Remove timeline items where no event starts or ends");
        removeUnusedTimelineITemsPanel.add(removeUnusedTLICheckBox);

        mainPanel.add(removeUnusedTimelineITemsPanel);

        removeGapsPanel.setLayout(new javax.swing.BoxLayout(removeGapsPanel, javax.swing.BoxLayout.LINE_AXIS));

        removeGapsCheckBox.setText("Remove gaps");
        removeGapsCheckBox.setToolTipText("Remove gaps in the timeline (i.e. join events interrupted only by stretches of empty events, remove the intervening timeline items)");
        removeGapsPanel.add(removeGapsCheckBox);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(java.awt.Color.red);
        jLabel4.setText("   [USE WITH CAUTION!]");
        jLabel4.setToolTipText("Removing gaps s can have unintended side effects. Use this option only if you are very sure you know what you are doing. Make a safety backup of your file first.");
        removeGapsPanel.add(jLabel4);

        mainPanel.add(removeGapsPanel);

        normalizeIDsPanel.setLayout(new javax.swing.BoxLayout(normalizeIDsPanel, javax.swing.BoxLayout.LINE_AXIS));

        normalizeIDsCheckBox.setText("Normalize IDs");
        normalizeIDsCheckBox.setToolTipText("Normalize speaker, tier and timeline IDs - disabled, suspected to cause a serious bug with larg files");
        normalizeIDsPanel.add(normalizeIDsCheckBox);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(java.awt.Color.red);
        jLabel3.setText("   [USE WITH CAUTION!]");
        jLabel3.setToolTipText("Normalizing IDs can have unintended side effects. Use this option only if you are very sure you know what you are doing.  Make a safety backup of your file first.");
        normalizeIDsPanel.add(jLabel3);

        mainPanel.add(normalizeIDsPanel);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        okButton.setText("OK");
        okButton.setMaximumSize(new java.awt.Dimension(110, 27));
        okButton.setMinimumSize(new java.awt.Dimension(73, 26));
        okButton.setPreferredSize(new java.awt.Dimension(110, 27));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        okCancelPanel.add(okButton);

        cancelButton.setText("Cancel");
        cancelButton.setMaximumSize(new java.awt.Dimension(110, 27));
        cancelButton.setPreferredSize(new java.awt.Dimension(110, 27));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        okCancelPanel.add(cancelButton);

        getContentPane().add(okCancelPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // Add your handling code here:
        change = false;
        setVisible(false);
        dispose();        
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // Add your handling code here:
        change = true;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        change = false;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        new CleanupDialog(new javax.swing.JFrame(), true).show();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bridgeGapsCheckBox;
    private javax.swing.JPanel bridgeGapsPanel;
    private javax.swing.JSlider bridgeGapsSlider;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JCheckBox normalizeIDsCheckBox;
    private javax.swing.JPanel normalizeIDsPanel;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel okCancelPanel;
    private javax.swing.JCheckBox removeEmptyEventsCheckBox;
    private javax.swing.JPanel removeEmtpyEventsPanel;
    private javax.swing.JCheckBox removeGapsCheckBox;
    private javax.swing.JPanel removeGapsPanel;
    private javax.swing.JCheckBox removeUnusedSpeakersCheckBox;
    private javax.swing.JPanel removeUnusedSpeakersPanel;
    private javax.swing.JCheckBox removeUnusedTLICheckBox;
    private javax.swing.JPanel removeUnusedTimelineITemsPanel;
    private javax.swing.JCheckBox smoothTimelineCheckBox;
    private javax.swing.JPanel smoothTimelinePanel;
    private javax.swing.JSlider smoothTimelineSlider;
    // End of variables declaration//GEN-END:variables

    public boolean editCleanupParameters(){
        java.awt.Dimension dialogSize = this.getPreferredSize();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(screenSize.width/2 - dialogSize.width/2, screenSize.height/2 - dialogSize.height/2);
        show();
        return change;
    }
}
