/*
 * EditTierFormatTableDialog.java
 *
 * Created on 10. August 2001, 10:47
 */

package org.exmaralda.partitureditor.jexmaraldaswing;

import org.exmaralda.common.helpers.Internationalizer;
import org.exmaralda.partitureditor.jexmaralda.TierDescriptions;
import java.util.*;
import org.exmaralda.partitureditor.jexmaralda.*;

/**
 *
 * @author  Thomas
 * @version 
 */
public class EditTierFormatTableDialog extends JEscapeDialog {

    private EditTierFormatPanel editTierFormatPanel;
    private org.exmaralda.partitureditor.jexmaralda.TierFormatTable tierFormatTable;
    private javax.swing.DefaultListModel tierFormatsListModel;
    private org.exmaralda.partitureditor.jexmaralda.TierFormat currentTierFormat;
    Vector tierIDs = new Vector();

    /** Creates new form EditTierFormatTableDialog */
    public EditTierFormatTableDialog(java.awt.Frame parent,boolean modal, TierFormatTable tft, TierDescriptions td) {
        super (parent, modal);
        tierFormatTable = tft.makeCopy();
        editTierFormatPanel = new EditTierFormatPanel(new org.exmaralda.partitureditor.jexmaralda.TierFormat());
        String[] ids = tierFormatTable.getAllTierIDs();        
        tierFormatsListModel = new javax.swing.DefaultListModel();
        for (int pos=0; pos<ids.length; pos++){
           String listEntry = td.getTierDescriptionForTierID(ids[pos]) + " (" + ids[pos] + ")";
           tierFormatsListModel.addElement(listEntry);
           tierIDs.addElement(ids[pos]);
        }
        initComponents ();
        this.getRootPane().setDefaultButton(okButton);
        tierFormatList.setSelectedIndex(0);
        //editTierFormatPanel.setEnabled(false);
        pack ();
        Internationalizer.internationalizeDialogToolTips(this);
    }

    /** Creates new form EditTierFormatTableDialog */
    public EditTierFormatTableDialog(java.awt.Frame parent,boolean modal, org.exmaralda.partitureditor.jexmaralda.TierFormatTable tft) {
        this(parent, modal, tft, new org.exmaralda.partitureditor.jexmaralda.TierDescriptions());
    }

    public org.exmaralda.partitureditor.jexmaralda.TierFormatTable getTierFormatTable(){
        return tierFormatTable;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        getContentPane ().add (editTierFormatPanel, java.awt.BorderLayout.CENTER);
        okButton = new javax.swing.JButton();
        okButton.setMnemonic('O');
        cancelButton = new javax.swing.JButton();
        cancelButton.setMnemonic('C');
        tablePanel = new javax.swing.JPanel();
        tierFormatButtonPanel = new javax.swing.JPanel();
        addFormatButton = new javax.swing.JButton();
        addFormatButton.setMnemonic('A');
        removeFormatButton = new javax.swing.JButton();
        removeFormatButton.setMnemonic('R');
        tierFormatScrollPane = new javax.swing.JScrollPane();
        tierFormatList = new javax.swing.JList(tierFormatsListModel);

        setTitle("Edit format table");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setText("OK");
        okButton.setMaximumSize(new java.awt.Dimension(100, 27));
        okButton.setMinimumSize(new java.awt.Dimension(100, 27));
        okButton.setPreferredSize(new java.awt.Dimension(100, 27));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(okButton);

        cancelButton.setText("Cancel");
        cancelButton.setMaximumSize(new java.awt.Dimension(100, 27));
        cancelButton.setMinimumSize(new java.awt.Dimension(100, 27));
        cancelButton.setPreferredSize(new java.awt.Dimension(100, 27));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(cancelButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        tablePanel.setLayout(new java.awt.BorderLayout());

        tierFormatButtonPanel.setLayout(new javax.swing.BoxLayout(tierFormatButtonPanel, javax.swing.BoxLayout.Y_AXIS));

        addFormatButton.setText("Add format...");
        addFormatButton.setMaximumSize(new java.awt.Dimension(110, 27));
        addFormatButton.setMinimumSize(new java.awt.Dimension(110, 27));
        addFormatButton.setPreferredSize(new java.awt.Dimension(110, 27));
        tierFormatButtonPanel.add(addFormatButton);

        removeFormatButton.setText("Remove format");
        removeFormatButton.setMaximumSize(new java.awt.Dimension(110, 27));
        removeFormatButton.setMinimumSize(new java.awt.Dimension(110, 27));
        removeFormatButton.setPreferredSize(new java.awt.Dimension(110, 27));
        tierFormatButtonPanel.add(removeFormatButton);

        tablePanel.add(tierFormatButtonPanel, java.awt.BorderLayout.EAST);

        tierFormatList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tierFormatList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                tierFormatListValueChanged(evt);
            }
        });
        tierFormatScrollPane.setViewportView(tierFormatList);

        tablePanel.add(tierFormatScrollPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(tablePanel, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

  private void cancelButtonActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
// Add your handling code here:
    change=false;
    setVisible (false);
    dispose ();        
  }//GEN-LAST:event_cancelButtonActionPerformed

  private void okButtonActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
// Add your handling code here:
    if (tierFormatList.getSelectedIndex()!=-1){
        if (editTierFormatPanel.getTierFormat().getTierref().length()>0){
            tierFormatTable.setTierFormat(editTierFormatPanel.getTierFormat());
        }
    }
    change=true;
    setVisible (false);
    dispose ();    
  }//GEN-LAST:event_okButtonActionPerformed

  private void tierFormatListValueChanged (javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_tierFormatListValueChanged
// Add your handling code here:
    if (tierFormatList.getSelectedIndex()!=-1){
        if (editTierFormatPanel.getTierFormat().getTierref().length()>0){
            tierFormatTable.setTierFormat(editTierFormatPanel.getTierFormat());
        }
        String listEntry = ((String)tierFormatList.getSelectedValue());
        //String tierID = listEntry.substring(0,listEntry.indexOf(" ("));
        String tierID = (String)(tierIDs.elementAt(tierFormatList.getSelectedIndex()));
        try {editTierFormatPanel.setTierFormat(tierFormatTable.getTierFormatForTier(tierID));}
        catch (org.exmaralda.partitureditor.jexmaralda.JexmaraldaException je){}
        editTierFormatPanel.setEnabled(true);
    }
    else {
        editTierFormatPanel.setEnabled(false);
    }    
  }//GEN-LAST:event_tierFormatListValueChanged

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        change=false;
        setVisible (false);
        dispose ();
    }//GEN-LAST:event_closeDialog

    /**
    * @param args the command line arguments
    */
    public static void main (String args[]) {
//        new EditTierFormatTableDialog (new javax.swing.JFrame (), true).show ();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFormatButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton okButton;
    private javax.swing.JButton removeFormatButton;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JPanel tierFormatButtonPanel;
    private javax.swing.JList tierFormatList;
    private javax.swing.JScrollPane tierFormatScrollPane;
    // End of variables declaration//GEN-END:variables

    public boolean editTierFormatTable(boolean enableAddRemoveButtons){
        addFormatButton.setEnabled(enableAddRemoveButtons);
        removeFormatButton.setEnabled(enableAddRemoveButtons);
        java.awt.Dimension dialogSize = this.getPreferredSize();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(screenSize.width/2 - dialogSize.width/2, screenSize.height/2 - dialogSize.height/2);
        show();
        return change;
    }
}