/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewTierDialog.java
 *
 * Created on 04.02.2010, 15:37:27
 */

package org.exmaralda.exakt.wizard.newtranscriptionwizard;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author thomas
 */
public class NewTierDialog extends javax.swing.JDialog {

    public boolean approved = false;

    /** Creates new form NewTierDialog */
    public NewTierDialog(java.awt.Frame parent, boolean modal, boolean enableAnno) {
        super(parent, modal);
        initComponents();
        annotationRadioButton.setEnabled(enableAnno);
        annotationRadioButton.setSelected(enableAnno);
        descriptionRadioButton.setSelected(!enableAnno);
        categoryTextField.getDocument().addDocumentListener(new DocumentListener(){
            public void insertUpdate(DocumentEvent e) {evaluateCat();}
            public void removeUpdate(DocumentEvent e) {evaluateCat();}
            public void changedUpdate(DocumentEvent e) {evaluateCat();}
        });
    }
    
    private void evaluateCat() {
        okButton.setEnabled(categoryTextField.getText().length()>0);
    }


    public String[] getTierSpecification(){
        String[] returnValue = new String[2];
        if (annotationRadioButton.isSelected()){
            returnValue[0] = "a";
        } else {
            returnValue[0] = "d";
        }
        returnValue[1] = categoryTextField.getText();
        return returnValue;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        annotationRadioButton = new javax.swing.JRadioButton();
        descriptionRadioButton = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        categoryTextField = new javax.swing.JTextField();
        okCancelPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tier specification");

        mainPanel.setLayout(new javax.swing.BoxLayout(mainPanel, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Type: ");
        jPanel1.add(jLabel1);

        buttonGroup1.add(annotationRadioButton);
        annotationRadioButton.setSelected(true);
        annotationRadioButton.setText("A(nnotation)");
        jPanel1.add(annotationRadioButton);

        buttonGroup1.add(descriptionRadioButton);
        descriptionRadioButton.setText("D(escription)");
        jPanel1.add(descriptionRadioButton);

        mainPanel.add(jPanel1);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("Category: ");
        jPanel2.add(jLabel2);

        categoryTextField.setMaximumSize(new java.awt.Dimension(80, 20));
        categoryTextField.setPreferredSize(new java.awt.Dimension(80, 20));
        jPanel2.add(categoryTextField);

        mainPanel.add(jPanel2);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        okButton.setText("OK");
        okButton.setEnabled(false);
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        okCancelPanel.add(okButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        okCancelPanel.add(cancelButton);

        getContentPane().add(okCancelPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        approved = true;
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewTierDialog dialog = new NewTierDialog(new javax.swing.JFrame(), true, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton annotationRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField categoryTextField;
    private javax.swing.JRadioButton descriptionRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel okCancelPanel;
    // End of variables declaration//GEN-END:variables

}
