/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SpeakersWizardPanel.java
 *
 * Created on 25.01.2010, 16:42:30
 */

package org.exmaralda.exakt.wizard.newtranscriptionwizard;

import java.util.HashSet;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author thomas
 */
public class SpeakersWizardPanel extends javax.swing.JPanel {

    String[] speakers = new String[0];

    /** Creates new form SpeakersWizardPanel */
    public SpeakersWizardPanel() {
        initComponents();
        speakersTextArea.getDocument().addDocumentListener(new DocumentListener(){
            public void insertUpdate(DocumentEvent e) {parse();}
            public void removeUpdate(DocumentEvent e) {parse();}
            public void changedUpdate(DocumentEvent e) {parse();}
        });
    }

    public String[] getSpeakers(){
        return speakers;
    }

    void parse(){
        String text = speakersTextArea.getText();
        speakers = text.split("\\,");
        boolean duplicates = false;
        HashSet<String> hs = new HashSet<String>();
        int count=0;
        for (String s : speakers){
            s = s.trim();
            if (hs.contains(s)){
                duplicates = true;
                break;
            }
            hs.add(s);            
            speakers[count] = s;
            count++;
        }
        String label = Integer.toString(speakers.length) + " speakers. ";
        if (duplicates){
            label+="There are duplicate labels!";
        }
        parseLabel.setText(label);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        speakersTextArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        parseLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Enter speaker abbreviations, separated by commas:");
        add(jLabel1, java.awt.BorderLayout.NORTH);

        speakersTextArea.setColumns(20);
        speakersTextArea.setLineWrap(true);
        speakersTextArea.setRows(5);
        speakersTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(speakersTextArea);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(parseLabel);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel parseLabel;
    public javax.swing.JTextArea speakersTextArea;
    // End of variables declaration//GEN-END:variables

}
