/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TiersWizardPanel.java
 *
 * Created on 25.01.2010, 16:57:19
 */

package org.exmaralda.exakt.wizard.newtranscriptionwizard;

import java.awt.Component;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author thomas
 */
public class TiersWizardPanel extends javax.swing.JPanel {

    DefaultListModel beforeTiersListModel = new DefaultListModel();
    DefaultListModel afterTiersListModel = new DefaultListModel();
    DefaultListModel bottomSpeakerTiersListModel = new DefaultListModel();
    DefaultListModel bottomNoSpeakerTiersListModel = new DefaultListModel();

    /** Creates new form TiersWizardPanel */
    public TiersWizardPanel() {
        initComponents();
        beforeList.setModel(beforeTiersListModel);
        afterList.setModel(afterTiersListModel);
        bottomSpeakerList.setModel(bottomSpeakerTiersListModel);
        bottomNoSpeakerList.setModel(bottomNoSpeakerTiersListModel);

        DefaultListCellRenderer lc = new DefaultListCellRenderer(){

            @Override
            public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                String[] tierSpec = (String[])value;
                String text = "Type: ";
                if (tierSpec[0].equals("a")){
                    text+="A(nnotation)";
                } else {
                    text+="D(escription)";
                }
                if (tierSpec.length>1){
                    text+= " / Category: " + tierSpec[1];
                } else {
                    text+= " / Category: ";
                }
                return super.getListCellRendererComponent(list, text, index, isSelected, cellHasFocus);
            }

        };

        beforeList.setCellRenderer(lc);
        afterList.setCellRenderer(lc);
        bottomSpeakerList.setCellRenderer(lc);
        bottomNoSpeakerList.setCellRenderer(lc);

    }

    String[][] getSpecs(DefaultListModel model){
        String[][] result = new String[model.size()][2];
        for (int pos=0; pos<model.getSize(); pos++){
             String[] tierSpec = (String[])model.elementAt(pos);
             result[pos] = tierSpec;
        }
        return result;
    }

    public String[][][] getTierSpecifications(){
        String[][][] result = new String[4][][];
        result[0] = getSpecs(beforeTiersListModel);
        result[1] = getSpecs(afterTiersListModel);
        result[2] = getSpecs(bottomSpeakerTiersListModel);
        result[3] = getSpecs(bottomNoSpeakerTiersListModel);
        return result;
    }

    public String getMainCategory(){
        return categoryTextField.getText();
    }

    public void setMainCategory(String cat){
        categoryTextField.setText(cat);
    }

    void setTierSpecifications(String[][] beforeTiersSpec, String[][] afterTiersSpec, String[][] bottomSpeakerTiersSpec, String[][] bottomNoSpeakerTiersSpec) {
        for (String[] spec : beforeTiersSpec){
            beforeTiersListModel.addElement(spec);
        }
        for (String[] spec : afterTiersSpec){
            afterTiersListModel.addElement(spec);
        }
        for (String[] spec : bottomSpeakerTiersSpec){
            bottomSpeakerTiersListModel.addElement(spec);
        }
        for (String[] spec : bottomNoSpeakerTiersSpec){
            bottomNoSpeakerTiersListModel.addElement(spec);
        }
    }


    private void add(DefaultListModel listModel, boolean enableAnno) {
        NewTierDialog ntd = new NewTierDialog(null, true, enableAnno);
        ntd.setLocationRelativeTo(this);
        ntd.setVisible(true);
        if (ntd.approved){
            listModel.addElement(ntd.getTierSpecification());
        }
    }

    private void removeSelected(JList list){
        for (Object o : list.getSelectedValues()){
            ((DefaultListModel)(list.getModel())).removeElement(o);
        }
    }

    private void up(JList list){
        if (list.getSelectedIndex()<1) return;
        Object o = list.getSelectedValue();
        int i = list.getSelectedIndex();
        DefaultListModel model = (DefaultListModel)(list.getModel());
        model.removeElement(o);
        model.insertElementAt(o, i-1);
        list.setSelectedIndex(i-1);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        mainTierPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        categoryTextField = new javax.swing.JTextField();
        beforePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        beforeList = new javax.swing.JList();
        buttonPanel = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        upButton = new javax.swing.JButton();
        afterPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        afterList = new javax.swing.JList();
        buttonPanel1 = new javax.swing.JPanel();
        addButton1 = new javax.swing.JButton();
        removeButton1 = new javax.swing.JButton();
        upButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        bottomSpeakerPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        bottomSpeakerList = new javax.swing.JList();
        buttonPanel2 = new javax.swing.JPanel();
        addButton2 = new javax.swing.JButton();
        removeButton2 = new javax.swing.JButton();
        upButton2 = new javax.swing.JButton();
        bottomNoSpeakerPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        bottomNoSpeakerList = new javax.swing.JList();
        buttonPanel3 = new javax.swing.JPanel();
        addButton3 = new javax.swing.JButton();
        removeButton3 = new javax.swing.JButton();
        upButton3 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("For each speaker..."));
        jPanel2.setLayout(new java.awt.BorderLayout());

        mainTierPanel.setLayout(new javax.swing.BoxLayout(mainTierPanel, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Category for main transcription tier: ");
        mainTierPanel.add(jLabel1);

        categoryTextField.setFont(new java.awt.Font("Tahoma", 1, 14));
        categoryTextField.setForeground(new java.awt.Color(0, 0, 153));
        categoryTextField.setText("v");
        categoryTextField.setMaximumSize(new java.awt.Dimension(100, 23));
        categoryTextField.setPreferredSize(new java.awt.Dimension(50, 23));
        mainTierPanel.add(categoryTextField);

        jPanel2.add(mainTierPanel, java.awt.BorderLayout.CENTER);

        beforePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "...before the main transcription tier", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        beforePanel.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(258, 80));
        jScrollPane1.setViewportView(beforeList);

        beforePanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        buttonPanel.setLayout(new javax.swing.BoxLayout(buttonPanel, javax.swing.BoxLayout.Y_AXIS));

        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/exmaralda/folker/tangoicons/tango-icon-theme-0.8.1/16x16/actions/list-add.png"))); // NOI18N
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(addButton);

        removeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/exmaralda/folker/tangoicons/tango-icon-theme-0.8.1/16x16/actions/list-remove.png"))); // NOI18N
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(removeButton);

        upButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/exmaralda/folker/tangoicons/tango-icon-theme-0.8.1/16x16/actions/go-up.png"))); // NOI18N
        upButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(upButton);

        beforePanel.add(buttonPanel, java.awt.BorderLayout.EAST);

        jPanel2.add(beforePanel, java.awt.BorderLayout.PAGE_START);

        afterPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "...after the main transcription tier", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        afterPanel.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setPreferredSize(new java.awt.Dimension(258, 80));
        jScrollPane2.setViewportView(afterList);

        afterPanel.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        buttonPanel1.setLayout(new javax.swing.BoxLayout(buttonPanel1, javax.swing.BoxLayout.Y_AXIS));

        addButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/exmaralda/folker/tangoicons/tango-icon-theme-0.8.1/16x16/actions/list-add.png"))); // NOI18N
        addButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton1ActionPerformed(evt);
            }
        });
        buttonPanel1.add(addButton1);

        removeButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/exmaralda/folker/tangoicons/tango-icon-theme-0.8.1/16x16/actions/list-remove.png"))); // NOI18N
        removeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButton1ActionPerformed(evt);
            }
        });
        buttonPanel1.add(removeButton1);

        upButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/exmaralda/folker/tangoicons/tango-icon-theme-0.8.1/16x16/actions/go-up.png"))); // NOI18N
        upButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upButton1ActionPerformed(evt);
            }
        });
        buttonPanel1.add(upButton1);

        afterPanel.add(buttonPanel1, java.awt.BorderLayout.EAST);

        jPanel2.add(afterPanel, java.awt.BorderLayout.SOUTH);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("At the bottom of the partitur..."));
        jPanel1.setLayout(new java.awt.BorderLayout());

        bottomSpeakerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "...for each speaker", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        bottomSpeakerPanel.setLayout(new java.awt.BorderLayout());

        jScrollPane3.setPreferredSize(new java.awt.Dimension(258, 80));
        jScrollPane3.setViewportView(bottomSpeakerList);

        bottomSpeakerPanel.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        buttonPanel2.setLayout(new javax.swing.BoxLayout(buttonPanel2, javax.swing.BoxLayout.Y_AXIS));

        addButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/exmaralda/folker/tangoicons/tango-icon-theme-0.8.1/16x16/actions/list-add.png"))); // NOI18N
        addButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton2ActionPerformed(evt);
            }
        });
        buttonPanel2.add(addButton2);

        removeButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/exmaralda/folker/tangoicons/tango-icon-theme-0.8.1/16x16/actions/list-remove.png"))); // NOI18N
        removeButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButton2ActionPerformed(evt);
            }
        });
        buttonPanel2.add(removeButton2);

        upButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/exmaralda/folker/tangoicons/tango-icon-theme-0.8.1/16x16/actions/go-up.png"))); // NOI18N
        upButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upButton2ActionPerformed(evt);
            }
        });
        buttonPanel2.add(upButton2);

        bottomSpeakerPanel.add(buttonPanel2, java.awt.BorderLayout.EAST);

        jPanel1.add(bottomSpeakerPanel, java.awt.BorderLayout.EAST);

        bottomNoSpeakerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "...with no speaker", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        bottomNoSpeakerPanel.setLayout(new java.awt.BorderLayout());

        jScrollPane4.setPreferredSize(new java.awt.Dimension(258, 80));
        jScrollPane4.setViewportView(bottomNoSpeakerList);

        bottomNoSpeakerPanel.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        buttonPanel3.setLayout(new javax.swing.BoxLayout(buttonPanel3, javax.swing.BoxLayout.Y_AXIS));

        addButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/exmaralda/folker/tangoicons/tango-icon-theme-0.8.1/16x16/actions/list-add.png"))); // NOI18N
        addButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton3ActionPerformed(evt);
            }
        });
        buttonPanel3.add(addButton3);

        removeButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/exmaralda/folker/tangoicons/tango-icon-theme-0.8.1/16x16/actions/list-remove.png"))); // NOI18N
        removeButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButton3ActionPerformed(evt);
            }
        });
        buttonPanel3.add(removeButton3);

        upButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/exmaralda/folker/tangoicons/tango-icon-theme-0.8.1/16x16/actions/go-up.png"))); // NOI18N
        upButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upButton3ActionPerformed(evt);
            }
        });
        buttonPanel3.add(upButton3);

        bottomNoSpeakerPanel.add(buttonPanel3, java.awt.BorderLayout.EAST);

        jPanel1.add(bottomNoSpeakerPanel, java.awt.BorderLayout.WEST);

        add(jPanel1, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        add(beforeTiersListModel, true);
    }//GEN-LAST:event_addButtonActionPerformed

    private void addButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton1ActionPerformed
        add(afterTiersListModel, true);
    }//GEN-LAST:event_addButton1ActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        removeSelected(beforeList);
    }//GEN-LAST:event_removeButtonActionPerformed

    private void removeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButton1ActionPerformed
        removeSelected(afterList);
    }//GEN-LAST:event_removeButton1ActionPerformed

    private void upButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upButtonActionPerformed
        up(beforeList);
    }//GEN-LAST:event_upButtonActionPerformed

    private void upButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upButton1ActionPerformed
        up(afterList);
    }//GEN-LAST:event_upButton1ActionPerformed

    private void addButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton2ActionPerformed
        add(bottomSpeakerTiersListModel, true);
    }//GEN-LAST:event_addButton2ActionPerformed

    private void removeButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButton2ActionPerformed
        removeSelected(bottomSpeakerList);
    }//GEN-LAST:event_removeButton2ActionPerformed

    private void upButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upButton2ActionPerformed
        up(bottomSpeakerList);
    }//GEN-LAST:event_upButton2ActionPerformed

    private void addButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton3ActionPerformed
        add(bottomNoSpeakerTiersListModel, false);
    }//GEN-LAST:event_addButton3ActionPerformed

    private void removeButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButton3ActionPerformed
        removeSelected(bottomNoSpeakerList);
    }//GEN-LAST:event_removeButton3ActionPerformed

    private void upButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upButton3ActionPerformed
        up(bottomNoSpeakerList);
    }//GEN-LAST:event_upButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton addButton1;
    private javax.swing.JButton addButton2;
    private javax.swing.JButton addButton3;
    private javax.swing.JList afterList;
    private javax.swing.JPanel afterPanel;
    private javax.swing.JList beforeList;
    private javax.swing.JPanel beforePanel;
    private javax.swing.JList bottomNoSpeakerList;
    private javax.swing.JPanel bottomNoSpeakerPanel;
    private javax.swing.JList bottomSpeakerList;
    private javax.swing.JPanel bottomSpeakerPanel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel buttonPanel1;
    private javax.swing.JPanel buttonPanel2;
    private javax.swing.JPanel buttonPanel3;
    private javax.swing.JTextField categoryTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel mainTierPanel;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton removeButton1;
    private javax.swing.JButton removeButton2;
    private javax.swing.JButton removeButton3;
    private javax.swing.JButton upButton;
    private javax.swing.JButton upButton1;
    private javax.swing.JButton upButton2;
    private javax.swing.JButton upButton3;
    // End of variables declaration//GEN-END:variables

}
