/*
 * AboutDialog.java
 *
 * Created on 31. Juli 2008, 16:03
 */

package org.exmaralda.common.application;
import javax.swing.JOptionPane;
import org.exmaralda.common.*;
import org.exmaralda.folker.utilities.FOLKERInternationalizer;

/**
 *
 * @author  thomas
 */
public class AboutDialog extends javax.swing.JDialog {

    ExmaraldaApplication application;
    
    /** Creates new form AboutDialog */
    public AboutDialog(java.awt.Frame parent, boolean modal, ExmaraldaApplication app) {
        super(parent, modal);
        application = app;
        initComponents();
        setTitle("About " + app.getApplicationName() + " " + app.getVersion());
        iconLabel.setIcon(app.getWelcomeScreen());
        String javaVersion = System.getProperty("java.version");
        String os = System.getProperty("os.name");
        String osVersion = System.getProperty("os.version");
        osLabel.setText(os);
        osVersionLabel.setText(osVersion);
        javaVersionLabel.setText(javaVersion);
        softwareVersionLabel.setText(app.getVersion());
        buildTimeLabel.setText(org.exmaralda.common.EXMARaLDAConstants.BUILD_TIME);

        // added 19-05-2009: Folker always German
        // changed 17-06-2010: Folker now internationalized
        if (app.getApplicationName().toUpperCase().indexOf("FOLKER")>=0){
            setTitle(FOLKERInternationalizer.getString("dialog.about.about") + app.getApplicationName() + " " + app.getVersion());
            jLabel1.setText(FOLKERInternationalizer.getString("dialog.about.os"));
            jLabel3.setText(FOLKERInternationalizer.getString("dialog.about.osversion"));
            jLabel5.setText(FOLKERInternationalizer.getString("dialog.about.javaversion"));
            jLabel7.setText(FOLKERInternationalizer.getString("dialog.about.softwareversion"));
            jLabel9.setText(FOLKERInternationalizer.getString("dialog.about.buildtime"));
            copyDebugButton.setText(FOLKERInternationalizer.getString("dialog.about.copydebug"));
        }




        pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        iconLabel = new javax.swing.JLabel();
        versionInfoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        osLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        osVersionLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        javaVersionLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        softwareVersionLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        buildTimeLabel = new javax.swing.JLabel();
        buttonsPanel = new javax.swing.JPanel();
        copyDebugButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        mainPanel.setLayout(new java.awt.BorderLayout());

        iconLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        mainPanel.add(iconLabel, java.awt.BorderLayout.CENTER);

        versionInfoPanel.setLayout(new java.awt.GridLayout(5, 2));

        jLabel1.setText("Operating system: ");
        versionInfoPanel.add(jLabel1);

        osLabel.setText("jLabel1");
        versionInfoPanel.add(osLabel);

        jLabel3.setText("OS version: ");
        versionInfoPanel.add(jLabel3);

        osVersionLabel.setText("jLabel1");
        versionInfoPanel.add(osVersionLabel);

        jLabel5.setText("Java version:");
        versionInfoPanel.add(jLabel5);

        javaVersionLabel.setText("jLabel1");
        versionInfoPanel.add(javaVersionLabel);

        jLabel7.setText("Software version: ");
        versionInfoPanel.add(jLabel7);

        softwareVersionLabel.setText("jLabel1");
        versionInfoPanel.add(softwareVersionLabel);

        jLabel9.setText("Build time: ");
        versionInfoPanel.add(jLabel9);

        buildTimeLabel.setText("jLabel1");
        versionInfoPanel.add(buildTimeLabel);

        mainPanel.add(versionInfoPanel, java.awt.BorderLayout.SOUTH);

        jPanel1.add(mainPanel, java.awt.BorderLayout.CENTER);

        copyDebugButton.setText("Copy debug info");
        copyDebugButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyDebugButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(copyDebugButton);

        jPanel1.add(buttonsPanel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void copyDebugButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyDebugButtonActionPerformed
    String debugInfo = Logger.getLog(application);
    java.awt.datatransfer.StringSelection ss = new java.awt.datatransfer.StringSelection(debugInfo);
    this.getToolkit().getSystemClipboard().setContents(ss,ss);
    JOptionPane.showMessageDialog(rootPane, "Debug information copied to the system clipboard. \n Please paste in email or text document as appropriate.");
}//GEN-LAST:event_copyDebugButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AboutDialog dialog = new AboutDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buildTimeLabel;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton copyDebugButton;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel javaVersionLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel osLabel;
    private javax.swing.JLabel osVersionLabel;
    private javax.swing.JLabel softwareVersionLabel;
    private javax.swing.JPanel versionInfoPanel;
    // End of variables declaration//GEN-END:variables

}
