/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AbstractWizardPanel.java
 *
 * Created on 22.01.2010, 15:23:44
 */

package org.exmaralda.exakt.wizard;

import javax.swing.JPanel;

/**
 *
 * @author thomas
 */
public class AbstractWizardPanel extends javax.swing.JPanel {

    /** Creates new form AbstractWizardPanel */
    public AbstractWizardPanel(String title, String helpText, JPanel mainPanel) {
        initComponents();
        helpEditorPane.setText(helpText);
        helpEditorPane.setCaretPosition(0);
        titleLabel.setText(title);
        add(mainPanel, java.awt.BorderLayout.CENTER);
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        helpEditorPane = new javax.swing.JEditorPane();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(600, 120));

        helpEditorPane.setBackground(new java.awt.Color(204, 204, 255));
        helpEditorPane.setContentType("text/html");
        helpEditorPane.setEditable(false);
        helpEditorPane.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
        jScrollPane1.setViewportView(helpEditorPane);

        add(jScrollPane1, java.awt.BorderLayout.SOUTH);

        titlePanel.setBackground(new java.awt.Color(255, 255, 153));
        titlePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        titlePanel.setForeground(new java.awt.Color(0, 51, 204));

        titleLabel.setBackground(new java.awt.Color(255, 255, 255));
        titleLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 51, 153));
        titleLabel.setText("jLabel1");
        titlePanel.add(titleLabel);

        add(titlePanel, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane helpEditorPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables

}
