/*
 * CalculateAnalysisPanel.java
 *
 * Created on 26. Maerz 2008, 09:28
 */

package org.exmaralda.exakt.exmaraldaSearch.swing;

import java.util.*;
import javax.swing.*;
import org.exmaralda.exakt.exmaraldaSearch.*;
import org.exmaralda.exakt.exmaraldaSearch.swing.*;


/**
 *
 * @author  thomas
 */
public class CalculateAnalysisPanel extends javax.swing.JPanel {
    
    /** Creates new form CalculateAnalysisPanel */
    public CalculateAnalysisPanel(COMACorpusInterface c) {
        initComponents();
        DefaultComboBoxModel dcbm1 = new DefaultComboBoxModel();
        DefaultComboBoxModel dcbm2 = new DefaultComboBoxModel();
        for (String attribute : c.getSpeakerAttributes()){
            dcbm1.addElement(attribute + " [S]");
            dcbm2.addElement(attribute + " [S]");
        }
        for (String attribute : c.getCommunicationAttributes()){
            dcbm1.addElement(attribute + " [C]");
            dcbm2.addElement(attribute + " [C]");
        }
        for (String attribute : c.getTranscriptionAttributes()){
            dcbm1.addElement(attribute + " [T]");
            dcbm2.addElement(attribute + " [T]");
        }
        firstValueComboBox.setModel(dcbm1);
        secondValueComboBox.setModel(dcbm2);
    }
    
    public String[] getValues(){
        String[] returnValue = new String[4];
        returnValue[0] = (String)(firstValueComboBox.getSelectedItem());
        returnValue[1] = (String)(operatorComboBox.getSelectedItem());
        returnValue[2] = (String)(secondValueComboBox.getSelectedItem());
        returnValue[3] = (String)(dataTypeComboBox.getSelectedItem());        
        return returnValue;
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        firstValueComboBox = new javax.swing.JComboBox();
        operatorComboBox = new javax.swing.JComboBox();
        secondValueComboBox = new javax.swing.JComboBox();
        dataTypeComboBox = new javax.swing.JComboBox();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        firstValueComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        firstValueComboBox.setMaximumSize(new java.awt.Dimension(30000, 22));
        firstValueComboBox.setPreferredSize(new java.awt.Dimension(200, 22));
        add(firstValueComboBox);

        operatorComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- (Minus)" }));
        operatorComboBox.setMaximumSize(new java.awt.Dimension(30000, 22));
        add(operatorComboBox);

        secondValueComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        secondValueComboBox.setMaximumSize(new java.awt.Dimension(30000, 22));
        secondValueComboBox.setPreferredSize(new java.awt.Dimension(200, 22));
        add(secondValueComboBox);

        dataTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Date" }));
        dataTypeComboBox.setMaximumSize(new java.awt.Dimension(30000, 22));
        dataTypeComboBox.setPreferredSize(new java.awt.Dimension(66, 22));
        add(dataTypeComboBox);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox dataTypeComboBox;
    private javax.swing.JComboBox firstValueComboBox;
    private javax.swing.JComboBox operatorComboBox;
    private javax.swing.JComboBox secondValueComboBox;
    // End of variables declaration//GEN-END:variables
    
}
