/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OpenRemoteCorpusDialog.java
 *
 * Created on 28.10.2009, 11:08:42
 */

package org.exmaralda.exakt.exmaraldaSearch.swing;

import java.awt.Frame;
import java.util.Vector;
import java.util.prefs.Preferences;
import org.exmaralda.common.ExmaraldaApplication;

/**
 *
 * @author thomas
 */
public class OpenDBCorpusDialog extends javax.swing.JDialog {

    public boolean approved = false;
    Vector<String> corpusNames = new Vector<String>();
    Vector<String> corpusURLs = new Vector<String>();
    Frame parentFrame;


    /** Creates new form OpenRemoteCorpusDialog */
    public OpenDBCorpusDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        parentFrame = parent;
        initComponents();
        getRootPane().setDefaultButton(okButton);
        if (parent instanceof ExmaraldaApplication){
            ExmaraldaApplication ea = (ExmaraldaApplication)parent;
            Preferences prefs = java.util.prefs.Preferences.userRoot().node(ea.getPreferencesNode());
            String url = prefs.get("DB-URL", "");
            urlTextField.setText(url);
            String cn = prefs.get("DB-Corpus-Name", "");
            corpusNameTextField.setText(cn);
            String username = prefs.get("DB-Corpus-Username", "");
            urlTextField.setText(url);
            usernameTextField.setText(username);
            if (username.length()==0){
                usernameTextField.requestFocus();
            } else {
                passwordField.requestFocus();
            }
            
        }
    }

    public String getURL(){
        return urlTextField.getText();
    }

    public String getCorpusName(){
        return corpusNameTextField.getText();
    }

    public String getUsername(){
        return usernameTextField.getText();
    }

    public char[] getPassword(){
        return passwordField.getPassword();
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        urlTextField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        corpusNameTextField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        okCancelPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        openCatalogPanel = new javax.swing.JPanel();
        openCatalogButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Open Database Corpus");

        mainPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        mainPanel.setLayout(new java.awt.GridLayout(4, 1));

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Database URL: ");
        jLabel1.setToolTipText("The URL of the COMA corpus");
        jLabel1.setMaximumSize(new java.awt.Dimension(130, 14));
        jLabel1.setPreferredSize(new java.awt.Dimension(130, 14));
        jPanel3.add(jLabel1);

        urlTextField.setMaximumSize(new java.awt.Dimension(1200, 24));
        urlTextField.setPreferredSize(new java.awt.Dimension(600, 24));
        jPanel3.add(urlTextField);

        mainPanel.add(jPanel3);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("Corpus name: ");
        jLabel2.setToolTipText("The URL of the COMA corpus");
        jLabel2.setMaximumSize(new java.awt.Dimension(130, 14));
        jLabel2.setPreferredSize(new java.awt.Dimension(130, 14));
        jPanel4.add(jLabel2);

        corpusNameTextField.setMaximumSize(new java.awt.Dimension(1200, 24));
        corpusNameTextField.setPreferredSize(new java.awt.Dimension(200, 24));
        jPanel4.add(corpusNameTextField);

        mainPanel.add(jPanel4);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        usernameLabel.setText("Username: ");
        usernameLabel.setMaximumSize(new java.awt.Dimension(130, 14));
        usernameLabel.setPreferredSize(new java.awt.Dimension(130, 14));
        jPanel5.add(usernameLabel);

        usernameTextField.setMaximumSize(new java.awt.Dimension(300, 24));
        usernameTextField.setPreferredSize(new java.awt.Dimension(200, 24));
        jPanel5.add(usernameTextField);

        mainPanel.add(jPanel5);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        passwordLabel.setText("Password: ");
        passwordLabel.setMaximumSize(new java.awt.Dimension(130, 14));
        passwordLabel.setPreferredSize(new java.awt.Dimension(130, 14));
        jPanel6.add(passwordLabel);

        passwordField.setMaximumSize(new java.awt.Dimension(300, 24));
        passwordField.setPreferredSize(new java.awt.Dimension(200, 24));
        jPanel6.add(passwordField);

        mainPanel.add(jPanel6);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        okButton.setText("OK");
        okButton.setMaximumSize(new java.awt.Dimension(65, 23));
        okButton.setMinimumSize(new java.awt.Dimension(65, 23));
        okButton.setPreferredSize(new java.awt.Dimension(65, 23));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        okCancelPanel.add(okButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        okCancelPanel.add(cancelButton);

        getContentPane().add(okCancelPanel, java.awt.BorderLayout.SOUTH);

        openCatalogButton.setFont(new java.awt.Font("Tahoma", 1, 12));
        openCatalogButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/exmaralda/exakt/exmaraldaSearch/swing/resources/search_catalog_icon.gif"))); // NOI18N
        openCatalogButton.setText("Catalog lookup...");
        openCatalogButton.setToolTipText("Pick connection data from a catalog of EXMARaLDA resources");
        openCatalogButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        openCatalogButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        openCatalogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openCatalogButtonActionPerformed(evt);
            }
        });
        openCatalogPanel.add(openCatalogButton);

        getContentPane().add(openCatalogPanel, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        if (this.getParent() instanceof ExmaraldaApplication){
            ExmaraldaApplication ea = (ExmaraldaApplication)getParent();
            Preferences prefs = java.util.prefs.Preferences.userRoot().node(ea.getPreferencesNode());
            prefs.put("DB-URL", urlTextField.getText());
            prefs.put("DB-Corpus-Name", corpusNameTextField.getText());
            prefs.put("DB-Corpus-Username", usernameTextField.getText());            
        }
        approved = true;
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void openCatalogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openCatalogButtonActionPerformed
        CatalogLookupDialog cld = new CatalogLookupDialog(parentFrame,true, 
                CatalogLookupDialog.DB_RESOURCE_SELECTION_XPATH);
        cld.setLocationRelativeTo(this);
        cld.setVisible(true);
        if (cld.approved){
            urlTextField.setText(cld.getDBURL());
            corpusNameTextField.setText(cld.getDBCorpusName());
        }
    }//GEN-LAST:event_openCatalogButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                OpenDBCorpusDialog dialog = new OpenDBCorpusDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField corpusNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel okCancelPanel;
    private javax.swing.JButton openCatalogButton;
    private javax.swing.JPanel openCatalogPanel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField urlTextField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables

}
